import { Hono } from 'hono';
import { v4 as uuidv4 } from 'uuid';
import { Env,getDb } from '../db';
import { getActor } from '../utils/actors';
import { apiError } from '../utils/http';
import { serializeJsonObject } from '../utils/json';
import { computeInsight,mergeInsightFilters,rowsToCsv } from '../utils/insights';
import { sha256Hex } from '../middleware/auth';

const router=new Hono<{Bindings:Env}>();type Row=Record<string,any>;
const MEASURES=new Set(['issue_count','effort','cycle_time','lead_time','triage_time','issue_age']);
const DIMS=new Set(['none','status','status_type','owner','business','priority','tag','estimate','template','project','initiative','cycle','release','pipeline','created_date','completed_date','started_date','due_date','burn_up']);
const SEGMENTS=new Set(['status','status_type','owner','business','priority','tag','estimate','template','project','initiative','cycle','release','pipeline']);
const CHARTS=new Set(['bar','scatter','burn_up','metric','table']);const GROUPINGS=new Set(['daily','weekly','monthly','quarterly','yearly']);

export function validateInsightBody(body:Row,partial=false){const errors:string[]=[];if(!partial&&(typeof body.name!=='string'||!body.name.trim()))errors.push('name is required');if(body.name!==undefined&&(typeof body.name!=='string'||!body.name.trim()))errors.push('name must be non-empty');if(body.measure!==undefined&&!MEASURES.has(String(body.measure)))errors.push('measure is invalid');if(body.slice_by!==undefined&&!DIMS.has(String(body.slice_by)))errors.push('slice_by is invalid');if(body.segment_by!==undefined&&body.segment_by!==null&&!SEGMENTS.has(String(body.segment_by)))errors.push('segment_by is invalid');if(body.chart_type!==undefined&&!CHARTS.has(String(body.chart_type)))errors.push('chart_type is invalid');if(body.time_grouping!==undefined&&!GROUPINGS.has(String(body.time_grouping)))errors.push('time_grouping is invalid');if(body.filters!==undefined&&(!body.filters||typeof body.filters!=='object'||Array.isArray(body.filters)))errors.push('filters must be an object');return errors}

async function loadAnalyticsActions(supabase:ReturnType<typeof getDb>):Promise<{actions:Row[];unestimatedValue:number}>{
  const actionResult=await supabase.from('atlas_actions').select('*');if(actionResult.error)throw actionResult.error;const actions=(actionResult.data||[])as Row[];const projectIds=Array.from(new Set(actions.map(item=>item.project_id).filter(Boolean)));const cycleIds=Array.from(new Set(actions.map(item=>item.cycle_id).filter(Boolean)));const templateIds=Array.from(new Set(actions.map(item=>item.template_id).filter(Boolean)));
  const [projects,cycles,templates,memberships,releaseAssociations,estimateSettings]=await Promise.all([
    projectIds.length?supabase.from('atlas_projects').select('id,name').in('id',projectIds):Promise.resolve({data:[],error:null}),
    cycleIds.length?supabase.from('atlas_cycles').select('id,name').in('id',cycleIds):Promise.resolve({data:[],error:null}),
    templateIds.length?supabase.from('atlas_templates').select('id,name').in('id',templateIds):Promise.resolve({data:[],error:null}),
    projectIds.length?supabase.from('atlas_initiative_projects').select('project_id,initiative_id').eq('status','active').in('project_id',projectIds):Promise.resolve({data:[],error:null}),
    supabase.from('atlas_release_actions').select('*').eq('status','active'),
    supabase.from('atlas_config').select('value').eq('key','estimate_settings').maybeSingle(),
  ]);for(const result of[projects,cycles,templates,memberships,releaseAssociations,estimateSettings])if(result.error)throw result.error;
  const initiativeIds=Array.from(new Set((memberships.data||[]).map(item=>item.initiative_id)));const releaseIds=Array.from(new Set((releaseAssociations.data||[]).map(item=>item.release_id)));const initiatives=initiativeIds.length?await supabase.from('atlas_initiatives').select('id,name').in('id',initiativeIds):{data:[],error:null};const releases=releaseIds.length?await supabase.from('atlas_releases').select('id,pipeline_id,name,version,status,released_at').in('id',releaseIds):{data:[],error:null};if(initiatives.error)throw initiatives.error;if(releases.error)throw releases.error;const pipelineIds=Array.from(new Set((releases.data||[]).map(item=>item.pipeline_id)));const pipelines=pipelineIds.length?await supabase.from('atlas_release_pipelines').select('id,name').in('id',pipelineIds):{data:[],error:null};if(pipelines.error)throw pipelines.error;
  const hydrated:Row[]=actions.map(action=>({...action,project_name:(projects.data||[]).find(item=>item.id===action.project_id)?.name||null,cycle_name:(cycles.data||[]).find(item=>item.id===action.cycle_id)?.name||null,template_name:(templates.data||[]).find(item=>item.id===action.template_id)?.name||null,initiatives:(memberships.data||[]).filter(item=>item.project_id===action.project_id).map(item=>(initiatives.data||[]).find(candidate=>candidate.id===item.initiative_id)).filter(Boolean),releases:(releaseAssociations.data||[]).filter(item=>item.action_id===action.id).map(item=>{const release=(releases.data||[]).find(candidate=>candidate.id===item.release_id);return{...item,release,pipeline:release?(pipelines.data||[]).find(candidate=>candidate.id===release.pipeline_id):null}})}as Row));
  const value=estimateSettings.data?.value as Row|undefined;return{actions:hydrated,unestimatedValue:Number.isSafeInteger(value?.unestimated_value)?Number(value?.unestimated_value):1};
}

async function evaluateInsight(supabase:ReturnType<typeof getDb>,insight:Row,extraFilters:Row={}){const loaded=await loadAnalyticsActions(supabase);return computeInsight(loaded.actions,{...insight,filters:mergeInsightFilters(insight.filters||{},extraFilters)}, {unestimatedValue:loaded.unestimatedValue});}
function transitionError(c:any,error:{code?:string;message?:string}){const message=error.message||'';if(error.code==='40001'||message.includes('REVISION_CONFLICT'))return apiError(c,409,'REVISION_CONFLICT','The analytics definition changed.');if(error.code==='42501')return apiError(c,403,'OWNER_REQUIRED','Only the owner can change analytics lifecycle.');if(error.code==='P0002')return apiError(c,404,'ANALYTICS_NOT_FOUND','Analytics definition not found.');return apiError(c,500,'ANALYTICS_TRANSITION_FAILED','Unable to transition analytics state.')}

router.get('/',async c=>{try{const{status,scope,business}=c.req.query();let query=getDb(c.env).from('atlas_insights').select('*');query=query.eq('status',status||'active');if(scope)query=query.eq('scope',scope);if(business)query=query.eq('business',business);const{data,error}=await query.order('name');if(error)throw error;return c.json(data||[])}catch(error){console.error(`[insights] list error: ${(error as Error).message}`);return apiError(c,500,'INSIGHT_LIST_FAILED','Unable to load insights.')}});
router.post('/',async c=>{try{const body=await c.req.json<Row>().catch(()=>({}as Row));const errors=validateInsightBody(body);if(errors.length)return apiError(c,400,'INVALID_INSIGHT',errors.join('; '));const actor=getActor(c);const{data,error}=await getDb(c.env).from('atlas_insights').insert({id:uuidv4(),name:body.name.trim(),description:body.description||'',measure:body.measure||'issue_count',slice_by:body.slice_by||'status',segment_by:body.segment_by||null,chart_type:body.chart_type||'bar',filters:serializeJsonObject(body.filters||{}),time_grouping:body.time_grouping||'monthly',include_archived:body.include_archived===true,exclude_no_priority:body.exclude_no_priority===true,saved_view_id:body.saved_view_id||null,scope:body.scope||'workspace',business:body.scope==='business'?body.business:null,owner_id:'ransomed',created_by:actor,updated_by:actor}).select().single();if(error)throw error;return c.json(data,201)}catch(error){console.error(`[insights] create error: ${(error as Error).message}`);return apiError(c,500,'INSIGHT_CREATE_FAILED','Unable to create insight.')}});
router.get('/:id',async c=>{try{const supabase=getDb(c.env);const[insight,snapshots]=await Promise.all([supabase.from('atlas_insights').select('*').eq('id',c.req.param('id')).maybeSingle(),supabase.from('atlas_insight_snapshots').select('*').eq('insight_id',c.req.param('id')).order('created_at',{ascending:false}).limit(50)]);if(insight.error)throw insight.error;if(snapshots.error)throw snapshots.error;if(!insight.data)return apiError(c,404,'INSIGHT_NOT_FOUND','Insight not found.');return c.json({...insight.data,snapshots:snapshots.data||[]})}catch(error){console.error(`[insights] detail error: ${(error as Error).message}`);return apiError(c,500,'INSIGHT_LOAD_FAILED','Unable to load insight.')}});
router.put('/:id',async c=>{try{const body=await c.req.json<Row>().catch(()=>({}as Row));if(!Number.isSafeInteger(body.expected_revision))return apiError(c,400,'INVALID_REVISION','expected_revision is required.');const supabase=getDb(c.env);const{data:existing,error:fetchError}=await supabase.from('atlas_insights').select('*').eq('id',c.req.param('id')).maybeSingle();if(fetchError)throw fetchError;if(!existing)return apiError(c,404,'INSIGHT_NOT_FOUND','Insight not found.');const candidate={...existing,...body};const errors=validateInsightBody(candidate,true);if(errors.length)return apiError(c,400,'INVALID_INSIGHT',errors.join('; '));const updates:Row={};for(const field of['name','description','measure','slice_by','segment_by','chart_type','time_grouping','include_archived','exclude_no_priority','saved_view_id','scope','business'])if(body[field]!==undefined)updates[field]=body[field]===''?null:body[field];if(body.filters!==undefined)updates.filters=serializeJsonObject(body.filters);updates.revision=existing.revision+1;updates.updated_by=getActor(c);updates.updated_at=new Date().toISOString();const{data,error}=await supabase.from('atlas_insights').update(updates).eq('id',existing.id).eq('revision',body.expected_revision).select().maybeSingle();if(error)throw error;if(!data)return apiError(c,409,'REVISION_CONFLICT','The insight changed.');return c.json(data)}catch(error){console.error(`[insights] update error: ${(error as Error).message}`);return apiError(c,500,'INSIGHT_UPDATE_FAILED','Unable to update insight.')}});
router.post('/:id/run',async c=>{try{const body=await c.req.json<Row>().catch(()=>({}as Row));const supabase=getDb(c.env);const{data:insight,error}=await supabase.from('atlas_insights').select('*').eq('id',c.req.param('id')).eq('status','active').maybeSingle();if(error)throw error;if(!insight)return apiError(c,404,'INSIGHT_NOT_FOUND','Insight not found.');const result=await evaluateInsight(supabase,insight,serializeJsonObject(body.filters||{}));if(body.persist_snapshot===true){const snapshot=await supabase.rpc('record_atlas_insight_snapshot',{p_snapshot_id:uuidv4(),p_insight_id:insight.id,p_insight_revision:insight.revision,p_result:result,p_source_watermark:result.source_watermark,p_actor:getActor(c)});if(snapshot.error)throw snapshot.error;return c.json({...result,snapshot_id:snapshot.data.id})}return c.json(result)}catch(error){console.error(`[insights] run error: ${(error as Error).message}`);return apiError(c,500,'INSIGHT_RUN_FAILED','Unable to evaluate insight.')}});
router.get('/:id/export.csv',async c=>{try{const supabase=getDb(c.env);const{data:insight,error}=await supabase.from('atlas_insights').select('*').eq('id',c.req.param('id')).maybeSingle();if(error)throw error;if(!insight)return apiError(c,404,'INSIGHT_NOT_FOUND','Insight not found.');const result=await evaluateInsight(supabase,insight);const csv=rowsToCsv(result.table);const hash=await sha256Hex(csv);const receipt=await supabase.rpc('record_atlas_export_receipt',{p_receipt_id:uuidv4(),p_export_type:'insight',p_insight_id:insight.id,p_filters:insight.filters,p_row_count:result.table.length,p_content_sha256:hash,p_actor:getActor(c)});if(receipt.error)throw receipt.error;c.header('Content-Type','text/csv; charset=utf-8');c.header('Content-Disposition',`attachment; filename="atlas-insight-${insight.id}.csv"`);c.header('X-Atlas-Export-SHA256',hash);return c.body(csv)}catch(error){console.error(`[insights] export error: ${(error as Error).message}`);return apiError(c,500,'INSIGHT_EXPORT_FAILED','Unable to export insight.')}});
async function transition(c:any,restore:boolean){const body=await c.req.json().catch(()=>({}))as Row;const{data,error}=await getDb(c.env).rpc('transition_atlas_analytics_entity',{p_entity_type:'insight',p_entity_id:c.req.param('id'),p_restore:restore,p_actor:getActor(c),p_expected_revision:body.expected_revision});if(error)return transitionError(c,error);return c.json(data)}
router.post('/:id/archive',c=>transition(c,false));router.post('/:id/restore',c=>transition(c,true));

export { loadAnalyticsActions,evaluateInsight };
export default router;
