import { Hono } from 'hono';
import { v4 as uuidv4 } from 'uuid';
import { Env, getDb } from '../db';
import { getActor } from '../utils/actors';
import { apiError } from '../utils/http';
import { validateKnownBusinessId } from '../utils/referenceData';
import { dispatchPendingDeliveries } from '../services/integrations';
import {
  buildWebhookSigningInput, containsCredentialLikeKey, hmacSha256Hex, integrationSecret, isFreshWebhookTimestamp,
  readBoundedText, sha256Hex, timingSafeHexEqual, validateIntegrationEndpoint,
  validWebhookHeaders,
} from '../utils/integrations';

type Row = Record<string, any>;
const integrationsRouter = new Hono<{ Bindings: Env }>();
const hooksRouter = new Hono<{ Bindings: Env }>();
const PROVIDERS=new Set(['webhook','slack','email','calendar','github','generic']);
const DIRECTIONS=new Set(['inbound','outbound','bidirectional']);
const CATEGORIES=new Set(['all','assignments','mentions','status_changes','comments','project_updates','initiative_updates','cycles','documents','releases','analytics','workflows','system']);
const RESOURCES=new Set(['all','action','project','initiative','cycle','document','template','comment','reaction','release','insight','workflow','saved_view','system']);

function revision(value:unknown){return Number.isSafeInteger(value)&&Number(value)>=0?Number(value):null;}
function integrationError(c:any,error:any,fallback:string){const message=String(error?.message||'');if(error?.code==='40001'||message.includes('REVISION_CONFLICT'))return apiError(c,409,'REVISION_CONFLICT','The integration changed. Refresh and retry.');if(error?.code==='42501'||message.includes('OWNER_REQUIRED'))return apiError(c,403,'OWNER_REQUIRED','Only the ATLAS owner can configure integrations.');if(error?.code==='P0002'||message.includes('NOT_FOUND'))return apiError(c,404,'INTEGRATION_NOT_FOUND','Integration resource not found.');if(error?.code==='55000')return apiError(c,409,'INTEGRATION_STATE_CONFLICT',message||fallback);if(['22023','23503','23505','23514'].includes(String(error?.code)))return apiError(c,400,'INTEGRATION_INVALID',message||fallback);console.error(`[integrations] ${fallback}: ${message||error}`);return apiError(c,500,'INTEGRATION_OPERATION_FAILED',fallback);}
function validArray(value:unknown,allowed:Set<string>){return Array.isArray(value)&&value.length>0&&value.every(item=>typeof item==='string'&&allowed.has(item));}
function cleanConfig(value:unknown){if(value===undefined)return{};if(!value||typeof value!=='object'||Array.isArray(value)||containsCredentialLikeKey(value))return null;return value as Row;}

integrationsRouter.get('/',async c=>{
  try{const supabase=getDb(c.env);const[connections,subscriptions,deliveries,inbound,references]=await Promise.all([
    supabase.from('atlas_integration_connections').select('*').is('archived_at',null).order('created_at'),
    supabase.from('atlas_integration_subscriptions').select('*').neq('status','archived').order('created_at'),
    supabase.from('atlas_outbox_deliveries').select('*,event:atlas_notification_events!event_id(id,category,resource_type,resource_id,event_action,summary,created_at),attempts:atlas_delivery_attempts(*)').order('created_at',{ascending:false}).limit(100),
    supabase.from('atlas_inbound_events').select('*').order('created_at',{ascending:false}).limit(100),
    supabase.from('atlas_external_references').select('*').neq('status','archived').order('created_at',{ascending:false}).limit(100),
  ]);for(const result of[connections,subscriptions,deliveries,inbound,references])if(result.error)throw result.error;
  return c.json({connections:(connections.data||[]).map(connection=>({...connection,subscriptions:(subscriptions.data||[]).filter(item=>item.connection_id===connection.id)})),deliveries:deliveries.data||[],inbound:inbound.data||[],external_references:references.data||[],delivery_enabled:c.env.ATLAS_DELIVERY_ENABLED==='true'});
  }catch(error){return integrationError(c,error,'Unable to load integrations.');}
});

integrationsRouter.post('/connections',async c=>{
  try{const body=await c.req.json<Row>();const supabase=getDb(c.env);const actor=getActor(c);const endpoint=validateIntegrationEndpoint(body.endpoint_url);if(!endpoint.valid)return apiError(c,400,'INTEGRATION_ENDPOINT_INVALID',endpoint.error||'Invalid endpoint.');if(!PROVIDERS.has(String(body.provider))||!DIRECTIONS.has(String(body.direction||'outbound')))return apiError(c,400,'INTEGRATION_TYPE_INVALID','Provider or direction is invalid.');const business=body.business||null;const businessError=await validateKnownBusinessId(supabase,business);if(businessError)return apiError(c,400,'BUSINESS_INVALID',businessError);const config=cleanConfig(body.config);if(config===null)return apiError(c,400,'INTEGRATION_CONFIG_INVALID','Configuration must be a bounded object without credential-like keys.');const secretRef=body.secret_ref||null;if(secretRef!==null&&!/^ATLAS_INTEGRATION_SECRET_[A-Z0-9_]{1,100}$/.test(secretRef))return apiError(c,400,'INTEGRATION_SECRET_REF_INVALID','secret_ref must name an ATLAS_INTEGRATION_SECRET_* binding.');const endpointHash=await sha256Hex(endpoint.normalized_url!);const{data,error}=await supabase.from('atlas_integration_connections').insert({id:uuidv4(),name:String(body.name||'').trim(),provider:body.provider,direction:body.direction||'outbound',business,endpoint_url:endpoint.normalized_url,endpoint_host:endpoint.host,endpoint_sha256:endpointHash,secret_ref:secretRef,secret_fingerprint:null,config,status:'draft',created_by:actor,updated_by:actor}).select().single();if(error)throw error;await supabase.from('atlas_integration_activity_log').insert({connection_id:data.id,entity_type:'connection',entity_id:data.id,event:'draft_created',new_value:{provider:data.provider,direction:data.direction,endpoint_host:data.endpoint_host},actor});return c.json(data,201);}catch(error){return integrationError(c,error,'Unable to create integration draft.');}
});

integrationsRouter.put('/connections/:id',async c=>{
  try{const body=await c.req.json<Row>();const supabase=getDb(c.env);const actor=getActor(c);const{data:existing,error:loadError}=await supabase.from('atlas_integration_connections').select('*').eq('id',c.req.param('id')).is('archived_at',null).single();if(loadError)throw loadError;if(!['draft','paused','pending_verification'].includes(existing.status))return apiError(c,409,'INTEGRATION_ACTIVE','Pause the connection before editing it.');if(revision(body.expected_revision)!==null&&existing.revision!==revision(body.expected_revision))return apiError(c,409,'REVISION_CONFLICT','The integration changed.');const endpoint:{valid:boolean;normalized_url?:string;host?:string;error?:string}=body.endpoint_url!==undefined?validateIntegrationEndpoint(body.endpoint_url):{valid:true,normalized_url:existing.endpoint_url,host:existing.endpoint_host};if(!endpoint.valid)return apiError(c,400,'INTEGRATION_ENDPOINT_INVALID',endpoint.error||'Invalid endpoint.');const config=body.config===undefined?existing.config:cleanConfig(body.config);if(config===null)return apiError(c,400,'INTEGRATION_CONFIG_INVALID','Configuration cannot contain credential-like keys.');const secretRef=body.secret_ref===undefined?existing.secret_ref:(body.secret_ref||null);if(secretRef!==null&&!/^ATLAS_INTEGRATION_SECRET_[A-Z0-9_]{1,100}$/.test(secretRef))return apiError(c,400,'INTEGRATION_SECRET_REF_INVALID','Invalid secret reference.');const endpointHash=await sha256Hex(endpoint.normalized_url!);const identityChanged=endpointHash!==existing.endpoint_sha256||secretRef!==existing.secret_ref;const updates={name:body.name===undefined?existing.name:String(body.name).trim(),provider:body.provider||existing.provider,direction:body.direction||existing.direction,business:body.business===undefined?existing.business:(body.business||null),endpoint_url:endpoint.normalized_url,endpoint_host:endpoint.host,endpoint_sha256:endpointHash,secret_ref:secretRef,config,status:identityChanged?'draft':existing.status,verified_at:identityChanged?null:existing.verified_at,verification_expires_at:identityChanged?null:existing.verification_expires_at,verified_endpoint_sha256:identityChanged?null:existing.verified_endpoint_sha256,verification_challenge_sha256:identityChanged?null:existing.verification_challenge_sha256,secret_fingerprint:identityChanged?null:existing.secret_fingerprint,revision:existing.revision+1,updated_by:actor,updated_at:new Date().toISOString()};const{data,error}=await supabase.from('atlas_integration_connections').update(updates).eq('id',existing.id).select().single();if(error)throw error;return c.json(data);}catch(error){return integrationError(c,error,'Unable to update integration draft.');}
});

integrationsRouter.post('/connections/:id/verify',async c=>{
  try{const body=await c.req.json<Row>().catch(()=>({} as Row));const supabase=getDb(c.env);const actor=getActor(c);const{data:connection,error:loadError}=await supabase.from('atlas_integration_connections').select('*').eq('id',c.req.param('id')).is('archived_at',null).single();if(loadError)throw loadError;if(revision(body.expected_revision)!==null&&connection.revision!==revision(body.expected_revision))return apiError(c,409,'REVISION_CONFLICT','The integration changed.');const endpoint=validateIntegrationEndpoint(connection.endpoint_url);if(!endpoint.valid)return apiError(c,400,'INTEGRATION_ENDPOINT_INVALID',endpoint.error||'Invalid endpoint.');const secret=integrationSecret(c.env,connection.secret_ref);if(!secret)return apiError(c,409,'INTEGRATION_SECRET_UNAVAILABLE','Configure the exact secret_ref Worker binding before verification.');const challenge=crypto.randomUUID();const payload=JSON.stringify({type:'atlas.integration.verify',challenge,connection_id:connection.id,endpoint_sha256:connection.endpoint_sha256});const timestamp=Date.now().toString();const deliveryId=`verify:${challenge}`;const eventType='verification';const signature=await hmacSha256Hex(secret,buildWebhookSigningInput(timestamp,deliveryId,eventType,payload));const response=await fetch(endpoint.normalized_url!,{method:'POST',redirect:'manual',signal:AbortSignal.timeout(5000),headers:{'Content-Type':'application/json; charset=utf-8','Atlas-Delivery':deliveryId,'Atlas-Event':eventType,'Atlas-Signature':signature,'Atlas-Signature-Version':'v1','Atlas-Timestamp':timestamp,'User-Agent':'Atlas-Webhook/1.0'},body:payload});if(response.status!==200)return apiError(c,409,'INTEGRATION_VERIFICATION_FAILED',`Endpoint returned HTTP ${response.status}.`);const responseText=await readBoundedText(response,4096);let echoed='';try{echoed=JSON.parse(responseText)?.challenge||'';}catch{}if(echoed!==challenge)return apiError(c,409,'INTEGRATION_VERIFICATION_FAILED','Endpoint did not echo the verification challenge.');const{data,error}=await supabase.rpc('record_atlas_connection_verification',{p_connection_id:connection.id,p_endpoint_sha256:connection.endpoint_sha256,p_challenge_sha256:await sha256Hex(challenge),p_secret_fingerprint:(await sha256Hex(secret)).slice(0,12),p_actor:actor,p_expected_revision:connection.revision});if(error)throw error;return c.json(data);}catch(error){return integrationError(c,error,'Unable to verify integration endpoint.');}
});

for(const action of['activate','pause','resume','archive'])integrationsRouter.post(`/connections/:id/${action}`,async c=>{try{const body=await c.req.json<Row>().catch(()=>({} as Row));const{data,error}=await getDb(c.env).rpc('transition_atlas_integration_connection',{p_connection_id:c.req.param('id'),p_action:action,p_actor:getActor(c),p_expected_revision:revision(body.expected_revision)});if(error)throw error;return c.json(data);}catch(error){return integrationError(c,error,`Unable to ${action} integration.`);}});

integrationsRouter.post('/connections/:id/subscriptions',async c=>{
  try{const body=await c.req.json<Row>();const supabase=getDb(c.env);const actor=getActor(c);const{data:connection,error:connectionError}=await supabase.from('atlas_integration_connections').select('id,status').eq('id',c.req.param('id')).single();if(connectionError)throw connectionError;const categories=body.categories||['all'];const resources=body.resource_types||['all'];const actions=body.event_actions||['all'];if(!validArray(categories,CATEGORIES)||!validArray(resources,RESOURCES)||!Array.isArray(actions)||actions.some((item:unknown)=>typeof item!=='string'||!/^(all|[a-z][a-z0-9_]{0,63})$/.test(item)))return apiError(c,400,'INTEGRATION_SUBSCRIPTION_INVALID','Subscription filters are invalid.');const status=connection.status==='active'&&body.activate===true?'active':'paused';const{data,error}=await supabase.from('atlas_integration_subscriptions').insert({id:uuidv4(),connection_id:connection.id,name:String(body.name||'').trim(),categories,resource_types:resources,event_actions:actions,business:body.business||null,project_id:body.project_id||null,initiative_id:body.initiative_id||null,saved_view_id:body.saved_view_id||null,delivery_mode:body.delivery_mode||'immediate',status,created_by:actor,updated_by:actor}).select().single();if(error)throw error;await supabase.from('atlas_integration_activity_log').insert({connection_id:connection.id,entity_type:'subscription',entity_id:data.id,event:'created',new_value:data,actor});return c.json(data,201);}catch(error){return integrationError(c,error,'Unable to create integration subscription.');}
});

integrationsRouter.post('/subscriptions/:id/:transition',async c=>{
  try{const transition=c.req.param('transition');if(!['activate','pause','archive'].includes(transition))return apiError(c,400,'INTEGRATION_SUBSCRIPTION_INVALID','Transition must be activate, pause, or archive.');const body=await c.req.json<Row>().catch(()=>({} as Row));const supabase=getDb(c.env);const actor=getActor(c);const{data:existing,error:loadError}=await supabase.from('atlas_integration_subscriptions').select('*,connection:atlas_integration_connections!connection_id(status)').eq('id',c.req.param('id')).single();if(loadError)throw loadError;if(revision(body.expected_revision)!==null&&existing.revision!==revision(body.expected_revision))return apiError(c,409,'REVISION_CONFLICT','The subscription changed.');if(transition==='activate'&&existing.connection?.status!=='active')return apiError(c,409,'INTEGRATION_CONNECTION_INACTIVE','Verify and activate the connection first.');const status=transition==='activate'?'active':transition==='pause'?'paused':'archived';const{data,error}=await supabase.from('atlas_integration_subscriptions').update({status,revision:existing.revision+1,updated_by:actor,updated_at:new Date().toISOString()}).eq('id',existing.id).select().single();if(error)throw error;return c.json(data);}catch(error){return integrationError(c,error,'Unable to update integration subscription.');}
});

integrationsRouter.post('/deliveries/process',async c=>{try{const body=await c.req.json<Row>().catch(()=>({} as Row));return c.json(await dispatchPendingDeliveries(c.env,getActor(c),Math.min(Number(body.limit||10),25)));}catch(error){return integrationError(c,error,'Unable to process pending deliveries.');}});

integrationsRouter.post('/inbound/:id/:transition',async c=>{try{const transition=c.req.param('transition');if(!['reviewed','ignored','rejected'].includes(transition))return apiError(c,400,'INBOUND_TRANSITION_INVALID','Transition is invalid.');const body=await c.req.json<Row>().catch(()=>({} as Row));const{data,error}=await getDb(c.env).rpc('transition_atlas_inbound_event',{p_event_id:c.req.param('id'),p_status:transition,p_actor:getActor(c),p_expected_revision:revision(body.expected_revision)});if(error)throw error;return c.json(data);}catch(error){return integrationError(c,error,'Unable to review inbound event.');}});

integrationsRouter.post('/connections/:id/references',async c=>{try{const body=await c.req.json<Row>();if(!['action','project','initiative','document','comment','release'].includes(body.resource_type)||typeof body.resource_id!=='string'||!body.resource_id||typeof body.provider_ref!=='string'||!body.provider_ref)return apiError(c,400,'EXTERNAL_REFERENCE_INVALID','Provider and Atlas resource references are required.');const actor=getActor(c);const{data,error}=await getDb(c.env).from('atlas_external_references').insert({id:uuidv4(),connection_id:c.req.param('id'),provider_ref:body.provider_ref,resource_type:body.resource_type,resource_id:body.resource_id,sync_mode:body.sync_mode||'link',external_url:body.external_url||null,metadata:cleanConfig(body.metadata)||{},status:'active',created_by:actor,updated_by:actor}).select().single();if(error)throw error;return c.json(data,201);}catch(error){return integrationError(c,error,'Unable to create external reference.');}});

hooksRouter.post('/:connectionId',async c=>{
  try{
    const length=Number(c.req.header('content-length')||0);if(length>65536)return apiError(c,413,'INBOUND_TOO_LARGE','Inbound payload exceeds 64 KiB.');const raw=await c.req.text();if(new TextEncoder().encode(raw).byteLength>65536)return apiError(c,413,'INBOUND_TOO_LARGE','Inbound payload exceeds 64 KiB.');if(!(c.req.header('content-type')||'').toLowerCase().startsWith('application/json'))return apiError(c,415,'INBOUND_CONTENT_TYPE','Inbound payload must be JSON.');
    const deliveryId=c.req.header('atlas-delivery')||'';const eventType=c.req.header('atlas-event')||'';const timestamp=c.req.header('atlas-timestamp')||'';const signature=(c.req.header('atlas-signature')||'').toLowerCase();const signatureVersion=c.req.header('atlas-signature-version')||'';if(signatureVersion!=='v1'||!validWebhookHeaders(deliveryId,eventType,timestamp)||!isFreshWebhookTimestamp(timestamp))return apiError(c,400,'INBOUND_HEADERS_INVALID','Versioned, fresh delivery, event, and timestamp headers are required.');const supabase=getDb(c.env);const{data:connection,error:loadError}=await supabase.from('atlas_integration_connections').select('*').eq('id',c.req.param('connectionId')).eq('status','active').in('direction',['inbound','bidirectional']).maybeSingle();if(loadError||!connection)return apiError(c,404,'INBOUND_CONNECTION_NOT_FOUND','Active inbound connection not found.');const endpoint=validateIntegrationEndpoint(connection.endpoint_url);if(!endpoint.valid||endpoint.normalized_url!==connection.endpoint_url)return apiError(c,409,'INBOUND_CONNECTION_INVALID','Connection identity is no longer valid.');const secret=integrationSecret(c.env,connection.secret_ref);if(!secret)return apiError(c,503,'INBOUND_SECRET_UNAVAILABLE','Inbound signing secret is unavailable.');const expected=await hmacSha256Hex(secret,buildWebhookSigningInput(timestamp,deliveryId,eventType,raw));if(!timingSafeHexEqual(signature,expected))return apiError(c,401,'INBOUND_SIGNATURE_INVALID','Inbound signature is invalid.');let payload:unknown;try{payload=JSON.parse(raw);}catch{return apiError(c,400,'INBOUND_JSON_INVALID','Inbound JSON is invalid.');}if(!payload||typeof payload!=='object'||Array.isArray(payload))return apiError(c,400,'INBOUND_JSON_INVALID','Inbound payload must be an object.');const providerTimestamp=new Date(Number(timestamp));const{data,error}=await supabase.rpc('record_atlas_inbound_event',{p_connection_id:connection.id,p_delivery_id:deliveryId,p_event_type:eventType,p_provider_timestamp:providerTimestamp.toISOString(),p_content_sha256:await sha256Hex(raw),p_payload:payload,p_actor:'integration_hook'});if(error)throw error;return c.json({accepted:true,replay:Boolean(data?.replay)},200);
  }catch(error){console.error(`[hooks] inbound error: ${(error as Error).message}`);return apiError(c,500,'INBOUND_FAILED','Unable to accept inbound event.');}
});

export {integrationsRouter,hooksRouter};
