import { Hono } from 'hono';
import { v4 as uuidv4 } from 'uuid';
import { Env, getDb } from '../db';
import { getActor, getAuthKind } from '../utils/actors';
import { apiError } from '../utils/http';
import { sanitizeBody, validateStringLengths } from '../middleware/validate';
import { serializeJsonArray, serializeJsonObject } from '../utils/json';
import { sha256Hex } from '../middleware/auth';
import { validateKnownBusinessId } from '../utils/referenceData';

const router=new Hono<{Bindings:Env}>();
type Row=Record<string,any>;
const PIPELINE_COLUMNS='id,name,description,pipeline_type,business,path_filters,notes_template,auto_generate_notes,complete_actions_on_release,access_key_fingerprint,access_key_rotated_at,status,revision,archived_at,created_by,updated_by,created_at,updated_at';
const PIPELINE_TYPES=new Set(['continuous','scheduled']);
const RELEASE_STATUSES=new Set(['planned','in_progress','completed','canceled','failed','archived']);
const STAGE_RUN_STATUSES=new Set(['started','completed','canceled','failed']);
const EVENT_TYPES=new Set(['release_created','stage_started','stage_completed','stage_failed','release_completed','release_failed']);

export function validatePipelineBody(body:Row,partial=false):string[]{const errors:string[]=[];if(!partial&&(typeof body.name!=='string'||!body.name.trim()))errors.push('name is required');if(body.name!==undefined&&(typeof body.name!=='string'||!body.name.trim()))errors.push('name must be non-empty');if(body.pipeline_type!==undefined&&!PIPELINE_TYPES.has(String(body.pipeline_type)))errors.push('pipeline_type is invalid');if(body.path_filters!==undefined&&(!Array.isArray(body.path_filters)||!body.path_filters.every((item:unknown)=>typeof item==='string'&&item.trim()&&!item.includes('..'))))errors.push('path_filters must be safe glob strings');if(body.notes_template!==undefined&&(typeof body.notes_template!=='string'||body.notes_template.length>20000))errors.push('notes_template must be text up to 20000 characters');return errors}
export function validateStageBody(body:Row):string[]{const errors:string[]=[];if(typeof body.stage_key!=='string'||!/^[a-z0-9_-]{1,50}$/i.test(body.stage_key))errors.push('stage_key is invalid');if(typeof body.name!=='string'||!body.name.trim())errors.push('name is required');if(typeof body.environment!=='string'||!body.environment.trim())errors.push('environment is required');if(!Number.isSafeInteger(body.position)||body.position<0)errors.push('position must be a non-negative integer');return errors}
export function validateReleaseEvent(body:Row):string[]{const errors:string[]=[];if(typeof body.event_key!=='string'||!body.event_key.trim()||body.event_key.length>200)errors.push('event_key is required');if(!EVENT_TYPES.has(String(body.event_type)))errors.push('event_type is invalid');if(typeof body.external_release_id!=='string'||!body.external_release_id.trim())errors.push('external_release_id is required');if(String(body.event_type).startsWith('stage_')&&(!body.stage_key||typeof body.stage_key!=='string'))errors.push('stage_key is required for stage events');if(body.action_ids!==undefined&&(!Array.isArray(body.action_ids)||!body.action_ids.every((id:unknown)=>typeof id==='string'&&id)))errors.push('action_ids must be an array of ids');if(body.changed_paths!==undefined&&(!Array.isArray(body.changed_paths)||!body.changed_paths.every((path:unknown)=>typeof path==='string'&&!path.includes('..'))))errors.push('changed_paths must be safe path strings');return errors}

function globRegex(glob:string){const escaped=glob.replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*\*/g,'§§').replace(/\*/g,'[^/]*').replace(/§§/g,'.*');return new RegExp(`^${escaped}$`)}
export function matchesPathFilters(paths:string[],filters:string[]){if(!filters.length||!paths.length)return true;return paths.some(path=>filters.some(filter=>{try{return globRegex(filter).test(path)}catch{return false}}))}

function rpcError(c:any,error:{code?:string;message?:string;details?:string},fallback:string){const message=error.message||'';if(error.code==='40001'||message.includes('REVISION_CONFLICT'))return apiError(c,409,'REVISION_CONFLICT','The release state changed. Refresh and retry.');if(error.code==='42501'||message.includes('OWNER_REQUIRED'))return apiError(c,403,'OWNER_REQUIRED','This release operation requires the Atlas owner.');if(error.code==='P0002'||message.includes('NOT_FOUND'))return apiError(c,404,'RELEASE_REFERENCE_NOT_FOUND','The pipeline, release, stage, or action was not found.');if(error.code==='55000'||message.includes('TERMINAL')||message.includes('FROZEN'))return apiError(c,409,'RELEASE_STATE_CONFLICT',message||fallback);if(['22023','23503','23505','23514'].includes(String(error.code)))return apiError(c,400,'INVALID_RELEASE_OPERATION',error.details?`${message}: ${error.details}`:message||fallback);console.error(`[releases] RPC error: ${message||error.code||'unknown'}`);return apiError(c,500,'RELEASE_OPERATION_FAILED',fallback)}
async function callRpc(c:any,name:string,args:Row,fallback:string){try{const{data,error}=await getDb(c.env).rpc(name,args);if(error)return rpcError(c,error,fallback);return c.json(data)}catch(error){console.error(`[releases] ${name} error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_OPERATION_FAILED',fallback)}}

async function loadPipelineAggregate(supabase:ReturnType<typeof getDb>,pipeline:Row){
  const [stages,releases]=await Promise.all([supabase.from('atlas_release_stages').select('*').eq('pipeline_id',pipeline.id).order('position'),supabase.from('atlas_releases').select('*').eq('pipeline_id',pipeline.id).order('created_at',{ascending:false})]);
  if(stages.error)throw stages.error;if(releases.error)throw releases.error;const releaseIds=(releases.data||[]).map(item=>item.id);let runs:Row[]=[];let associations:Row[]=[];let actions:Row[]=[];
  if(releaseIds.length){const[runResult,associationResult]=await Promise.all([supabase.from('atlas_release_stage_runs').select('*').in('release_id',releaseIds),supabase.from('atlas_release_actions').select('*').in('release_id',releaseIds).eq('status','active')]);if(runResult.error)throw runResult.error;if(associationResult.error)throw associationResult.error;runs=runResult.data||[];associations=associationResult.data||[];const actionIds=Array.from(new Set(associations.map(item=>item.action_id)));if(actionIds.length){const actionResult=await supabase.from('atlas_actions').select('id,title,status,priority,business,completed_at').in('id',actionIds);if(actionResult.error)throw actionResult.error;actions=actionResult.data||[];}}
  return{...pipeline,stages:stages.data||[],releases:(releases.data||[]).map(release=>({...release,stage_runs:runs.filter(run=>run.release_id===release.id).map(run=>({...run,stage:(stages.data||[]).find(stage=>stage.id===run.stage_id)||null})),actions:associations.filter(item=>item.release_id===release.id).map(item=>({...item,action:actions.find(action=>action.id===item.action_id)||null}))}))};
}

router.get('/pipelines',async c=>{try{const{status,business}=c.req.query();let query=getDb(c.env).from('atlas_release_pipelines').select(PIPELINE_COLUMNS);if(status)query=query.eq('status',status);else query=query.eq('status','active');if(business)query=query.eq('business',business);const{data,error}=await query.order('name');if(error)throw error;const supabase=getDb(c.env);const items=await Promise.all((data||[]).map(async pipeline=>{const [releaseCount,stageCount]=await Promise.all([supabase.from('atlas_releases').select('id',{count:'exact',head:true}).eq('pipeline_id',pipeline.id),supabase.from('atlas_release_stages').select('id',{count:'exact',head:true}).eq('pipeline_id',pipeline.id).eq('status','active')]);return{...pipeline,release_count:releaseCount.count||0,stage_count:stageCount.count||0}}));return c.json(items)}catch(error){console.error(`[releases] pipelines error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_PIPELINE_LIST_FAILED','Unable to load release pipelines.')}});

router.post('/pipelines',async c=>{try{const raw=await c.req.json<Row>().catch(()=>({}as Row));const body=sanitizeBody(raw,['name','description','business','notes_template']);const businessError=await validateKnownBusinessId(getDb(c.env),body.business);const errors=[...validatePipelineBody(body),...validateStringLengths(body),...(businessError?[businessError]:[])];if(errors.length)return apiError(c,400,'INVALID_RELEASE_PIPELINE',errors.join('; '));const actor=getActor(c);const{data,error}=await getDb(c.env).from('atlas_release_pipelines').insert({id:uuidv4(),name:String(body.name).trim(),description:body.description||'',pipeline_type:body.pipeline_type||'continuous',business:body.business||null,path_filters:serializeJsonArray(body.path_filters||[]),notes_template:body.notes_template||'# {{release_name}}\n\n{{issues}}',auto_generate_notes:body.auto_generate_notes===true,complete_actions_on_release:body.complete_actions_on_release===true,created_by:actor,updated_by:actor}).select(PIPELINE_COLUMNS).single();if(error)throw error;return c.json(data,201)}catch(error){console.error(`[releases] pipeline create error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_PIPELINE_CREATE_FAILED','Unable to create the release pipeline.')}});

router.get('/pipelines/:id',async c=>{try{const supabase=getDb(c.env);const{data,error}=await supabase.from('atlas_release_pipelines').select(PIPELINE_COLUMNS).eq('id',c.req.param('id')).maybeSingle();if(error)throw error;if(!data)return apiError(c,404,'RELEASE_PIPELINE_NOT_FOUND','Release pipeline not found.');return c.json(await loadPipelineAggregate(supabase,data))}catch(error){console.error(`[releases] pipeline detail error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_PIPELINE_LOAD_FAILED','Unable to load the release pipeline.')}});

router.put('/pipelines/:id',async c=>{try{const raw=await c.req.json<Row>().catch(()=>({}as Row));if(!Number.isSafeInteger(raw.expected_revision))return apiError(c,400,'INVALID_REVISION','expected_revision is required.');const supabase=getDb(c.env);const{data:existing,error:fetchError}=await supabase.from('atlas_release_pipelines').select('*').eq('id',c.req.param('id')).maybeSingle();if(fetchError)throw fetchError;if(!existing)return apiError(c,404,'RELEASE_PIPELINE_NOT_FOUND','Release pipeline not found.');const candidate={...existing,...raw};const errors=validatePipelineBody(candidate,true);if(errors.length)return apiError(c,400,'INVALID_RELEASE_PIPELINE',errors.join('; '));const updates:Row={};for(const field of ['name','description','pipeline_type','business','notes_template','auto_generate_notes','complete_actions_on_release'])if(raw[field]!==undefined)updates[field]=raw[field]===''?null:raw[field];if(raw.path_filters!==undefined)updates.path_filters=serializeJsonArray(raw.path_filters);updates.revision=existing.revision+1;updates.updated_by=getActor(c);updates.updated_at=new Date().toISOString();const{data,error}=await supabase.from('atlas_release_pipelines').update(updates).eq('id',existing.id).eq('revision',raw.expected_revision).select(PIPELINE_COLUMNS).maybeSingle();if(error)throw error;if(!data)return apiError(c,409,'REVISION_CONFLICT','The pipeline changed. Refresh and retry.');return c.json(data)}catch(error){console.error(`[releases] pipeline update error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_PIPELINE_UPDATE_FAILED','Unable to update the release pipeline.')}});

async function pipelineStatus(c:any,status:string){const body=await c.req.json().catch(()=>({}))as Row;const supabase=getDb(c.env);const{data:existing,error:fetchError}=await supabase.from('atlas_release_pipelines').select('*').eq('id',c.req.param('id')).maybeSingle();if(fetchError)throw fetchError;if(!existing)return apiError(c,404,'RELEASE_PIPELINE_NOT_FOUND','Release pipeline not found.');if(existing.revision!==body.expected_revision)return apiError(c,409,'REVISION_CONFLICT','The pipeline changed.');const{data,error}=await supabase.from('atlas_release_pipelines').update({status,archived_at:status==='archived'?new Date().toISOString():null,revision:existing.revision+1,updated_by:getActor(c),updated_at:new Date().toISOString()}).eq('id',existing.id).eq('revision',existing.revision).select(PIPELINE_COLUMNS).maybeSingle();if(error)throw error;return c.json(data)}
router.post('/pipelines/:id/archive',c=>pipelineStatus(c,'archived'));router.post('/pipelines/:id/restore',c=>pipelineStatus(c,'active'));

router.post('/pipelines/:id/access-key',async c=>{const body=await c.req.json<Row>().catch(()=>({}as Row));if(typeof body.access_key!=='string'||body.access_key.length<24)return apiError(c,400,'INVALID_RELEASE_ACCESS_KEY','Provide an access key of at least 24 characters.');const digest=await sha256Hex(body.access_key);const fingerprint=digest.slice(0,12);return callRpc(c,'rotate_atlas_release_access_key',{p_pipeline_id:c.req.param('id'),p_access_key_hash:digest,p_fingerprint:fingerprint,p_actor:getActor(c),p_expected_revision:body.expected_revision},'Unable to configure the pipeline access key.');});

router.post('/pipelines/:id/stages',async c=>{try{const body=await c.req.json<Row>().catch(()=>({}as Row));const errors=validateStageBody(body);if(errors.length)return apiError(c,400,'INVALID_RELEASE_STAGE',errors.join('; '));const actor=getActor(c);const{data,error}=await getDb(c.env).from('atlas_release_stages').insert({id:uuidv4(),pipeline_id:c.req.param('id'),stage_key:body.stage_key,name:body.name.trim(),environment:body.environment.trim(),position:body.position,freeze_on_start:body.freeze_on_start===true,created_by:actor,updated_by:actor}).select().single();if(error)throw error;return c.json(data,201)}catch(error){console.error(`[releases] stage create error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_STAGE_CREATE_FAILED','Unable to create the release stage.')}});
router.put('/pipelines/:id/stages/:stageId',async c=>{try{const body=await c.req.json<Row>().catch(()=>({}as Row));if(!Number.isSafeInteger(body.expected_revision))return apiError(c,400,'INVALID_REVISION','expected_revision is required.');const supabase=getDb(c.env);const{data:existing,error:fetchError}=await supabase.from('atlas_release_stages').select('*').eq('id',c.req.param('stageId')).eq('pipeline_id',c.req.param('id')).maybeSingle();if(fetchError)throw fetchError;if(!existing)return apiError(c,404,'RELEASE_STAGE_NOT_FOUND','Release stage not found.');const updates:Row={};for(const field of ['stage_key','name','environment','position','freeze_on_start','status'])if(body[field]!==undefined)updates[field]=body[field];updates.revision=existing.revision+1;updates.updated_by=getActor(c);updates.updated_at=new Date().toISOString();const{data,error}=await supabase.from('atlas_release_stages').update(updates).eq('id',existing.id).eq('revision',body.expected_revision).select().maybeSingle();if(error)throw error;if(!data)return apiError(c,409,'REVISION_CONFLICT','The stage changed.');return c.json(data)}catch(error){console.error(`[releases] stage update error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_STAGE_UPDATE_FAILED','Unable to update the release stage.')}});

router.post('/pipelines/:id/releases',async c=>{const body=await c.req.json<Row>().catch(()=>({}as Row));return callRpc(c,'create_atlas_release',{p_pipeline_id:c.req.param('id'),p_release_id:uuidv4(),p_external_id:body.external_id||null,p_name:body.name,p_version:body.version||null,p_commit_sha:body.commit_sha||null,p_scheduled_at:body.scheduled_at||null,p_actor:getActor(c)},'Unable to create the release.');});

router.get('/items/:id',async c=>{try{const supabase=getDb(c.env);const{data:release,error}=await supabase.from('atlas_releases').select('*').eq('id',c.req.param('id')).maybeSingle();if(error)throw error;if(!release)return apiError(c,404,'RELEASE_NOT_FOUND','Release not found.');const pipelineResult=await supabase.from('atlas_release_pipelines').select(PIPELINE_COLUMNS).eq('id',release.pipeline_id).single();if(pipelineResult.error)throw pipelineResult.error;const aggregate=await loadPipelineAggregate(supabase,pipelineResult.data);return c.json(aggregate.releases.find((item:Row)=>item.id===release.id))}catch(error){console.error(`[releases] item load error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_LOAD_FAILED','Unable to load the release.')}});
router.put('/items/:id',async c=>{try{const body=await c.req.json<Row>().catch(()=>({}as Row));if(!Number.isSafeInteger(body.expected_revision))return apiError(c,400,'INVALID_REVISION','expected_revision is required.');const supabase=getDb(c.env);const{data:existing,error:fetchError}=await supabase.from('atlas_releases').select('*').eq('id',c.req.param('id')).maybeSingle();if(fetchError)throw fetchError;if(!existing)return apiError(c,404,'RELEASE_NOT_FOUND','Release not found.');if(['completed','canceled','failed','archived'].includes(existing.status))return apiError(c,409,'RELEASE_STATE_CONFLICT','Terminal releases cannot be edited.');const updates:Row={};for(const field of ['name','version','commit_sha','scheduled_at','notes'])if(body[field]!==undefined)updates[field]=body[field]??null;if(body.notes!==undefined)updates.notes_source='manual';updates.revision=existing.revision+1;updates.updated_by=getActor(c);updates.updated_at=new Date().toISOString();const{data,error}=await supabase.from('atlas_releases').update(updates).eq('id',existing.id).eq('revision',body.expected_revision).select().maybeSingle();if(error)throw error;if(!data)return apiError(c,409,'REVISION_CONFLICT','The release changed.');return c.json(data)}catch(error){console.error(`[releases] item update error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_UPDATE_FAILED','Unable to update the release.')}});
router.post('/items/:id/actions/:actionId/attach',async c=>{const body=await c.req.json<Row>().catch(()=>({}as Row));return callRpc(c,'set_atlas_release_action',{p_release_id:c.req.param('id'),p_action_id:c.req.param('actionId'),p_stage_run_id:body.stage_run_id||null,p_active:true,p_source:'manual',p_actor:getActor(c)},'Unable to attach the action.');});
router.post('/items/:id/actions/:actionId/detach',c=>callRpc(c,'set_atlas_release_action',{p_release_id:c.req.param('id'),p_action_id:c.req.param('actionId'),p_stage_run_id:null,p_active:false,p_source:'manual',p_actor:getActor(c)},'Unable to detach the action.'));
router.post('/stage-runs/:id/transition',async c=>{const body=await c.req.json<Row>().catch(()=>({}as Row));if(!STAGE_RUN_STATUSES.has(String(body.status)))return apiError(c,400,'INVALID_RELEASE_STAGE_STATUS','status is invalid.');return callRpc(c,'transition_atlas_release_stage',{p_stage_run_id:c.req.param('id'),p_status:body.status,p_commit_sha:body.commit_sha||null,p_external_url:body.external_url||null,p_actor:getActor(c),p_expected_revision:body.expected_revision},'Unable to transition the stage.');});
router.post('/items/:id/transition',async c=>{const body=await c.req.json<Row>().catch(()=>({}as Row));if(!RELEASE_STATUSES.has(String(body.status))||body.status==='planned')return apiError(c,400,'INVALID_RELEASE_STATUS','status is invalid.');if(body.status==='archived'&&getAuthKind(c)!=='owner_access')return apiError(c,403,'OWNER_REQUIRED','Only the ATLAS owner can archive a release.');return callRpc(c,'transition_atlas_release',{p_release_id:c.req.param('id'),p_status:body.status,p_notes:body.notes??null,p_actor:getActor(c),p_expected_revision:body.expected_revision},'Unable to transition the release.');});
router.post('/items/:id/notes/generate',c=>callRpc(c,'generate_atlas_release_notes',{p_release_id:c.req.param('id'),p_actor:getActor(c)},'Unable to generate release notes.'));
router.post('/items/:id/restore',async c=>{const body=await c.req.json<Row>().catch(()=>({}as Row));return callRpc(c,'restore_atlas_release',{p_release_id:c.req.param('id'),p_actor:getActor(c),p_expected_revision:body.expected_revision},'Unable to restore the release.');});

router.get('/pipelines/:id/changelog',async c=>{try{const supabase=getDb(c.env);const{data,error}=await supabase.from('atlas_releases').select('*').eq('pipeline_id',c.req.param('id')).eq('status','completed').order('released_at',{ascending:false});if(error)throw error;return c.json(data||[])}catch(error){console.error(`[releases] changelog error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_CHANGELOG_FAILED','Unable to load the changelog.')}});

router.post('/ingest/:pipelineId',async c=>{try{const pipelineId=c.req.param('pipelineId');const bound=(c as any).get('atlasReleasePipelineId');if(getAuthKind(c)==='release_access'&&bound!==pipelineId)return apiError(c,403,'RELEASE_PIPELINE_BOUNDARY','This key belongs to another pipeline.');const body=await c.req.json<Row>().catch(()=>({}as Row));const errors=validateReleaseEvent(body);if(errors.length)return apiError(c,400,'INVALID_RELEASE_EVENT',errors.join('; '));const supabase=getDb(c.env);const{data:pipeline,error:pipelineError}=await supabase.from('atlas_release_pipelines').select('id,path_filters,status').eq('id',pipelineId).maybeSingle();if(pipelineError)throw pipelineError;if(!pipeline||pipeline.status!=='active')return apiError(c,404,'RELEASE_PIPELINE_NOT_FOUND','Active release pipeline not found.');if(!matchesPathFilters(body.changed_paths||[],pipeline.path_filters||[])){const result={pipeline_id:pipelineId,ignored:true,reason:'path_filters',changed_paths:body.changed_paths||[],replay:false};const event={id:uuidv4(),pipeline_id:pipelineId,event_key:body.event_key,event_type:'ignored',release_id:null,external_release_id:body.external_release_id,commit_sha:body.commit_sha||null,occurred_at:body.occurred_at||new Date().toISOString(),payload:serializeJsonObject(body),processing_result:result,actor:getActor(c)};const{data,error}=await supabase.from('atlas_release_events').insert(event).select().single();if(error?.code==='23505'){const existing=await supabase.from('atlas_release_events').select('id,processing_result').eq('pipeline_id',pipelineId).eq('event_key',body.event_key).single();if(existing.error)throw existing.error;return c.json({...existing.data.processing_result,replay:true,event_id:existing.data.id});}if(error)throw error;return c.json({...result,event_id:data.id},202);}const{data,error}=await supabase.rpc('ingest_atlas_release_event',{p_pipeline_id:pipelineId,p_event_key:body.event_key,p_event_type:body.event_type,p_external_release_id:body.external_release_id,p_release_name:body.release_name||body.external_release_id,p_version:body.version||null,p_commit_sha:body.commit_sha||null,p_stage_key:body.stage_key||null,p_action_ids:serializeJsonArray(body.action_ids||[]),p_occurred_at:body.occurred_at||new Date().toISOString(),p_payload:serializeJsonObject(body.payload||{}),p_actor:getActor(c)});if(error)return rpcError(c,error,'Unable to ingest the release event.');return c.json(data,202)}catch(error){console.error(`[releases] ingest error: ${(error as Error).message}`);return apiError(c,500,'RELEASE_INGEST_FAILED','Unable to ingest the release event.')}});

export default router;
