// @vitest-environment jsdom
import { act,renderHook } from '@testing-library/react';import{afterEach,beforeEach,describe,expect,it,vi}from'vitest';import{useDocumentRealtime}from'./useDocumentRealtime.js';
class FakeWebSocket{static instances=[];constructor(url){this.url=url;this.readyState=0;this.sent=[];FakeWebSocket.instances.push(this)}send(value){this.sent.push(value)}close(){this.readyState=3;this.onclose?.({code:1000,reason:'closed'})}open(){this.readyState=1;this.onopen?.()}message(value){this.onmessage?.({data:JSON.stringify(value)})}disconnect(){this.readyState=3;this.onclose?.({code:1006,reason:'network'})}}
const document={id:'d1',title:'Plan',content:'# Plan\nBase',revision:1,status:'active',updated_by:'ransomed'};
describe('useDocumentRealtime',()=>{beforeEach(()=>{localStorage.clear();FakeWebSocket.instances=[];globalThis.WebSocket=FakeWebSocket;vi.useFakeTimers();vi.spyOn(globalThis.crypto.subtle,'digest').mockResolvedValue(new Uint8Array(32).buffer)});afterEach(()=>{vi.runOnlyPendingTimers();vi.restoreAllMocks();vi.useRealTimers()});
  it('connects, receives canonical snapshot, and sends debounced hashed edits',async()=>{const{result,unmount}=renderHook(()=>useDocumentRealtime('d1',document));const socket=FakeWebSocket.instances[0];act(()=>{socket.open();socket.message({type:'snapshot',document,operations:[],conflicts:[],presence:[{actor:'ransomed',client_id:'browser:one'}]})});expect(result.current.syncState).toBe('connected');expect(result.current.presence).toHaveLength(1);act(()=>result.current.updateDraft({title:'Plan',content:'# Plan\nChanged'},{start:14,end:14}));await act(async()=>{await vi.advanceTimersByTimeAsync(700);for(let index=0;index<20;index+=1)await Promise.resolve()});expect(socket.sent.some(value=>JSON.parse(value).type==='edit')).toBe(true);const edit=JSON.parse(socket.sent.find(value=>JSON.parse(value).type==='edit'));expect(edit.base_revision).toBe(1);expect(edit.base_content_sha256).toHaveLength(64);act(()=>socket.message({type:'edit.applied',operation_id:edit.operation_id,document:{...document,content:'# Plan\nChanged',revision:2},operation:{id:'o1',applied_revision:2},presence:[]}));expect(result.current.document.revision).toBe(2);expect(result.current.syncState).toBe('synced');unmount()});
  it('preserves the local draft and exposes explicit conflict choices',()=>{const{result,unmount}=renderHook(()=>useDocumentRealtime('d1',document));const socket=FakeWebSocket.instances[0];act(()=>{socket.open();socket.message({type:'snapshot',document,operations:[],conflicts:[],presence:[]});result.current.updateDraft({title:'Plan',content:'Local draft'},null);socket.message({type:'edit.conflict',reason:'overlapping_change',operation_id:'op1',document:{...document,content:'Canonical',revision:2}})});expect(result.current.syncState).toBe('conflict');expect(result.current.draft.content).toBe('Local draft');expect(result.current.conflict.document.content).toBe('Canonical');act(()=>result.current.useLatest());expect(result.current.draft.content).toBe('Canonical');expect(result.current.conflict).toBeNull();unmount()});
  it('reconnects with exponential backoff after an unclean close',async()=>{const{result,unmount}=renderHook(()=>useDocumentRealtime('d1',document));const first=FakeWebSocket.instances[0];act(()=>first.disconnect());expect(result.current.syncState).toBe('offline');await act(async()=>{await vi.advanceTimersByTimeAsync(1000)});expect(FakeWebSocket.instances).toHaveLength(2);expect(result.current.syncState).toBe('reconnecting');unmount()});
});
