-- Linear parity slice 6: action/project/document templates, structured forms,
-- transactional instantiation, provenance, defaults, and versioned documents.

create table if not exists public.atlas_templates (
  id text primary key,
  name text not null,
  description text not null default '',
  template_type text not null check (template_type in ('action', 'project', 'document')),
  mode text not null default 'standard' check (mode in ('standard', 'form')),
  scope text not null default 'workspace' check (scope in ('workspace', 'business')),
  business text,
  default_audience text not null default 'owner' check (default_audience in ('owner', 'intake', 'all')),
  is_default boolean not null default false,
  blueprint jsonb not null default '{}'::jsonb check (jsonb_typeof(blueprint) = 'object'),
  form_schema jsonb not null default '[]'::jsonb check (jsonb_typeof(form_schema) = 'array'),
  status text not null default 'active' check (status in ('active', 'archived')),
  revision bigint not null default 0 check (revision >= 0),
  usage_count bigint not null default 0 check (usage_count >= 0),
  last_used_at timestamptz,
  archived_at timestamptz,
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check ((scope = 'workspace' and business is null) or (scope = 'business' and nullif(btrim(business), '') is not null)),
  check (mode <> 'form' or template_type = 'action')
);

create unique index if not exists atlas_templates_one_default_idx
  on public.atlas_templates (template_type, coalesce(business, '__workspace__'), default_audience)
  where is_default and status = 'active';
create index if not exists atlas_templates_active_type_idx
  on public.atlas_templates (template_type, scope, business, name) where status = 'active';

create table if not exists public.atlas_template_instances (
  id text primary key,
  template_id text not null references public.atlas_templates(id) on delete restrict,
  template_revision bigint not null,
  result_entity_type text not null check (result_entity_type in ('action', 'project', 'document')),
  result_entity_id text not null,
  form_values jsonb not null default '{}'::jsonb check (jsonb_typeof(form_values) = 'object'),
  overrides jsonb not null default '{}'::jsonb check (jsonb_typeof(overrides) = 'object'),
  actor text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists atlas_template_instances_template_created_idx
  on public.atlas_template_instances (template_id, created_at desc);
create unique index if not exists atlas_template_instances_result_idx
  on public.atlas_template_instances (result_entity_type, result_entity_id);

create table if not exists public.atlas_template_activity_log (
  id bigint generated by default as identity primary key,
  template_id text not null references public.atlas_templates(id) on delete restrict,
  event text not null,
  old_value jsonb,
  new_value jsonb,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists atlas_template_activity_created_idx
  on public.atlas_template_activity_log (template_id, created_at desc);

create table if not exists public.atlas_documents (
  id text primary key,
  title text not null,
  content text not null default '',
  context_type text not null default 'workspace'
    check (context_type in ('workspace', 'project', 'initiative', 'action', 'cycle')),
  context_id text,
  icon text,
  color text,
  template_id text references public.atlas_templates(id) on delete restrict,
  template_instance_id text references public.atlas_template_instances(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'archived')),
  revision bigint not null default 0 check (revision >= 0),
  archived_at timestamptz,
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check ((context_type = 'workspace' and context_id is null) or (context_type <> 'workspace' and nullif(btrim(context_id), '') is not null))
);

create index if not exists atlas_documents_context_idx
  on public.atlas_documents (context_type, context_id, updated_at desc) where status = 'active';
create index if not exists atlas_documents_template_idx
  on public.atlas_documents (template_id, created_at desc) where template_id is not null;

create table if not exists public.atlas_document_versions (
  id bigint generated by default as identity primary key,
  document_id text not null references public.atlas_documents(id) on delete restrict,
  revision bigint not null,
  title text not null,
  content text not null,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (document_id, revision)
);

create table if not exists public.atlas_document_activity_log (
  id bigint generated by default as identity primary key,
  document_id text not null references public.atlas_documents(id) on delete restrict,
  event text not null,
  old_value jsonb,
  new_value jsonb,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists atlas_document_versions_created_idx
  on public.atlas_document_versions (document_id, revision desc);
create index if not exists atlas_document_activity_created_idx
  on public.atlas_document_activity_log (document_id, created_at desc);

alter table public.atlas_actions
  add column if not exists template_id text,
  add column if not exists template_instance_id text;
alter table public.atlas_projects
  add column if not exists template_id text,
  add column if not exists template_instance_id text;

do $migration$
begin
  if not exists (select 1 from pg_constraint where conname = 'atlas_actions_template_id_fkey') then
    alter table public.atlas_actions add constraint atlas_actions_template_id_fkey
      foreign key (template_id) references public.atlas_templates(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_actions_template_instance_id_fkey') then
    alter table public.atlas_actions add constraint atlas_actions_template_instance_id_fkey
      foreign key (template_instance_id) references public.atlas_template_instances(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_projects_template_id_fkey') then
    alter table public.atlas_projects add constraint atlas_projects_template_id_fkey
      foreign key (template_id) references public.atlas_templates(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_projects_template_instance_id_fkey') then
    alter table public.atlas_projects add constraint atlas_projects_template_instance_id_fkey
      foreign key (template_instance_id) references public.atlas_template_instances(id) on delete restrict;
  end if;
end
$migration$;

create index if not exists atlas_actions_template_idx on public.atlas_actions (template_id, created_at desc) where template_id is not null;
create index if not exists atlas_projects_template_idx on public.atlas_projects (template_id, created_at desc) where template_id is not null;
create index if not exists atlas_actions_template_instance_idx on public.atlas_actions (template_instance_id) where template_instance_id is not null;
create index if not exists atlas_projects_template_instance_idx on public.atlas_projects (template_instance_id) where template_instance_id is not null;
create index if not exists atlas_documents_template_instance_idx on public.atlas_documents (template_instance_id) where template_instance_id is not null;

create or replace function public.atlas_validate_template_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  field jsonb;
  field_key text;
  field_type text;
  keys text[] := array[]::text[];
  node_count integer;
  reachable_count integer;
  max_depth integer;
begin
  if new.mode = 'form' and jsonb_array_length(new.form_schema) = 0 then
    raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_FORM_SCHEMA_REQUIRED';
  end if;
  for field in select value from jsonb_array_elements(new.form_schema)
  loop
    if jsonb_typeof(field) <> 'object' then raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_FORM_FIELD_OBJECT_REQUIRED'; end if;
    field_key := nullif(btrim(field->>'key'), '');
    field_type := field->>'type';
    if field_key is null or field_key = any(keys) then raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_FORM_FIELD_KEY_INVALID'; end if;
    if field_type not in ('text','long_text','dropdown','checkboxes','date','instructions','title','priority','due_date','labels') then
      raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_FORM_FIELD_TYPE_INVALID';
    end if;
    if field_type in ('dropdown','checkboxes') and (jsonb_typeof(field->'options') <> 'array' or jsonb_array_length(field->'options') = 0) then
      raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_FORM_FIELD_OPTIONS_REQUIRED';
    end if;
    keys := array_append(keys, field_key);
  end loop;

  if new.template_type = 'action' then
    if new.mode = 'standard' and nullif(btrim(new.blueprint->>'title'), '') is null then raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_ACTION_TITLE_REQUIRED'; end if;
    with recursive nodes as (
      select item->>'key' as key, nullif(item->>'parent_key','') as parent_key
      from jsonb_array_elements(coalesce(new.blueprint->'sub_actions','[]'::jsonb)) item
    ), walk(key, depth, path) as (
      select key, 1, array[key] from nodes where parent_key is null
      union all
      select node.key, walk.depth + 1, walk.path || node.key from nodes node join walk on node.parent_key = walk.key where not node.key = any(walk.path)
    )
    select (select count(*) from nodes), count(distinct key), coalesce(max(depth),0) into node_count, reachable_count, max_depth from walk;
  elsif new.template_type = 'project' then
    if nullif(btrim(new.blueprint->>'name'), '') is null then raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_PROJECT_NAME_REQUIRED'; end if;
    with recursive nodes as (
      select item->>'key' as key, nullif(item->>'parent_key','') as parent_key
      from jsonb_array_elements(coalesce(new.blueprint->'actions','[]'::jsonb)) item
    ), walk(key, depth, path) as (
      select key, 1, array[key] from nodes where parent_key is null
      union all
      select node.key, walk.depth + 1, walk.path || node.key from nodes node join walk on node.parent_key = walk.key where not node.key = any(walk.path)
    )
    select (select count(*) from nodes), count(distinct key), coalesce(max(depth),0) into node_count, reachable_count, max_depth from walk;
  else
    if nullif(btrim(new.blueprint->>'title'), '') is null then raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_DOCUMENT_TITLE_REQUIRED'; end if;
    node_count := 0; reachable_count := 0; max_depth := 0;
  end if;
  if node_count <> reachable_count then raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_NODE_GRAPH_INVALID'; end if;
  if max_depth > 5 then raise exception using errcode = '23514', message = 'ATLAS_TEMPLATE_NODE_MAX_DEPTH'; end if;
  return new;
end
$function$;

create or replace function public.atlas_validate_document_context()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if new.context_type = 'workspace' then return new; end if;
  if new.context_type = 'project' and not exists (select 1 from public.atlas_projects where id = new.context_id and status <> 'archived') then raise exception using errcode = '23503', message = 'ATLAS_DOCUMENT_PROJECT_NOT_FOUND'; end if;
  if new.context_type = 'initiative' and not exists (select 1 from public.atlas_initiatives where id = new.context_id and status <> 'archived') then raise exception using errcode = '23503', message = 'ATLAS_DOCUMENT_INITIATIVE_NOT_FOUND'; end if;
  if new.context_type = 'action' and not exists (select 1 from public.atlas_actions where id = new.context_id and status <> 'archived') then raise exception using errcode = '23503', message = 'ATLAS_DOCUMENT_ACTION_NOT_FOUND'; end if;
  if new.context_type = 'cycle' and not exists (select 1 from public.atlas_cycles where id = new.context_id and status <> 'archived') then raise exception using errcode = '23503', message = 'ATLAS_DOCUMENT_CYCLE_NOT_FOUND'; end if;
  return new;
end
$function$;

create or replace function public.atlas_audit_template_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_template_activity_log (template_id,event,old_value,new_value,actor)
  values (new.id,
    case when tg_op='INSERT' then 'template_created' when new.status='archived' and old.status='active' then 'template_archived' when new.status='active' and old.status='archived' then 'template_restored' when new.is_default is distinct from old.is_default then 'template_default_changed' else 'template_updated' end,
    case when tg_op='INSERT' then null else to_jsonb(old) end, to_jsonb(new), case when tg_op='INSERT' then new.created_by else new.updated_by end);
  return new;
end
$function$;

create or replace function public.atlas_audit_document_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_document_versions (document_id,revision,title,content,actor)
  values (new.id,new.revision,new.title,new.content,case when tg_op='INSERT' then new.created_by else new.updated_by end);
  insert into public.atlas_document_activity_log (document_id,event,old_value,new_value,actor)
  values (new.id,
    case when tg_op='INSERT' then 'document_created' when new.status='archived' and old.status='active' then 'document_archived' when new.status='active' and old.status='archived' then 'document_restored' else 'document_updated' end,
    case when tg_op='INSERT' then null else to_jsonb(old) end,to_jsonb(new),case when tg_op='INSERT' then new.created_by else new.updated_by end);
  return new;
end
$function$;

revoke all on function public.atlas_validate_template_row() from public;
revoke all on function public.atlas_validate_document_context() from public;
revoke all on function public.atlas_audit_template_row() from public;
revoke all on function public.atlas_audit_document_row() from public;

create trigger atlas_templates_validate_row before insert or update of template_type,mode,scope,business,blueprint,form_schema on public.atlas_templates for each row execute function public.atlas_validate_template_row();
create trigger atlas_templates_audit_row after insert or update on public.atlas_templates for each row execute function public.atlas_audit_template_row();
create trigger atlas_documents_validate_context before insert or update of context_type,context_id on public.atlas_documents for each row execute function public.atlas_validate_document_context();
create trigger atlas_documents_audit_row after insert or update on public.atlas_documents for each row execute function public.atlas_audit_document_row();

create or replace function public.instantiate_atlas_template(
  p_template_id text,
  p_title_override text,
  p_business text,
  p_context_type text,
  p_context_id text,
  p_form_values jsonb,
  p_overrides jsonb,
  p_actor text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  template_row public.atlas_templates%rowtype;
  instance_id text := gen_random_uuid()::text;
  result_id text := gen_random_uuid()::text;
  config jsonb;
  values_json jsonb := coalesce(p_form_values,'{}'::jsonb);
  field jsonb;
  field_value jsonb;
  resolved_title text;
  resolved_description text;
  resolved_priority text;
  resolved_due_date text;
  resolved_tags jsonb;
  resolved_business text;
  node jsonb;
  node_ids jsonb := '{}'::jsonb;
  milestone jsonb;
  milestone_ids jsonb := '{}'::jsonb;
  initiative_id jsonb;
  node_id text;
  parent_id text;
  milestone_id text;
  node_depth integer;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  if jsonb_typeof(values_json) <> 'object' or jsonb_typeof(coalesce(p_overrides,'{}'::jsonb)) <> 'object' then raise exception using errcode='22023',message='ATLAS_TEMPLATE_INPUT_OBJECT_REQUIRED'; end if;
  select * into template_row from public.atlas_templates where id=p_template_id for update;
  if not found then raise exception using errcode='P0002',message='ATLAS_TEMPLATE_NOT_FOUND'; end if;
  if template_row.status <> 'active' then raise exception using errcode='55000',message='ATLAS_TEMPLATE_ARCHIVED'; end if;
  config := template_row.blueprint || coalesce(p_overrides,'{}'::jsonb);

  for field in select value from jsonb_array_elements(template_row.form_schema)
  loop
    field_value := values_json->(field->>'key');
    if coalesce((field->>'required')::boolean,false) and (field_value is null or field_value='null'::jsonb or field_value='""'::jsonb or field_value='[]'::jsonb) then
      raise exception using errcode='22023',message='ATLAS_TEMPLATE_REQUIRED_FIELD_MISSING',detail=field->>'key';
    end if;
    if field->>'type' in ('dropdown','checkboxes') and field_value is not null and field_value <> 'null'::jsonb then
      if field->>'type'='dropdown' and not (field->'options' @> jsonb_build_array(field_value)) then raise exception using errcode='22023',message='ATLAS_TEMPLATE_FIELD_OPTION_INVALID',detail=field->>'key'; end if;
      if field->>'type'='checkboxes' and exists (select 1 from jsonb_array_elements(field_value) choice where not (field->'options' @> jsonb_build_array(choice))) then raise exception using errcode='22023',message='ATLAS_TEMPLATE_FIELD_OPTION_INVALID',detail=field->>'key'; end if;
    end if;
  end loop;

  insert into public.atlas_template_instances (id,template_id,template_revision,result_entity_type,result_entity_id,form_values,overrides,actor)
  values (instance_id,template_row.id,template_row.revision,template_row.template_type,result_id,values_json,coalesce(p_overrides,'{}'::jsonb),p_actor);

  if template_row.template_type='action' then
    resolved_title := coalesce(nullif(btrim(p_title_override),''),nullif(btrim(values_json->>'title'),''),nullif(btrim(config->>'title'),''));
    resolved_description := coalesce(config->>'description','');
    resolved_priority := coalesce(values_json->>'priority',config->>'priority','p2');
    resolved_due_date := coalesce(values_json->>'due_date',nullif(config->>'due_date',''),case when config ? 'due_offset_days' then (current_date + (config->>'due_offset_days')::integer)::text else null end);
    resolved_tags := coalesce(values_json->'labels',config->'tags','[]'::jsonb);
    resolved_business := coalesce(nullif(p_business,''),nullif(config->>'business',''),template_row.business);
    for field in select value from jsonb_array_elements(template_row.form_schema)
    loop
      field_value := values_json->(field->>'key');
      if field->>'type'='title' and field_value is not null then resolved_title := field_value#>>'{}';
      elsif field->>'type'='priority' and field_value is not null then resolved_priority := field_value#>>'{}';
      elsif field->>'type'='due_date' and field_value is not null then resolved_due_date := field_value#>>'{}';
      elsif field->>'type'='labels' and field_value is not null then resolved_tags := field_value;
      elsif field->>'type'='instructions' then resolved_description := resolved_description || E'\n\n' || coalesce(field->>'help_text',field->>'label','');
      elsif field_value is not null and field_value <> 'null'::jsonb and field->>'type' in ('text','long_text','dropdown','checkboxes','date') then
        resolved_description := resolved_description || E'\n\n## ' || coalesce(field->>'label',field->>'key') || E'\n' || case when jsonb_typeof(field_value)='string' then field_value#>>'{}' else field_value::text end;
      end if;
    end loop;
    if resolved_title is null then raise exception using errcode='22023',message='ATLAS_TEMPLATE_ACTION_TITLE_REQUIRED'; end if;
    if resolved_business is null then raise exception using errcode='22023',message='ATLAS_TEMPLATE_ACTION_BUSINESS_REQUIRED'; end if;
    insert into public.atlas_actions (id,title,description,status,business,priority,due_date,owners,tags,evidence_json,source_label,project_id,project_milestone_id,estimate_points,work_mode,next_action,definition_of_done,review_date,recurrence,notes,template_id,template_instance_id,created_at,updated_at)
    values (result_id,resolved_title,resolved_description,coalesce(config->>'status','not_started'),resolved_business,resolved_priority,resolved_due_date,coalesce(config->'owners','["ransomed"]'::jsonb),resolved_tags,'{}'::jsonb,'template:'||template_row.name,nullif(config->>'project_id',''),nullif(config->>'project_milestone_id',''),(config->>'estimate_points')::integer,nullif(config->>'work_mode',''),nullif(config->>'next_action',''),nullif(config->>'definition_of_done',''),nullif(config->>'review_date',''),coalesce(config->>'recurrence','none'),coalesce(config->>'notes',''),template_row.id,instance_id,timezone('utc',now()),timezone('utc',now()));

    for node,node_depth in
      with recursive nodes as (
        select value item from jsonb_array_elements(coalesce(config->'sub_actions','[]'::jsonb))
      ), walk(item,depth) as (
        select item,1 from nodes where nullif(item->>'parent_key','') is null
        union all select node.item,walk.depth+1 from nodes node join walk on node.item->>'parent_key'=walk.item->>'key'
      ) select item,depth from walk order by depth,item->>'key'
    loop
      node_id := gen_random_uuid()::text;
      node_ids := node_ids || jsonb_build_object(node->>'key',node_id);
      parent_id := case when nullif(node->>'parent_key','') is null then result_id else node_ids->>(node->>'parent_key') end;
      insert into public.atlas_actions (id,title,description,status,business,priority,due_date,owners,tags,evidence_json,source_label,parent_action_id,estimate_points,template_id,template_instance_id,created_at,updated_at)
      values (node_id,node->>'title',coalesce(node->>'description',''),coalesce(node->>'status',config->>'status','not_started'),resolved_business,coalesce(node->>'priority',resolved_priority),case when node ? 'due_offset_days' then (current_date+(node->>'due_offset_days')::integer)::text else resolved_due_date end,coalesce(node->'owners',config->'owners','["ransomed"]'::jsonb),coalesce(node->'tags','[]'::jsonb),'{}'::jsonb,'template:'||template_row.name,parent_id,(node->>'estimate_points')::integer,template_row.id,instance_id,timezone('utc',now()),timezone('utc',now()));
    end loop;

  elsif template_row.template_type='project' then
    resolved_title := coalesce(nullif(btrim(p_title_override),''),nullif(btrim(config->>'name'),''));
    resolved_business := coalesce(nullif(p_business,''),nullif(config->>'business',''),template_row.business);
    insert into public.atlas_projects (id,name,summary,description,business,status,health,priority,lead_id,members,start_date,target_date,update_frequency,template_id,template_instance_id,created_by,updated_by)
    values (result_id,resolved_title,coalesce(config->>'summary',''),coalesce(config->>'description',''),resolved_business,coalesce(config->>'status','planned'),coalesce(config->>'health','no_update'),nullif(config->>'priority',''),coalesce(nullif(config->>'lead_id',''),'ransomed'),coalesce(config->'members','["ransomed"]'::jsonb),case when nullif(config->>'start_date','') is not null then (config->>'start_date')::date when config ? 'start_offset_days' then current_date+(config->>'start_offset_days')::integer else null end,case when nullif(config->>'target_date','') is not null then (config->>'target_date')::date when config ? 'target_offset_days' then current_date+(config->>'target_offset_days')::integer else null end,coalesce(config->>'update_frequency','weekly'),template_row.id,instance_id,p_actor,p_actor);
    for milestone in select value from jsonb_array_elements(coalesce(config->'milestones','[]'::jsonb))
    loop
      milestone_id := gen_random_uuid()::text;
      milestone_ids := milestone_ids || jsonb_build_object(milestone->>'key',milestone_id);
      insert into public.atlas_project_milestones (id,project_id,name,description,target_date,status,sort_order,created_by,updated_by)
      values (milestone_id,result_id,milestone->>'name',coalesce(milestone->>'description',''),case when milestone ? 'target_offset_days' then current_date+(milestone->>'target_offset_days')::integer else null end,coalesce(milestone->>'status','planned'),coalesce((milestone->>'sort_order')::integer,0),p_actor,p_actor);
    end loop;
    for initiative_id in select value from jsonb_array_elements(coalesce(config->'initiative_ids','[]'::jsonb))
    loop
      perform public.set_atlas_initiative_project(initiative_id#>>'{}',result_id,true,p_actor);
    end loop;
    for node,node_depth in
      with recursive nodes as (select value item from jsonb_array_elements(coalesce(config->'actions','[]'::jsonb))), walk(item,depth) as (
        select item,1 from nodes where nullif(item->>'parent_key','') is null
        union all select node.item,walk.depth+1 from nodes node join walk on node.item->>'parent_key'=walk.item->>'key'
      ) select item,depth from walk order by depth,item->>'key'
    loop
      node_id := gen_random_uuid()::text;
      node_ids := node_ids || jsonb_build_object(node->>'key',node_id);
      parent_id := case when nullif(node->>'parent_key','') is null then null else node_ids->>(node->>'parent_key') end;
      milestone_id := case when nullif(node->>'milestone_key','') is null then null else milestone_ids->>(node->>'milestone_key') end;
      if nullif(node->>'milestone_key','') is not null and milestone_id is null then raise exception using errcode='22023',message='ATLAS_TEMPLATE_MILESTONE_KEY_NOT_FOUND'; end if;
      insert into public.atlas_actions (id,title,description,status,business,priority,due_date,owners,tags,evidence_json,source_label,project_id,project_milestone_id,parent_action_id,estimate_points,template_id,template_instance_id,created_at,updated_at)
      values (node_id,node->>'title',coalesce(node->>'description',''),coalesce(node->>'status','not_started'),coalesce(resolved_business,'personal'),coalesce(node->>'priority','p2'),case when node ? 'due_offset_days' then (current_date+(node->>'due_offset_days')::integer)::text else null end,coalesce(node->'owners','["ransomed"]'::jsonb),coalesce(node->'tags','[]'::jsonb),'{}'::jsonb,'template:'||template_row.name,result_id,milestone_id,parent_id,(node->>'estimate_points')::integer,template_row.id,instance_id,timezone('utc',now()),timezone('utc',now()));
    end loop;

  else
    if p_context_type is not null and p_context_type not in ('workspace','project','initiative','action','cycle') then raise exception using errcode='22023',message='ATLAS_DOCUMENT_CONTEXT_INVALID'; end if;
    if config ? 'allowed_context_types' and not (config->'allowed_context_types' @> jsonb_build_array(coalesce(p_context_type,'workspace'))) then raise exception using errcode='22023',message='ATLAS_DOCUMENT_TEMPLATE_CONTEXT_NOT_ALLOWED'; end if;
    insert into public.atlas_documents (id,title,content,context_type,context_id,icon,color,template_id,template_instance_id,status,revision,created_by,updated_by)
    values (result_id,coalesce(nullif(btrim(p_title_override),''),config->>'title'),coalesce(config->>'content',''),coalesce(p_context_type,'workspace'),case when coalesce(p_context_type,'workspace')='workspace' then null else p_context_id end,config->>'icon',config->>'color',template_row.id,instance_id,'active',0,p_actor,p_actor);
  end if;

  update public.atlas_templates set usage_count=usage_count+1,last_used_at=timezone('utc',now()),updated_at=timezone('utc',now()) where id=template_row.id;
  insert into public.atlas_template_activity_log (template_id,event,new_value,actor)
  values (template_row.id,'template_instantiated',jsonb_build_object('instance_id',instance_id,'result_entity_type',template_row.template_type,'result_entity_id',result_id,'template_revision',template_row.revision),p_actor);
  return jsonb_build_object('instance_id',instance_id,'template_id',template_row.id,'template_revision',template_row.revision,'result_entity_type',template_row.template_type,'result_entity_id',result_id);
end
$function$;

create or replace function public.transition_atlas_template(p_template_id text,p_restore boolean,p_actor text,p_expected_revision bigint)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare row_value public.atlas_templates%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into row_value from public.atlas_templates where id=p_template_id for update;
  if not found then raise exception using errcode='P0002',message='ATLAS_TEMPLATE_NOT_FOUND'; end if;
  if row_value.revision<>p_expected_revision then raise exception using errcode='40001',message='ATLAS_TEMPLATE_REVISION_CONFLICT'; end if;
  update public.atlas_templates set status=case when p_restore then 'active' else 'archived' end,is_default=case when p_restore then is_default else false end,archived_at=case when p_restore then null else timezone('utc',now()) end,revision=revision+1,updated_by=p_actor,updated_at=timezone('utc',now()) where id=p_template_id returning * into row_value;
  return to_jsonb(row_value);
end $function$;

create or replace function public.duplicate_atlas_template(p_template_id text,p_new_template_id text,p_name text,p_actor text)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare source_row public.atlas_templates%rowtype; result_row public.atlas_templates%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into source_row from public.atlas_templates where id=p_template_id;
  if not found then raise exception using errcode='P0002',message='ATLAS_TEMPLATE_NOT_FOUND'; end if;
  insert into public.atlas_templates (id,name,description,template_type,mode,scope,business,default_audience,is_default,blueprint,form_schema,status,created_by,updated_by)
  values (p_new_template_id,coalesce(nullif(btrim(p_name),''),source_row.name||' copy'),source_row.description,source_row.template_type,source_row.mode,source_row.scope,source_row.business,source_row.default_audience,false,source_row.blueprint,source_row.form_schema,'active',p_actor,p_actor) returning * into result_row;
  return to_jsonb(result_row);
end $function$;

create or replace function public.transition_atlas_document(p_document_id text,p_restore boolean,p_actor text,p_expected_revision bigint)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare row_value public.atlas_documents%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into row_value from public.atlas_documents where id=p_document_id for update;
  if not found then raise exception using errcode='P0002',message='ATLAS_DOCUMENT_NOT_FOUND'; end if;
  if row_value.revision<>p_expected_revision then raise exception using errcode='40001',message='ATLAS_DOCUMENT_REVISION_CONFLICT'; end if;
  update public.atlas_documents set status=case when p_restore then 'active' else 'archived' end,archived_at=case when p_restore then null else timezone('utc',now()) end,revision=revision+1,updated_by=p_actor,updated_at=timezone('utc',now()) where id=p_document_id returning * into row_value;
  return to_jsonb(row_value);
end $function$;

revoke all on function public.instantiate_atlas_template(text,text,text,text,text,jsonb,jsonb,text) from public;
revoke all on function public.transition_atlas_template(text,boolean,text,bigint) from public;
revoke all on function public.duplicate_atlas_template(text,text,text,text) from public;
revoke all on function public.transition_atlas_document(text,boolean,text,bigint) from public;

drop trigger if exists atlas_templates_reject_delete on public.atlas_templates;
create trigger atlas_templates_reject_delete before delete on public.atlas_templates for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_template_instances_reject_mutation on public.atlas_template_instances;
create trigger atlas_template_instances_reject_mutation before update or delete on public.atlas_template_instances for each row execute function public.atlas_reject_project_history_mutation();
drop trigger if exists atlas_template_activity_reject_mutation on public.atlas_template_activity_log;
create trigger atlas_template_activity_reject_mutation before update or delete on public.atlas_template_activity_log for each row execute function public.atlas_reject_project_history_mutation();
drop trigger if exists atlas_documents_reject_delete on public.atlas_documents;
create trigger atlas_documents_reject_delete before delete on public.atlas_documents for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_document_versions_reject_mutation on public.atlas_document_versions;
create trigger atlas_document_versions_reject_mutation before update or delete on public.atlas_document_versions for each row execute function public.atlas_reject_project_history_mutation();
drop trigger if exists atlas_document_activity_reject_mutation on public.atlas_document_activity_log;
create trigger atlas_document_activity_reject_mutation before update or delete on public.atlas_document_activity_log for each row execute function public.atlas_reject_project_history_mutation();

alter table public.atlas_templates enable row level security;
alter table public.atlas_template_instances enable row level security;
alter table public.atlas_template_activity_log enable row level security;
alter table public.atlas_documents enable row level security;
alter table public.atlas_document_versions enable row level security;
alter table public.atlas_document_activity_log enable row level security;

revoke all on table public.atlas_templates,public.atlas_template_instances,public.atlas_template_activity_log,public.atlas_documents,public.atlas_document_versions,public.atlas_document_activity_log from public;

do $migration$
declare role_name text;
begin
  foreach role_name in array array['anon','authenticated'] loop
    if exists(select 1 from pg_roles where rolname=role_name) then
      execute format('revoke all on table public.atlas_templates,public.atlas_template_instances,public.atlas_template_activity_log,public.atlas_documents,public.atlas_document_versions,public.atlas_document_activity_log from %I',role_name);
      execute format('revoke execute on function public.instantiate_atlas_template(text,text,text,text,text,jsonb,jsonb,text) from %I',role_name);
      execute format('revoke execute on function public.transition_atlas_template(text,boolean,text,bigint) from %I',role_name);
      execute format('revoke execute on function public.duplicate_atlas_template(text,text,text,text) from %I',role_name);
      execute format('revoke execute on function public.transition_atlas_document(text,boolean,text,bigint) from %I',role_name);
    end if;
  end loop;
  if exists(select 1 from pg_roles where rolname='service_role') then
    grant select,insert,update on public.atlas_templates,public.atlas_documents to service_role;
    grant select,insert on public.atlas_template_instances,public.atlas_template_activity_log,public.atlas_document_versions,public.atlas_document_activity_log to service_role;
    grant usage,select on sequence public.atlas_template_activity_log_id_seq,public.atlas_document_versions_id_seq,public.atlas_document_activity_log_id_seq to service_role;
    revoke delete,truncate on public.atlas_templates,public.atlas_template_instances,public.atlas_template_activity_log,public.atlas_documents,public.atlas_document_versions,public.atlas_document_activity_log from service_role;
    revoke update on public.atlas_template_instances,public.atlas_template_activity_log,public.atlas_document_versions,public.atlas_document_activity_log from service_role;
    grant execute on function public.instantiate_atlas_template(text,text,text,text,text,jsonb,jsonb,text) to service_role;
    grant execute on function public.transition_atlas_template(text,boolean,text,bigint) to service_role;
    grant execute on function public.duplicate_atlas_template(text,text,text,text) to service_role;
    grant execute on function public.transition_atlas_document(text,boolean,text,bigint) to service_role;
  end if;
end $migration$;

comment on table public.atlas_templates is 'Reusable action, project, and document blueprints with standard/form modes, defaults, and provenance.';
comment on table public.atlas_documents is 'Versioned Markdown documents attached to one Atlas work context.';
