-- Linear parity slice 1: first-class ATLAS projects, milestones, health updates,
-- dependencies, action membership, effort, and append-only project evidence.
-- Forward-only. No project or project-history row is physically deleted.

create table if not exists public.atlas_projects (
  id text primary key,
  name text not null,
  summary text not null default '',
  description text not null default '',
  business text,
  status text not null default 'planned'
    check (status in ('backlog', 'planned', 'in_progress', 'paused', 'completed', 'canceled', 'archived')),
  health text not null default 'no_update'
    check (health in ('on_track', 'at_risk', 'off_track', 'no_update')),
  priority text
    check (priority is null or priority in ('p0', 'p1', 'p2', 'p3')),
  lead_id text references public.atlas_members(id),
  members jsonb not null default '[]'::jsonb
    check (jsonb_typeof(members) = 'array'),
  start_date date,
  target_date date,
  color text,
  icon text,
  update_frequency text not null default 'weekly'
    check (update_frequency in ('weekly', 'biweekly', 'monthly', 'never')),
  archived_from_status text,
  revision bigint not null default 0 check (revision >= 0),
  created_by text not null default 'system',
  updated_by text not null default 'system',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (start_date is null or target_date is null or start_date <= target_date)
);

create table if not exists public.atlas_project_milestones (
  id text primary key,
  project_id text not null references public.atlas_projects(id) on delete restrict,
  name text not null,
  description text not null default '',
  target_date date,
  status text not null default 'planned'
    check (status in ('planned', 'in_progress', 'completed', 'archived')),
  sort_order integer not null default 0,
  archived_from_status text,
  revision bigint not null default 0 check (revision >= 0),
  created_by text not null default 'system',
  updated_by text not null default 'system',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (project_id, name)
);

create table if not exists public.atlas_project_updates (
  id text primary key,
  project_id text not null references public.atlas_projects(id) on delete restrict,
  health text not null check (health in ('on_track', 'at_risk', 'off_track')),
  body text not null,
  created_by text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.atlas_project_dependencies (
  id text primary key,
  blocked_project_id text not null references public.atlas_projects(id) on delete restrict,
  blocking_project_id text not null references public.atlas_projects(id) on delete restrict,
  status text not null default 'active'
    check (status in ('active', 'resolved', 'archived')),
  note text not null default '',
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (blocked_project_id <> blocking_project_id)
);

create unique index if not exists atlas_project_dependencies_active_pair_idx
  on public.atlas_project_dependencies (blocked_project_id, blocking_project_id)
  where status = 'active';

create table if not exists public.atlas_project_activity_log (
  id bigint generated by default as identity primary key,
  project_id text not null references public.atlas_projects(id) on delete restrict,
  event text not null,
  old_value jsonb,
  new_value jsonb,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.atlas_actions
  add column if not exists project_id text,
  add column if not exists project_milestone_id text,
  add column if not exists estimate_points integer;

do $migration$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'atlas_actions_project_id_fkey'
  ) then
    alter table public.atlas_actions
      add constraint atlas_actions_project_id_fkey
      foreign key (project_id) references public.atlas_projects(id) on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'atlas_actions_project_milestone_id_fkey'
  ) then
    alter table public.atlas_actions
      add constraint atlas_actions_project_milestone_id_fkey
      foreign key (project_milestone_id) references public.atlas_project_milestones(id) on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'atlas_actions_estimate_points_check'
  ) then
    alter table public.atlas_actions
      add constraint atlas_actions_estimate_points_check
      check (estimate_points is null or estimate_points between 0 and 100000);
  end if;
end
$migration$;

create index if not exists atlas_projects_status_target_idx
  on public.atlas_projects (status, target_date);
create index if not exists atlas_projects_business_status_idx
  on public.atlas_projects (business, status);
create index if not exists atlas_project_milestones_project_order_idx
  on public.atlas_project_milestones (project_id, sort_order, target_date);
create index if not exists atlas_project_updates_project_created_idx
  on public.atlas_project_updates (project_id, created_at desc);
create index if not exists atlas_project_dependencies_blocked_idx
  on public.atlas_project_dependencies (blocked_project_id, status);
create index if not exists atlas_project_dependencies_blocking_idx
  on public.atlas_project_dependencies (blocking_project_id, status);
create index if not exists atlas_project_activity_project_created_idx
  on public.atlas_project_activity_log (project_id, created_at desc);
create index if not exists atlas_actions_project_status_idx
  on public.atlas_actions (project_id, status);
create index if not exists atlas_actions_project_milestone_idx
  on public.atlas_actions (project_milestone_id, status);

create or replace function public.atlas_validate_project_membership()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  milestone_project_id text;
begin
  if new.project_milestone_id is not null then
    if new.project_id is null then
      raise exception using errcode = '23514', message = 'ATLAS_PROJECT_REQUIRED_FOR_MILESTONE';
    end if;

    select milestone.project_id
      into milestone_project_id
      from public.atlas_project_milestones milestone
     where milestone.id = new.project_milestone_id
       and milestone.status <> 'archived';

    if milestone_project_id is null or milestone_project_id <> new.project_id then
      raise exception using errcode = '23514', message = 'ATLAS_PROJECT_MILESTONE_MISMATCH';
    end if;
  end if;

  return new;
end
$function$;

revoke all on function public.atlas_validate_project_membership() from public;

drop trigger if exists atlas_actions_validate_project_membership on public.atlas_actions;
create trigger atlas_actions_validate_project_membership
before insert or update of project_id, project_milestone_id on public.atlas_actions
for each row execute function public.atlas_validate_project_membership();

create or replace function public.atlas_validate_project_principals()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  principal_count integer;
  active_count integer;
begin
  if new.lead_id is not null and new.lead_id not in ('ransomed', 'codex', 'claude') then
    raise exception using errcode = '23514', message = 'ATLAS_PROJECT_LEAD_NOT_ALLOWED';
  end if;

  if new.members is null or jsonb_typeof(new.members) <> 'array' then
    raise exception using errcode = '23514', message = 'ATLAS_PROJECT_MEMBERS_ARRAY_REQUIRED';
  end if;

  if exists (
    select 1 from jsonb_array_elements_text(new.members) member(value)
    where member.value not in ('ransomed', 'codex', 'claude')
  ) then
    raise exception using errcode = '23514', message = 'ATLAS_PROJECT_MEMBER_NOT_ALLOWED';
  end if;

  select count(*), count(distinct member.value)
    into principal_count, active_count
    from jsonb_array_elements_text(new.members) member(value);

  if principal_count <> active_count then
    raise exception using errcode = '23514', message = 'ATLAS_PROJECT_DUPLICATE_MEMBER';
  end if;

  select count(*)
    into active_count
    from public.atlas_members member
   where member.id in (select jsonb_array_elements_text(new.members))
     and member.is_active
     and member.principal_type in ('owner', 'agent');

  if active_count <> principal_count then
    raise exception using errcode = '23514', message = 'ATLAS_PROJECT_MEMBER_REFERENCE_INVALID';
  end if;

  return new;
end
$function$;

revoke all on function public.atlas_validate_project_principals() from public;

drop trigger if exists atlas_projects_validate_principals on public.atlas_projects;
create trigger atlas_projects_validate_principals
before insert or update of lead_id, members on public.atlas_projects
for each row execute function public.atlas_validate_project_principals();

create or replace function public.atlas_audit_project_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  event_name text;
  event_actor text;
begin
  if tg_op = 'INSERT' then
    event_name := 'created';
    event_actor := new.created_by;
    insert into public.atlas_project_activity_log (project_id, event, old_value, new_value, actor)
    values (new.id, event_name, null, to_jsonb(new), event_actor);
  else
    event_name := case
      when new.status = 'archived' and old.status <> 'archived' then 'archived'
      when old.status = 'archived' and new.status <> 'archived' then 'restored'
      when new.health is distinct from old.health then 'health_changed'
      when new.status is distinct from old.status then 'status_changed'
      else 'updated'
    end;
    event_actor := new.updated_by;
    insert into public.atlas_project_activity_log (project_id, event, old_value, new_value, actor)
    values (new.id, event_name, to_jsonb(old), to_jsonb(new), event_actor);
  end if;
  return new;
end
$function$;

create or replace function public.atlas_audit_project_milestone_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_project_activity_log (project_id, event, old_value, new_value, actor)
  values (
    new.project_id,
    case
      when tg_op = 'INSERT' then 'milestone_created'
      when new.status = 'archived' and old.status <> 'archived' then 'milestone_archived'
      else 'milestone_updated'
    end,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new),
    case when tg_op = 'INSERT' then new.created_by else new.updated_by end
  );
  return new;
end
$function$;

create or replace function public.atlas_audit_project_dependency_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_project_activity_log (project_id, event, old_value, new_value, actor)
  values (
    new.blocked_project_id,
    case
      when tg_op = 'INSERT' then 'dependency_created'
      when new.status = 'resolved' and old.status = 'active' then 'dependency_resolved'
      when new.status = 'archived' and old.status <> 'archived' then 'dependency_archived'
      else 'dependency_updated'
    end,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new),
    case when tg_op = 'INSERT' then new.created_by else new.updated_by end
  );
  return new;
end
$function$;

revoke all on function public.atlas_audit_project_row() from public;
revoke all on function public.atlas_audit_project_milestone_row() from public;
revoke all on function public.atlas_audit_project_dependency_row() from public;

drop trigger if exists atlas_projects_audit_row on public.atlas_projects;
create trigger atlas_projects_audit_row
after insert or update on public.atlas_projects
for each row execute function public.atlas_audit_project_row();

drop trigger if exists atlas_project_milestones_audit_row on public.atlas_project_milestones;
create trigger atlas_project_milestones_audit_row
after insert or update on public.atlas_project_milestones
for each row execute function public.atlas_audit_project_milestone_row();

drop trigger if exists atlas_project_dependencies_audit_row on public.atlas_project_dependencies;
create trigger atlas_project_dependencies_audit_row
after insert or update on public.atlas_project_dependencies
for each row execute function public.atlas_audit_project_dependency_row();

create or replace function public.post_atlas_project_update(
  p_project_id text,
  p_update_id text,
  p_health text,
  p_body text,
  p_actor text
)
returns jsonb
language plpgsql
set search_path = ''
as $function$
declare
  project_row public.atlas_projects%rowtype;
  update_row public.atlas_project_updates%rowtype;
  old_health text;
begin
  if p_health not in ('on_track', 'at_risk', 'off_track') then
    raise exception using errcode = '22023', message = 'ATLAS_PROJECT_UPDATE_HEALTH_INVALID';
  end if;
  if nullif(btrim(p_body), '') is null then
    raise exception using errcode = '22023', message = 'ATLAS_PROJECT_UPDATE_BODY_REQUIRED';
  end if;

  select * into project_row
    from public.atlas_projects
   where id = p_project_id
   for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'ATLAS_PROJECT_NOT_FOUND';
  end if;
  if project_row.status = 'archived' then
    raise exception using errcode = '55000', message = 'ATLAS_PROJECT_ARCHIVED';
  end if;
  old_health := project_row.health;

  insert into public.atlas_project_updates (id, project_id, health, body, created_by)
  values (p_update_id, p_project_id, p_health, btrim(p_body), p_actor)
  returning * into update_row;

  update public.atlas_projects
     set health = p_health,
         revision = revision + 1,
         updated_by = p_actor,
         updated_at = timezone('utc', now())
   where id = p_project_id
  returning * into project_row;

  insert into public.atlas_project_activity_log (project_id, event, old_value, new_value, actor)
  values (
    p_project_id,
    'health_update_posted',
    jsonb_build_object('health', old_health),
    jsonb_build_object('update_id', p_update_id, 'health', p_health),
    p_actor
  );

  return jsonb_build_object('update', to_jsonb(update_row), 'project', to_jsonb(project_row));
end
$function$;

create or replace function public.assign_atlas_action_to_project(
  p_project_id text,
  p_action_id text,
  p_milestone_id text,
  p_estimate_points integer,
  p_actor text
)
returns jsonb
language plpgsql
set search_path = ''
as $function$
declare
  project_row public.atlas_projects%rowtype;
  action_row public.atlas_actions%rowtype;
  old_project_id text;
  old_milestone_id text;
  old_estimate integer;
begin
  select * into project_row from public.atlas_projects where id = p_project_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_PROJECT_NOT_FOUND'; end if;
  if project_row.status = 'archived' then raise exception using errcode = '55000', message = 'ATLAS_PROJECT_ARCHIVED'; end if;
  if p_estimate_points is not null and (p_estimate_points < 0 or p_estimate_points > 100000) then
    raise exception using errcode = '22023', message = 'ATLAS_PROJECT_ESTIMATE_INVALID';
  end if;
  if p_milestone_id is not null and not exists (
    select 1 from public.atlas_project_milestones
     where id = p_milestone_id and project_id = p_project_id and status <> 'archived'
  ) then
    raise exception using errcode = '23503', message = 'ATLAS_PROJECT_MILESTONE_INVALID';
  end if;

  select * into action_row from public.atlas_actions where id = p_action_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_ACTION_NOT_FOUND'; end if;
  old_project_id := action_row.project_id;
  old_milestone_id := action_row.project_milestone_id;
  old_estimate := action_row.estimate_points;

  update public.atlas_actions
     set project_id = p_project_id,
         project_milestone_id = p_milestone_id,
         estimate_points = p_estimate_points,
         updated_at = timezone('utc', now())
   where id = p_action_id
  returning * into action_row;

  insert into public.atlas_activity_log (action_id, event, old_value, new_value, actor)
  values (
    p_action_id,
    'project_assigned',
    jsonb_build_object('project_id', old_project_id, 'project_milestone_id', old_milestone_id, 'estimate_points', old_estimate)::text,
    jsonb_build_object('project_id', p_project_id, 'project_milestone_id', p_milestone_id, 'estimate_points', p_estimate_points)::text,
    p_actor
  );
  insert into public.atlas_project_activity_log (project_id, event, old_value, new_value, actor)
  values (p_project_id, 'action_assigned', jsonb_build_object('project_id', old_project_id), jsonb_build_object('action_id', p_action_id, 'milestone_id', p_milestone_id), p_actor);
  return to_jsonb(action_row);
end
$function$;

create or replace function public.remove_atlas_action_from_project(
  p_project_id text,
  p_action_id text,
  p_actor text
)
returns jsonb
language plpgsql
set search_path = ''
as $function$
declare
  action_row public.atlas_actions%rowtype;
  old_value jsonb;
begin
  select * into action_row
    from public.atlas_actions
   where id = p_action_id and project_id = p_project_id
   for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_PROJECT_ACTION_NOT_FOUND'; end if;
  old_value := jsonb_build_object('project_id', action_row.project_id, 'project_milestone_id', action_row.project_milestone_id, 'estimate_points', action_row.estimate_points);

  update public.atlas_actions
     set project_id = null,
         project_milestone_id = null,
         estimate_points = null,
         updated_at = timezone('utc', now())
   where id = p_action_id
  returning * into action_row;

  insert into public.atlas_activity_log (action_id, event, old_value, new_value, actor)
  values (p_action_id, 'project_removed', old_value::text, jsonb_build_object('project_id', null, 'project_milestone_id', null, 'estimate_points', null)::text, p_actor);
  insert into public.atlas_project_activity_log (project_id, event, old_value, new_value, actor)
  values (p_project_id, 'action_removed', jsonb_build_object('action_id', p_action_id), null, p_actor);
  return to_jsonb(action_row);
end
$function$;

revoke all on function public.post_atlas_project_update(text, text, text, text, text) from public;
revoke all on function public.assign_atlas_action_to_project(text, text, text, integer, text) from public;
revoke all on function public.remove_atlas_action_from_project(text, text, text) from public;

create or replace function public.atlas_reject_project_history_mutation()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  raise exception using
    errcode = '55000',
    message = 'ATLAS_PROJECT_HISTORY_IMMUTABLE',
    detail = format('%I.%I is append-only.', tg_table_schema, tg_table_name);
end
$function$;

revoke all on function public.atlas_reject_project_history_mutation() from public;

drop trigger if exists atlas_projects_reject_delete on public.atlas_projects;
create trigger atlas_projects_reject_delete
before delete on public.atlas_projects
for each row execute function public.atlas_reject_immutable_delete();

drop trigger if exists atlas_project_milestones_reject_delete on public.atlas_project_milestones;
create trigger atlas_project_milestones_reject_delete
before delete on public.atlas_project_milestones
for each row execute function public.atlas_reject_immutable_delete();

drop trigger if exists atlas_project_dependencies_reject_delete on public.atlas_project_dependencies;
create trigger atlas_project_dependencies_reject_delete
before delete on public.atlas_project_dependencies
for each row execute function public.atlas_reject_immutable_delete();

drop trigger if exists atlas_project_updates_reject_mutation on public.atlas_project_updates;
create trigger atlas_project_updates_reject_mutation
before update or delete on public.atlas_project_updates
for each row execute function public.atlas_reject_project_history_mutation();

drop trigger if exists atlas_project_activity_reject_mutation on public.atlas_project_activity_log;
create trigger atlas_project_activity_reject_mutation
before update or delete on public.atlas_project_activity_log
for each row execute function public.atlas_reject_project_history_mutation();

alter table public.atlas_projects enable row level security;
alter table public.atlas_project_milestones enable row level security;
alter table public.atlas_project_updates enable row level security;
alter table public.atlas_project_dependencies enable row level security;
alter table public.atlas_project_activity_log enable row level security;

revoke all on table public.atlas_projects from public;
revoke all on table public.atlas_project_milestones from public;
revoke all on table public.atlas_project_updates from public;
revoke all on table public.atlas_project_dependencies from public;
revoke all on table public.atlas_project_activity_log from public;

do $migration$
declare
  role_name text;
begin
  foreach role_name in array array['anon', 'authenticated']
  loop
    if exists (select 1 from pg_roles where rolname = role_name) then
      execute format('revoke all on table public.atlas_projects from %I', role_name);
      execute format('revoke all on table public.atlas_project_milestones from %I', role_name);
      execute format('revoke all on table public.atlas_project_updates from %I', role_name);
      execute format('revoke all on table public.atlas_project_dependencies from %I', role_name);
      execute format('revoke all on table public.atlas_project_activity_log from %I', role_name);
    end if;
  end loop;

  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant select, insert, update on table public.atlas_projects to service_role;
    grant select, insert, update on table public.atlas_project_milestones to service_role;
    grant select, insert on table public.atlas_project_updates to service_role;
    grant select, insert, update on table public.atlas_project_dependencies to service_role;
    grant select, insert on table public.atlas_project_activity_log to service_role;
    grant usage, select on sequence public.atlas_project_activity_log_id_seq to service_role;
    grant execute on function public.post_atlas_project_update(text, text, text, text, text) to service_role;
    grant execute on function public.assign_atlas_action_to_project(text, text, text, integer, text) to service_role;
    grant execute on function public.remove_atlas_action_from_project(text, text, text) to service_role;
    revoke delete, truncate on table public.atlas_projects from service_role;
    revoke delete, truncate on table public.atlas_project_milestones from service_role;
    revoke update, delete, truncate on table public.atlas_project_updates from service_role;
    revoke delete, truncate on table public.atlas_project_dependencies from service_role;
    revoke update, delete, truncate on table public.atlas_project_activity_log from service_role;
  end if;
end
$migration$;

comment on table public.atlas_projects is
  'Owner-only ATLAS project aggregates. Archive through status transitions; never delete.';
comment on table public.atlas_project_updates is
  'Append-only structured ATLAS project health reports.';
comment on column public.atlas_actions.estimate_points is
  'Non-negative project effort. Null counts as one point in ATLAS project progress.';
