-- Linear parity slice 3: repeating ATLAS cycles, capacity, live scope events,
-- immutable completion snapshots, action assignment, and rollover.

create table if not exists public.atlas_cycle_schedules (
  id text primary key,
  business text,
  enabled boolean not null default true,
  duration_weeks integer not null default 2 check (duration_weeks between 1 and 8),
  cooldown_days integer not null default 0 check (cooldown_days in (0, 7, 14)),
  future_cycles integer not null default 3 check (future_cycles between 1 and 15),
  start_date date not null,
  timezone text not null default 'America/Los_Angeles',
  auto_rollover boolean not null default true,
  auto_add_started boolean not null default false,
  revision bigint not null default 0 check (revision >= 0),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists atlas_cycle_schedules_business_idx
  on public.atlas_cycle_schedules (coalesce(business, '__workspace__'))
  where enabled;

create table if not exists public.atlas_cycles (
  id text primary key,
  schedule_id text not null references public.atlas_cycle_schedules(id) on delete restrict,
  cycle_number integer not null check (cycle_number > 0),
  name text not null,
  start_date date not null,
  end_date date not null,
  status text not null default 'planned'
    check (status in ('planned', 'active', 'completed', 'archived')),
  capacity_override integer check (capacity_override is null or capacity_override >= 0),
  scope_effort_snapshot integer,
  started_effort_snapshot integer,
  completed_effort_snapshot integer,
  success_percent_snapshot numeric(6,2),
  action_snapshot jsonb,
  completed_at timestamptz,
  revision bigint not null default 0 check (revision >= 0),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (schedule_id, cycle_number),
  check (start_date <= end_date),
  check (
    status <> 'completed'
    or (scope_effort_snapshot is not null and completed_effort_snapshot is not null and success_percent_snapshot is not null and action_snapshot is not null and completed_at is not null)
  )
);

create index if not exists atlas_cycles_schedule_status_dates_idx
  on public.atlas_cycles (schedule_id, status, start_date, end_date);
create unique index if not exists atlas_cycles_one_active_schedule_idx
  on public.atlas_cycles (schedule_id)
  where status = 'active';

create table if not exists public.atlas_cycle_scope_events (
  id bigint generated by default as identity primary key,
  cycle_id text not null references public.atlas_cycles(id) on delete restrict,
  event_type text not null,
  action_id text,
  scope_effort integer not null,
  started_effort integer not null,
  completed_effort integer not null,
  issue_count integer not null,
  completed_count integer not null,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists atlas_cycle_scope_events_cycle_created_idx
  on public.atlas_cycle_scope_events (cycle_id, created_at, id);

create table if not exists public.atlas_cycle_activity_log (
  id bigint generated by default as identity primary key,
  cycle_id text,
  schedule_id text,
  event text not null,
  old_value jsonb,
  new_value jsonb,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now()),
  check (cycle_id is not null or schedule_id is not null)
);

create index if not exists atlas_cycle_activity_cycle_created_idx
  on public.atlas_cycle_activity_log (cycle_id, created_at desc);
create index if not exists atlas_cycle_activity_schedule_created_idx
  on public.atlas_cycle_activity_log (schedule_id, created_at desc);

alter table public.atlas_actions add column if not exists cycle_id text;

do $migration$
begin
  if not exists (select 1 from pg_constraint where conname = 'atlas_actions_cycle_id_fkey') then
    alter table public.atlas_actions
      add constraint atlas_actions_cycle_id_fkey
      foreign key (cycle_id) references public.atlas_cycles(id) on delete restrict;
  end if;
end
$migration$;

create index if not exists atlas_actions_cycle_status_idx
  on public.atlas_actions (cycle_id, status);

create or replace function public.atlas_protect_completed_cycle_snapshot()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if old.status = 'completed' and (
    new.schedule_id is distinct from old.schedule_id
    or new.cycle_number is distinct from old.cycle_number
    or new.start_date is distinct from old.start_date
    or new.end_date is distinct from old.end_date
    or new.scope_effort_snapshot is distinct from old.scope_effort_snapshot
    or new.started_effort_snapshot is distinct from old.started_effort_snapshot
    or new.completed_effort_snapshot is distinct from old.completed_effort_snapshot
    or new.success_percent_snapshot is distinct from old.success_percent_snapshot
    or new.action_snapshot is distinct from old.action_snapshot
    or new.completed_at is distinct from old.completed_at
  ) then
    raise exception using errcode = '55000', message = 'ATLAS_CYCLE_SNAPSHOT_IMMUTABLE';
  end if;
  return new;
end
$function$;

create or replace function public.atlas_audit_cycle_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_cycle_activity_log (cycle_id, schedule_id, event, old_value, new_value, actor)
  values (
    new.id, new.schedule_id,
    case
      when tg_op = 'INSERT' then 'cycle_created'
      when new.status = 'completed' and old.status <> 'completed' then 'cycle_completed'
      when new.status = 'active' and old.status <> 'active' then 'cycle_started'
      when new.status = 'archived' and old.status <> 'archived' then 'cycle_archived'
      else 'cycle_updated'
    end,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new),
    case when tg_op = 'INSERT' then new.created_by else new.updated_by end
  );
  return new;
end
$function$;

create or replace function public.atlas_audit_cycle_schedule_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_cycle_activity_log (schedule_id, event, old_value, new_value, actor)
  values (
    new.id,
    case when tg_op = 'INSERT' then 'schedule_created' else 'schedule_updated' end,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new),
    case when tg_op = 'INSERT' then new.created_by else new.updated_by end
  );
  return new;
end
$function$;

revoke all on function public.atlas_protect_completed_cycle_snapshot() from public;
revoke all on function public.atlas_audit_cycle_row() from public;
revoke all on function public.atlas_audit_cycle_schedule_row() from public;

drop trigger if exists atlas_cycles_protect_snapshot on public.atlas_cycles;
create trigger atlas_cycles_protect_snapshot
before update on public.atlas_cycles
for each row execute function public.atlas_protect_completed_cycle_snapshot();

drop trigger if exists atlas_cycles_audit_row on public.atlas_cycles;
create trigger atlas_cycles_audit_row
after insert or update on public.atlas_cycles
for each row execute function public.atlas_audit_cycle_row();

drop trigger if exists atlas_cycle_schedules_audit_row on public.atlas_cycle_schedules;
create trigger atlas_cycle_schedules_audit_row
after insert or update on public.atlas_cycle_schedules
for each row execute function public.atlas_audit_cycle_schedule_row();

create or replace function public.atlas_capture_cycle_scope(
  p_cycle_id text,
  p_event_type text,
  p_action_id text,
  p_actor text
)
returns void
language plpgsql
set search_path = ''
as $function$
declare
  unestimated_value integer := 1;
  cycle_status text;
  scope_effort integer;
  started_effort integer;
  completed_effort integer;
  issue_count integer;
  completed_count integer;
begin
  select status into cycle_status from public.atlas_cycles where id = p_cycle_id;
  if cycle_status not in ('planned', 'active') then return; end if;
  select coalesce((value->>'unestimated_value')::integer, 1)
    into unestimated_value
    from public.atlas_config where key = 'estimate_settings';
  unestimated_value := coalesce(unestimated_value, 1);

  select
    coalesce(sum(coalesce(action.estimate_points, unestimated_value)), 0)::integer,
    coalesce(sum(case when action.status in ('in_progress', 'waiting', 'blocked') then coalesce(action.estimate_points, unestimated_value) else 0 end), 0)::integer,
    coalesce(sum(case when action.status in ('done', 'completed', 'closed') then coalesce(action.estimate_points, unestimated_value) else 0 end), 0)::integer,
    count(*)::integer,
    count(*) filter (where action.status in ('done', 'completed', 'closed'))::integer
  into scope_effort, started_effort, completed_effort, issue_count, completed_count
  from public.atlas_actions action where action.cycle_id = p_cycle_id;

  insert into public.atlas_cycle_scope_events (
    cycle_id, event_type, action_id, scope_effort, started_effort,
    completed_effort, issue_count, completed_count, actor
  ) values (
    p_cycle_id, p_event_type, p_action_id, scope_effort, started_effort,
    completed_effort, issue_count, completed_count, p_actor
  );
end
$function$;

create or replace function public.atlas_capture_action_cycle_change()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if tg_op = 'UPDATE' and old.cycle_id is not null and old.cycle_id is distinct from new.cycle_id then
    perform public.atlas_capture_cycle_scope(old.cycle_id, 'scope_removed', new.id, 'system');
  end if;
  if new.cycle_id is not null then
    perform public.atlas_capture_cycle_scope(
      new.cycle_id,
      case
        when tg_op = 'INSERT' or old.cycle_id is distinct from new.cycle_id then 'scope_added'
        when old.status is distinct from new.status then 'status_changed'
        else 'estimate_changed'
      end,
      new.id,
      'system'
    );
  end if;
  return new;
end
$function$;

revoke all on function public.atlas_capture_cycle_scope(text, text, text, text) from public;
revoke all on function public.atlas_capture_action_cycle_change() from public;

drop trigger if exists atlas_actions_capture_cycle_scope on public.atlas_actions;
create trigger atlas_actions_capture_cycle_scope
after insert or update of cycle_id, status, estimate_points on public.atlas_actions
for each row execute function public.atlas_capture_action_cycle_change();

create or replace function public.configure_atlas_cycle_schedule(
  p_schedule_id text,
  p_business text,
  p_duration_weeks integer,
  p_cooldown_days integer,
  p_future_cycles integer,
  p_start_date date,
  p_timezone text,
  p_auto_rollover boolean,
  p_auto_add_started boolean,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  schedule_row public.atlas_cycle_schedules%rowtype;
  active_row public.atlas_cycles%rowtype;
  cycle_row public.atlas_cycles%rowtype;
  next_start date;
  next_end date;
  next_number integer;
  cycle_status text;
  generated jsonb := '[]'::jsonb;
  index_value integer;
  server_timestamp timestamptz := timezone('utc', now());
begin
  if p_actor <> 'ransomed' then raise exception using errcode = '42501', message = 'ATLAS_OWNER_REQUIRED'; end if;
  if p_duration_weeks not between 1 and 8 then raise exception using errcode = '22023', message = 'ATLAS_CYCLE_DURATION_INVALID'; end if;
  if p_cooldown_days not in (0, 7, 14) then raise exception using errcode = '22023', message = 'ATLAS_CYCLE_COOLDOWN_INVALID'; end if;
  if p_future_cycles not between 1 and 15 then raise exception using errcode = '22023', message = 'ATLAS_CYCLE_FUTURE_COUNT_INVALID'; end if;
  if p_start_date is null then raise exception using errcode = '22023', message = 'ATLAS_CYCLE_START_REQUIRED'; end if;

  select * into schedule_row from public.atlas_cycle_schedules where id = p_schedule_id for update;
  if found then
    if p_expected_revision is not null and schedule_row.revision <> p_expected_revision then
      raise exception using errcode = '40001', message = 'ATLAS_CYCLE_REVISION_CONFLICT';
    end if;
    update public.atlas_cycle_schedules set
      business = p_business, enabled = true, duration_weeks = p_duration_weeks,
      cooldown_days = p_cooldown_days, future_cycles = p_future_cycles,
      start_date = p_start_date, timezone = coalesce(nullif(p_timezone, ''), 'America/Los_Angeles'),
      auto_rollover = p_auto_rollover, auto_add_started = p_auto_add_started,
      revision = revision + 1, updated_by = p_actor, updated_at = server_timestamp
    where id = p_schedule_id returning * into schedule_row;
    update public.atlas_cycles set status = 'archived', revision = revision + 1,
      updated_by = p_actor, updated_at = server_timestamp
    where schedule_id = p_schedule_id and status = 'planned';
  else
    insert into public.atlas_cycle_schedules (
      id, business, enabled, duration_weeks, cooldown_days, future_cycles,
      start_date, timezone, auto_rollover, auto_add_started, created_by, updated_by
    ) values (
      p_schedule_id, p_business, true, p_duration_weeks, p_cooldown_days,
      p_future_cycles, p_start_date, coalesce(nullif(p_timezone, ''), 'America/Los_Angeles'),
      p_auto_rollover, p_auto_add_started, p_actor, p_actor
    ) returning * into schedule_row;
  end if;

  select * into active_row from public.atlas_cycles
   where schedule_id = p_schedule_id and status = 'active'
   order by start_date desc limit 1 for update;
  select coalesce(max(cycle_number), 0) + 1 into next_number
    from public.atlas_cycles where schedule_id = p_schedule_id;

  if active_row.id is not null then
    next_start := active_row.end_date + schedule_row.cooldown_days + 1;
  else
    next_start := p_start_date;
    while next_start + (p_duration_weeks * 7 - 1) < current_date loop
      next_end := next_start + (p_duration_weeks * 7 - 1);
      insert into public.atlas_cycles (
        id, schedule_id, cycle_number, name, start_date, end_date, status,
        scope_effort_snapshot, started_effort_snapshot, completed_effort_snapshot,
        success_percent_snapshot, action_snapshot, completed_at, created_by, updated_by
      ) values (
        gen_random_uuid()::text, p_schedule_id, next_number, format('Cycle %s', next_number),
        next_start, next_end, 'completed', 0, 0, 0, 0, '[]'::jsonb,
        server_timestamp, p_actor, p_actor
      ) returning * into cycle_row;
      generated := generated || to_jsonb(cycle_row);
      next_number := next_number + 1;
      next_start := next_end + p_cooldown_days + 1;
    end loop;
  end if;

  for index_value in 0..(case when active_row.id is not null then p_future_cycles - 1 else p_future_cycles end) loop
    next_end := next_start + (p_duration_weeks * 7 - 1);
    cycle_status := case when current_date between next_start and next_end then 'active' else 'planned' end;
    insert into public.atlas_cycles (
      id, schedule_id, cycle_number, name, start_date, end_date, status,
      created_by, updated_by
    ) values (
      gen_random_uuid()::text, p_schedule_id, next_number, format('Cycle %s', next_number),
      next_start, next_end, cycle_status, p_actor, p_actor
    ) returning * into cycle_row;
    generated := generated || to_jsonb(cycle_row);
    next_number := next_number + 1;
    next_start := next_end + p_cooldown_days + 1;
  end loop;

  return jsonb_build_object('schedule', to_jsonb(schedule_row), 'cycles', generated);
end
$function$;

create or replace function public.assign_atlas_action_to_cycle(
  p_cycle_id text,
  p_action_id text,
  p_actor text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  cycle_row public.atlas_cycles%rowtype;
  action_row public.atlas_actions%rowtype;
  old_cycle_id text;
  schedule_business text;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into cycle_row from public.atlas_cycles where id = p_cycle_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_CYCLE_NOT_FOUND'; end if;
  if cycle_row.status not in ('planned', 'active') then raise exception using errcode = '55000', message = 'ATLAS_CYCLE_NOT_ASSIGNABLE'; end if;
  select * into action_row from public.atlas_actions where id = p_action_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_ACTION_NOT_FOUND'; end if;
  if action_row.status = 'archived' then raise exception using errcode = '55000', message = 'ATLAS_ACTION_ARCHIVED'; end if;
  select business into schedule_business from public.atlas_cycle_schedules where id = cycle_row.schedule_id;
  if schedule_business is not null and action_row.business is distinct from schedule_business then
    raise exception using errcode = '23514', message = 'ATLAS_CYCLE_ACTION_BUSINESS_MISMATCH';
  end if;
  old_cycle_id := action_row.cycle_id;
  update public.atlas_actions set cycle_id = p_cycle_id, updated_at = timezone('utc', now())
   where id = p_action_id returning * into action_row;
  insert into public.atlas_activity_log (action_id, event, old_value, new_value, actor)
  values (p_action_id, 'cycle_assigned', old_cycle_id, p_cycle_id, p_actor);
  insert into public.atlas_cycle_activity_log (cycle_id, schedule_id, event, old_value, new_value, actor)
  values (p_cycle_id, cycle_row.schedule_id, 'action_assigned', jsonb_build_object('cycle_id', old_cycle_id), jsonb_build_object('action_id', p_action_id), p_actor);
  return to_jsonb(action_row);
end
$function$;

create or replace function public.remove_atlas_action_from_cycle(
  p_cycle_id text,
  p_action_id text,
  p_actor text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  action_row public.atlas_actions%rowtype;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into action_row from public.atlas_actions where id = p_action_id and cycle_id = p_cycle_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_CYCLE_ACTION_NOT_FOUND'; end if;
  update public.atlas_actions set cycle_id = null, updated_at = timezone('utc', now())
   where id = p_action_id returning * into action_row;
  insert into public.atlas_activity_log (action_id, event, old_value, new_value, actor)
  values (p_action_id, 'cycle_removed', p_cycle_id, null, p_actor);
  insert into public.atlas_cycle_activity_log (cycle_id, event, old_value, new_value, actor)
  values (p_cycle_id, 'action_removed', jsonb_build_object('action_id', p_action_id), null, p_actor);
  return to_jsonb(action_row);
end
$function$;

create or replace function public.complete_atlas_cycle(
  p_cycle_id text,
  p_actor text,
  p_expected_revision bigint default null,
  p_start_next_now boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  cycle_row public.atlas_cycles%rowtype;
  next_cycle public.atlas_cycles%rowtype;
  schedule_row public.atlas_cycle_schedules%rowtype;
  unestimated_value integer := 1;
  scope_effort integer;
  started_effort integer;
  completed_effort integer;
  success_percent numeric(6,2);
  snapshot jsonb;
  rolled_count integer := 0;
  server_timestamp timestamptz := timezone('utc', now());
begin
  if p_actor <> 'ransomed' then raise exception using errcode = '42501', message = 'ATLAS_OWNER_REQUIRED'; end if;
  select * into cycle_row from public.atlas_cycles where id = p_cycle_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_CYCLE_NOT_FOUND'; end if;
  if cycle_row.status <> 'active' then raise exception using errcode = '22023', message = 'ATLAS_CYCLE_NOT_ACTIVE'; end if;
  if p_expected_revision is not null and cycle_row.revision <> p_expected_revision then raise exception using errcode = '40001', message = 'ATLAS_CYCLE_REVISION_CONFLICT'; end if;
  select * into schedule_row from public.atlas_cycle_schedules where id = cycle_row.schedule_id for update;
  select coalesce((value->>'unestimated_value')::integer, 1) into unestimated_value
    from public.atlas_config where key = 'estimate_settings';
  unestimated_value := coalesce(unestimated_value, 1);

  select
    coalesce(sum(coalesce(estimate_points, unestimated_value)), 0)::integer,
    coalesce(sum(case when status in ('in_progress', 'waiting', 'blocked') then coalesce(estimate_points, unestimated_value) else 0 end), 0)::integer,
    coalesce(sum(case when status in ('done', 'completed', 'closed') then coalesce(estimate_points, unestimated_value) else 0 end), 0)::integer,
    coalesce(jsonb_agg(jsonb_build_object('id', id, 'status', status, 'estimate_points', estimate_points) order by id), '[]'::jsonb)
  into scope_effort, started_effort, completed_effort, snapshot
  from public.atlas_actions where cycle_id = p_cycle_id;
  success_percent := case when scope_effort = 0 then 0 else round(((completed_effort + started_effort * 0.25) / scope_effort::numeric) * 100, 2) end;

  select * into next_cycle from public.atlas_cycles
   where schedule_id = cycle_row.schedule_id and status = 'planned'
   order by start_date asc limit 1 for update;
  if next_cycle.id is null then
    insert into public.atlas_cycles (id, schedule_id, cycle_number, name, start_date, end_date, status, created_by, updated_by)
    values (
      gen_random_uuid()::text, cycle_row.schedule_id, cycle_row.cycle_number + 1,
      format('Cycle %s', cycle_row.cycle_number + 1),
      cycle_row.end_date + schedule_row.cooldown_days + 1,
      cycle_row.end_date + schedule_row.cooldown_days + schedule_row.duration_weeks * 7,
      'planned', p_actor, p_actor
    ) returning * into next_cycle;
  end if;

  update public.atlas_cycles set status = 'completed',
    scope_effort_snapshot = scope_effort, started_effort_snapshot = started_effort,
    completed_effort_snapshot = completed_effort, success_percent_snapshot = success_percent,
    action_snapshot = snapshot, completed_at = server_timestamp,
    revision = revision + 1, updated_by = p_actor, updated_at = server_timestamp
  where id = p_cycle_id returning * into cycle_row;

  if p_start_next_now then
    update public.atlas_cycles set start_date = current_date,
      end_date = current_date + (schedule_row.duration_weeks * 7 - 1),
      status = 'active', revision = revision + 1, updated_by = p_actor, updated_at = server_timestamp
    where id = next_cycle.id returning * into next_cycle;
    with future as (
      select id, row_number() over (order by cycle_number)::integer as position
      from public.atlas_cycles
      where schedule_id = cycle_row.schedule_id and status = 'planned' and id <> next_cycle.id
    )
    update public.atlas_cycles cycle
       set start_date = next_cycle.end_date + schedule_row.cooldown_days + 1
           + ((future.position - 1) * (schedule_row.duration_weeks * 7 + schedule_row.cooldown_days)),
           end_date = next_cycle.end_date + schedule_row.cooldown_days
           + ((future.position - 1) * (schedule_row.duration_weeks * 7 + schedule_row.cooldown_days))
           + schedule_row.duration_weeks * 7,
           revision = cycle.revision + 1,
           updated_by = p_actor,
           updated_at = server_timestamp
      from future
     where cycle.id = future.id;
  elsif next_cycle.start_date <= current_date then
    update public.atlas_cycles set status = 'active', revision = revision + 1,
      updated_by = p_actor, updated_at = server_timestamp
    where id = next_cycle.id returning * into next_cycle;
  end if;

  if schedule_row.auto_rollover then
    update public.atlas_actions set cycle_id = next_cycle.id, updated_at = server_timestamp
     where cycle_id = p_cycle_id
       and status in ('not_started', 'in_progress', 'waiting', 'blocked', 'todo', 'open');
    get diagnostics rolled_count = row_count;
  end if;
  insert into public.atlas_cycle_activity_log (cycle_id, schedule_id, event, old_value, new_value, actor)
  values (
    p_cycle_id, cycle_row.schedule_id, 'cycle_rollover_completed', null,
    jsonb_build_object('next_cycle_id', next_cycle.id, 'rolled_actions', rolled_count, 'success_percent', success_percent), p_actor
  );
  return jsonb_build_object('cycle', to_jsonb(cycle_row), 'next_cycle', to_jsonb(next_cycle), 'rolled_actions', rolled_count);
end
$function$;

create or replace function public.disable_atlas_cycle_schedule(
  p_schedule_id text,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  schedule_row public.atlas_cycle_schedules%rowtype;
  cycle_row public.atlas_cycles%rowtype;
  unestimated_value integer := 1;
  scope_effort integer;
  started_effort integer;
  completed_effort integer;
  success_percent numeric(6,2);
  snapshot jsonb;
  server_timestamp timestamptz := timezone('utc', now());
begin
  if p_actor <> 'ransomed' then raise exception using errcode = '42501', message = 'ATLAS_OWNER_REQUIRED'; end if;
  select * into schedule_row from public.atlas_cycle_schedules where id = p_schedule_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_CYCLE_SCHEDULE_NOT_FOUND'; end if;
  if p_expected_revision is not null and schedule_row.revision <> p_expected_revision then raise exception using errcode = '40001', message = 'ATLAS_CYCLE_REVISION_CONFLICT'; end if;
  select * into cycle_row from public.atlas_cycles where schedule_id = p_schedule_id and status = 'active' order by start_date desc limit 1 for update;
  if cycle_row.id is not null then
    select coalesce((value->>'unestimated_value')::integer, 1) into unestimated_value from public.atlas_config where key = 'estimate_settings';
    unestimated_value := coalesce(unestimated_value, 1);
    select
      coalesce(sum(coalesce(estimate_points, unestimated_value)), 0)::integer,
      coalesce(sum(case when status in ('in_progress','waiting','blocked') then coalesce(estimate_points, unestimated_value) else 0 end), 0)::integer,
      coalesce(sum(case when status in ('done','completed','closed') then coalesce(estimate_points, unestimated_value) else 0 end), 0)::integer,
      coalesce(jsonb_agg(jsonb_build_object('id',id,'status',status,'estimate_points',estimate_points) order by id), '[]'::jsonb)
    into scope_effort, started_effort, completed_effort, snapshot
    from public.atlas_actions where cycle_id = cycle_row.id;
    success_percent := case when scope_effort = 0 then 0 else round(((completed_effort + started_effort * 0.25) / scope_effort::numeric) * 100, 2) end;
    update public.atlas_cycles set status = 'completed', scope_effort_snapshot = scope_effort,
      started_effort_snapshot = started_effort, completed_effort_snapshot = completed_effort,
      success_percent_snapshot = success_percent, action_snapshot = snapshot,
      completed_at = server_timestamp, revision = revision + 1,
      updated_by = p_actor, updated_at = server_timestamp
    where id = cycle_row.id returning * into cycle_row;
  end if;
  update public.atlas_cycles set status = 'archived', revision = revision + 1,
    updated_by = p_actor, updated_at = server_timestamp
  where schedule_id = p_schedule_id and status = 'planned';
  update public.atlas_cycle_schedules set enabled = false, revision = revision + 1,
    updated_by = p_actor, updated_at = server_timestamp
  where id = p_schedule_id returning * into schedule_row;
  return jsonb_build_object('schedule', to_jsonb(schedule_row), 'completed_cycle', case when cycle_row.id is null then null else to_jsonb(cycle_row) end);
end
$function$;

create or replace function public.atlas_auto_add_action_to_cycle()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  target_cycle_id text;
begin
  if new.cycle_id is not null or new.status not in ('in_progress', 'waiting', 'blocked', 'done', 'completed', 'closed') then return new; end if;
  select cycle.id into target_cycle_id
    from public.atlas_cycles cycle
    join public.atlas_cycle_schedules schedule on schedule.id = cycle.schedule_id
   where schedule.enabled and schedule.auto_add_started and cycle.status = 'active'
     and (schedule.business = new.business or schedule.business is null)
   order by (schedule.business = new.business) desc, cycle.start_date desc
   limit 1;
  if target_cycle_id is null and new.status in ('done', 'completed', 'closed') then
    select cycle.id into target_cycle_id
      from public.atlas_cycles cycle
      join public.atlas_cycle_schedules schedule on schedule.id = cycle.schedule_id
     where schedule.enabled and schedule.auto_add_started and cycle.status = 'completed'
       and (schedule.business = new.business or schedule.business is null)
       and current_date <= cycle.end_date + schedule.cooldown_days
     order by cycle.end_date desc limit 1;
  end if;
  if target_cycle_id is not null then
    update public.atlas_actions set cycle_id = target_cycle_id, updated_at = timezone('utc', now()) where id = new.id;
  end if;
  return new;
end
$function$;

revoke all on function public.configure_atlas_cycle_schedule(text, text, integer, integer, integer, date, text, boolean, boolean, text, bigint) from public;
revoke all on function public.assign_atlas_action_to_cycle(text, text, text) from public;
revoke all on function public.remove_atlas_action_from_cycle(text, text, text) from public;
revoke all on function public.complete_atlas_cycle(text, text, bigint, boolean) from public;
revoke all on function public.disable_atlas_cycle_schedule(text, text, bigint) from public;
revoke all on function public.atlas_auto_add_action_to_cycle() from public;

drop trigger if exists atlas_actions_auto_add_cycle on public.atlas_actions;
create trigger atlas_actions_auto_add_cycle
after insert or update of status on public.atlas_actions
for each row execute function public.atlas_auto_add_action_to_cycle();

alter table public.atlas_cycle_schedules enable row level security;
alter table public.atlas_cycles enable row level security;
alter table public.atlas_cycle_scope_events enable row level security;
alter table public.atlas_cycle_activity_log enable row level security;

revoke all on table public.atlas_cycle_schedules from public;
revoke all on table public.atlas_cycles from public;
revoke all on table public.atlas_cycle_scope_events from public;
revoke all on table public.atlas_cycle_activity_log from public;

drop trigger if exists atlas_cycle_schedules_reject_delete on public.atlas_cycle_schedules;
create trigger atlas_cycle_schedules_reject_delete before delete on public.atlas_cycle_schedules
for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_cycles_reject_delete on public.atlas_cycles;
create trigger atlas_cycles_reject_delete before delete on public.atlas_cycles
for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_cycle_scope_events_reject_mutation on public.atlas_cycle_scope_events;
create trigger atlas_cycle_scope_events_reject_mutation before update or delete on public.atlas_cycle_scope_events
for each row execute function public.atlas_reject_project_history_mutation();
drop trigger if exists atlas_cycle_activity_reject_mutation on public.atlas_cycle_activity_log;
create trigger atlas_cycle_activity_reject_mutation before update or delete on public.atlas_cycle_activity_log
for each row execute function public.atlas_reject_project_history_mutation();

do $migration$
declare
  role_name text;
  function_signature text;
begin
  foreach role_name in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = role_name) then
      execute format('revoke all on table public.atlas_cycle_schedules from %I', role_name);
      execute format('revoke all on table public.atlas_cycles from %I', role_name);
      execute format('revoke all on table public.atlas_cycle_scope_events from %I', role_name);
      execute format('revoke all on table public.atlas_cycle_activity_log from %I', role_name);
    end if;
  end loop;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant select, insert, update on public.atlas_cycle_schedules to service_role;
    grant select, insert, update on public.atlas_cycles to service_role;
    grant select, insert on public.atlas_cycle_scope_events to service_role;
    grant select, insert on public.atlas_cycle_activity_log to service_role;
    grant usage, select on sequence public.atlas_cycle_scope_events_id_seq to service_role;
    grant usage, select on sequence public.atlas_cycle_activity_log_id_seq to service_role;
    revoke delete, truncate on table public.atlas_cycle_schedules from service_role;
    revoke delete, truncate on table public.atlas_cycles from service_role;
    revoke update, delete, truncate on table public.atlas_cycle_scope_events from service_role;
    revoke update, delete, truncate on table public.atlas_cycle_activity_log from service_role;
  end if;
  foreach function_signature in array array[
    'public.configure_atlas_cycle_schedule(text,text,integer,integer,integer,date,text,boolean,boolean,text,bigint)',
    'public.assign_atlas_action_to_cycle(text,text,text)',
    'public.remove_atlas_action_from_cycle(text,text,text)',
    'public.complete_atlas_cycle(text,text,bigint,boolean)'
    ,'public.disable_atlas_cycle_schedule(text,text,bigint)'
  ] loop
    foreach role_name in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = role_name) then
        execute format('revoke execute on function %s from %I', function_signature, role_name);
      end if;
    end loop;
    if exists (select 1 from pg_roles where rolname = 'service_role') then
      execute format('grant execute on function %s to service_role', function_signature);
    end if;
  end loop;
end
$migration$;

comment on table public.atlas_cycles is
  'Generated ATLAS execution cycles with immutable completion snapshots.';
