-- Linear parity slice 4: typed durable views, project micro-order,
-- completion windows, and dependency-aware timeline movement.

alter table public.atlas_projects
  add column if not exists sort_order numeric(30,10) not null default 0,
  add column if not exists completed_at timestamptz;

with ranked as (
  select id, row_number() over (
    order by case priority when 'p0' then 0 when 'p1' then 1 when 'p2' then 2 when 'p3' then 3 else 4 end,
             created_at, id
  ) * 1000 as rank_value
  from public.atlas_projects
)
update public.atlas_projects project
set sort_order = ranked.rank_value
from ranked
where project.id = ranked.id and project.sort_order = 0;

update public.atlas_projects
set completed_at = coalesce(completed_at, updated_at)
where status = 'completed' and completed_at is null;

create or replace function public.atlas_manage_project_completion_timestamp()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if new.status = 'completed' and old.status <> 'completed' then
    new.completed_at := coalesce(new.completed_at, timezone('utc', now()));
  elsif old.status = 'completed' and new.status <> 'completed' then
    new.completed_at := null;
  end if;
  return new;
end
$function$;

revoke all on function public.atlas_manage_project_completion_timestamp() from public;
drop trigger if exists atlas_projects_manage_completed_at on public.atlas_projects;
create trigger atlas_projects_manage_completed_at
before update of status on public.atlas_projects
for each row execute function public.atlas_manage_project_completion_timestamp();

alter table public.atlas_saved_views
  add column if not exists entity_type text not null default 'action',
  add column if not exists context_project_id text,
  add column if not exists layout text not null default 'list',
  add column if not exists group_by text,
  add column if not exists subgroup_by text,
  add column if not exists display_options jsonb not null default '{}'::jsonb,
  add column if not exists is_favorite boolean not null default false,
  add column if not exists is_default boolean not null default false,
  add column if not exists archived_at timestamptz,
  add column if not exists revision bigint not null default 0,
  add column if not exists created_by text not null default 'ransomed',
  add column if not exists updated_by text not null default 'ransomed';

do $migration$
begin
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_entity_type_check') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_entity_type_check
      check (entity_type in ('action', 'project'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_layout_check') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_layout_check
      check (layout in ('list', 'board', 'timeline'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_timeline_entity_check') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_timeline_entity_check
      check (layout <> 'timeline' or entity_type = 'project');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_sort_dir_check') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_sort_dir_check
      check (sort_dir in ('asc', 'desc'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_context_project_id_fkey') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_context_project_id_fkey
      foreign key (context_project_id) references public.atlas_projects(id) on delete restrict;
  end if;
end
$migration$;

update public.atlas_saved_views
set entity_type = 'action', layout = 'list', display_options = '{}'::jsonb
where entity_type is null or layout is null or display_options is null;

create unique index if not exists atlas_saved_views_one_default_idx
  on public.atlas_saved_views (entity_type, coalesce(context_project_id, '__workspace__'))
  where is_default and archived_at is null;
create index if not exists atlas_saved_views_entity_context_idx
  on public.atlas_saved_views (entity_type, context_project_id, is_favorite, name)
  where archived_at is null;
create index if not exists atlas_saved_views_context_project_idx
  on public.atlas_saved_views (context_project_id)
  where context_project_id is not null;

create table if not exists public.atlas_saved_view_activity_log (
  id bigint generated by default as identity primary key,
  view_id text not null references public.atlas_saved_views(id) on delete restrict,
  event text not null,
  old_value jsonb,
  new_value jsonb,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists atlas_saved_view_activity_view_created_idx
  on public.atlas_saved_view_activity_log (view_id, created_at desc);

create or replace function public.atlas_audit_saved_view_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_saved_view_activity_log (view_id, event, old_value, new_value, actor)
  values (
    new.id,
    case
      when tg_op = 'INSERT' then 'view_created'
      when new.archived_at is not null and old.archived_at is null then 'view_archived'
      when new.archived_at is null and old.archived_at is not null then 'view_restored'
      when new.is_favorite is distinct from old.is_favorite then 'view_favorite_changed'
      else 'view_updated'
    end,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new),
    case when tg_op = 'INSERT' then new.created_by else new.updated_by end
  );
  return new;
end
$function$;

revoke all on function public.atlas_audit_saved_view_row() from public;
drop trigger if exists atlas_saved_views_audit_row on public.atlas_saved_views;
create trigger atlas_saved_views_audit_row
after insert or update on public.atlas_saved_views
for each row execute function public.atlas_audit_saved_view_row();

drop trigger if exists atlas_saved_views_reject_delete on public.atlas_saved_views;
create trigger atlas_saved_views_reject_delete
before delete on public.atlas_saved_views
for each row execute function public.atlas_reject_immutable_delete();

drop trigger if exists atlas_saved_view_activity_reject_mutation on public.atlas_saved_view_activity_log;
create trigger atlas_saved_view_activity_reject_mutation
before update or delete on public.atlas_saved_view_activity_log
for each row execute function public.atlas_reject_project_history_mutation();

alter table public.atlas_saved_view_activity_log enable row level security;
alter table public.atlas_saved_views enable row level security;
revoke all on table public.atlas_saved_view_activity_log from public;
revoke delete, truncate on table public.atlas_saved_views from public;

create or replace function public.move_atlas_project_order(
  p_project_id text,
  p_before_project_id text,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  project_row public.atlas_projects%rowtype;
  target_order numeric;
  previous_order numeric;
  new_order numeric;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into project_row from public.atlas_projects where id = p_project_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_PROJECT_NOT_FOUND'; end if;
  if p_expected_revision is not null and project_row.revision <> p_expected_revision then raise exception using errcode = '40001', message = 'ATLAS_PROJECT_REVISION_CONFLICT'; end if;
  if p_before_project_id is null then
    select coalesce(max(sort_order), 0) + 1000 into new_order from public.atlas_projects where id <> p_project_id;
  else
    select sort_order into target_order from public.atlas_projects where id = p_before_project_id for update;
    if not found then raise exception using errcode = 'P0002', message = 'ATLAS_PROJECT_REFERENCE_NOT_FOUND'; end if;
    select max(sort_order) into previous_order from public.atlas_projects
     where id not in (p_project_id, p_before_project_id) and sort_order < target_order;
    new_order := case when previous_order is null then target_order - 1000 else (previous_order + target_order) / 2 end;
  end if;
  update public.atlas_projects set sort_order = new_order, revision = revision + 1,
    updated_by = p_actor, updated_at = timezone('utc', now())
  where id = p_project_id returning * into project_row;
  return to_jsonb(project_row);
end
$function$;

create or replace function public.move_atlas_project_timeline(
  p_project_id text,
  p_start_date date,
  p_target_date date,
  p_shift_dependency_chain boolean,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  project_row public.atlas_projects%rowtype;
  delta_days integer := 0;
  moved_ids jsonb := '[]'::jsonb;
  dependent record;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  if p_start_date is not null and p_target_date is not null and p_start_date > p_target_date then raise exception using errcode = '22023', message = 'ATLAS_PROJECT_TIMEFRAME_INVALID'; end if;
  select * into project_row from public.atlas_projects where id = p_project_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_PROJECT_NOT_FOUND'; end if;
  if project_row.status = 'archived' then raise exception using errcode = '55000', message = 'ATLAS_PROJECT_ARCHIVED'; end if;
  if p_expected_revision is not null and project_row.revision <> p_expected_revision then raise exception using errcode = '40001', message = 'ATLAS_PROJECT_REVISION_CONFLICT'; end if;
  if project_row.start_date is not null and p_start_date is not null then delta_days := p_start_date - project_row.start_date; end if;
  update public.atlas_projects set start_date = p_start_date, target_date = p_target_date,
    revision = revision + 1, updated_by = p_actor, updated_at = timezone('utc', now())
  where id = p_project_id returning * into project_row;
  moved_ids := moved_ids || to_jsonb(project_row.id);

  if p_shift_dependency_chain and delta_days <> 0 then
    for dependent in
      with recursive chain(project_id) as (
        select dependency.blocked_project_id
        from public.atlas_project_dependencies dependency
        where dependency.blocking_project_id = p_project_id and dependency.status = 'active'
        union
        select dependency.blocked_project_id
        from public.atlas_project_dependencies dependency
        join chain on dependency.blocking_project_id = chain.project_id
        where dependency.status = 'active'
      )
      select project.id from public.atlas_projects project
      join chain on chain.project_id = project.id
      where project.status in ('backlog', 'planned')
      for update
    loop
      update public.atlas_projects set
        start_date = case when start_date is null then null else start_date + delta_days end,
        target_date = case when target_date is null then null else target_date + delta_days end,
        revision = revision + 1, updated_by = p_actor, updated_at = timezone('utc', now())
      where id = dependent.id;
      moved_ids := moved_ids || to_jsonb(dependent.id);
    end loop;
  end if;
  return jsonb_build_object('project', to_jsonb(project_row), 'moved_project_ids', moved_ids, 'delta_days', delta_days);
end
$function$;

revoke all on function public.move_atlas_project_order(text, text, text, bigint) from public;
revoke all on function public.move_atlas_project_timeline(text, date, date, boolean, text, bigint) from public;

do $migration$
declare
  role_name text;
  function_signature text;
begin
  foreach role_name in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = role_name) then
      execute format('revoke all on table public.atlas_saved_view_activity_log from %I', role_name);
      execute format('revoke delete, truncate on table public.atlas_saved_views from %I', role_name);
    end if;
  end loop;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant select, insert on public.atlas_saved_view_activity_log to service_role;
    grant usage, select on sequence public.atlas_saved_view_activity_log_id_seq to service_role;
    revoke update, delete, truncate on public.atlas_saved_view_activity_log from service_role;
    revoke delete, truncate on public.atlas_saved_views from service_role;
  end if;
  foreach function_signature in array array[
    'public.move_atlas_project_order(text,text,text,bigint)',
    'public.move_atlas_project_timeline(text,date,date,boolean,text,bigint)'
  ] loop
    foreach role_name in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = role_name) then execute format('revoke execute on function %s from %I', function_signature, role_name); end if;
    end loop;
    if exists (select 1 from pg_roles where rolname = 'service_role') then execute format('grant execute on function %s to service_role', function_signature); end if;
  end loop;
end
$migration$;

comment on table public.atlas_saved_views is
  'Typed, revisioned, archivable saved views for ATLAS actions and projects.';
