-- Linear parity completion: stable action identifiers, automatic text
-- references, hierarchy completion policy, parent-to-project conversion, and
-- explicit cycle start-today lifecycle.

create sequence if not exists public.atlas_action_display_number_seq;

alter table public.atlas_actions
  add column if not exists display_number bigint,
  add column if not exists identifier text;

alter table public.atlas_actions
  alter column display_number set default nextval('public.atlas_action_display_number_seq');

update public.atlas_actions
set display_number = nextval('public.atlas_action_display_number_seq')
where display_number is null;

update public.atlas_actions
set identifier = 'ATLAS-' || display_number::text
where identifier is null;

select setval(
  'public.atlas_action_display_number_seq',
  coalesce((select max(display_number) + 1 from public.atlas_actions), 1),
  false
);

alter sequence public.atlas_action_display_number_seq owned by public.atlas_actions.display_number;
alter table public.atlas_actions alter column display_number set not null;
alter table public.atlas_actions alter column identifier set not null;
create unique index if not exists atlas_actions_display_number_idx on public.atlas_actions(display_number);
create unique index if not exists atlas_actions_identifier_idx on public.atlas_actions(identifier);

create or replace function public.atlas_assign_action_identifier()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if tg_op = 'UPDATE' and (
    new.display_number is distinct from old.display_number
    or new.identifier is distinct from old.identifier
  ) then
    raise exception using errcode = '55000', message = 'ATLAS_ACTION_IDENTIFIER_IMMUTABLE';
  end if;
  if new.display_number is null then
    new.display_number := nextval('public.atlas_action_display_number_seq');
  end if;
  new.identifier := 'ATLAS-' || new.display_number::text;
  return new;
end
$function$;

drop trigger if exists atlas_actions_assign_identifier on public.atlas_actions;
create trigger atlas_actions_assign_identifier
before insert or update of display_number, identifier on public.atlas_actions
for each row execute function public.atlas_assign_action_identifier();

alter table public.atlas_workflows
  add column if not exists parent_auto_close boolean not null default false,
  add column if not exists sub_action_auto_close boolean not null default false;

create table if not exists public.atlas_hierarchy_automation_events (
  id bigint generated by default as identity primary key,
  workflow_id uuid references public.atlas_workflows(id) on delete restrict,
  source_action_id text not null references public.atlas_actions(id) on delete restrict,
  affected_action_id text not null references public.atlas_actions(id) on delete restrict,
  event text not null check (event in ('parent_auto_closed','sub_action_auto_closed')),
  actor text not null default 'system',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists atlas_hierarchy_automation_source_idx
  on public.atlas_hierarchy_automation_events(source_action_id, created_at desc);
create index if not exists atlas_hierarchy_automation_affected_idx
  on public.atlas_hierarchy_automation_events(affected_action_id, created_at desc);

create or replace function public.atlas_apply_hierarchy_completion_policy()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  workflow_row public.atlas_workflows%rowtype;
  parent_row public.atlas_actions%rowtype;
  child_id text;
  server_timestamp timestamptz := timezone('utc', now());
begin
  if new.status not in ('done','completed','closed')
     or old.status in ('done','completed','closed') then
    return new;
  end if;

  select * into workflow_row
    from public.atlas_workflows
   where archived_at is null
     and (business is not distinct from new.business or business is null)
   order by (business is not distinct from new.business) desc, created_at
   limit 1;

  if workflow_row.id is null then return new; end if;

  if workflow_row.parent_auto_close and new.parent_action_id is not null then
    update public.atlas_actions parent
       set status = 'done', resolution = 'completed', revision = parent.revision + 1,
           evidence_json = jsonb_build_object(
             'version', 2, 'kind', 'hierarchy_automation',
             'summary', 'Completed automatically after all direct sub-actions completed.',
             'source_action_id', new.id,
             'verification', jsonb_build_object('status', 'system_recorded')
           ),
           updated_at = server_timestamp
     where parent.id = new.parent_action_id
       and parent.status not in ('done','completed','closed','archived','cancelled','canceled')
       and coalesce(parent.work_mode, 'autonomous') <> 'user_only'
       and coalesce(parent.approval_state, 'not_required') not in ('needs_review','deferred')
       and exists (select 1 from public.atlas_actions child where child.parent_action_id = parent.id)
       and not exists (
         select 1 from public.atlas_actions child
          where child.parent_action_id = parent.id
            and child.status not in ('done','completed','closed','archived','cancelled','canceled')
       )
     returning parent.* into parent_row;
    if parent_row.id is not null then
      insert into public.atlas_hierarchy_automation_events(workflow_id,source_action_id,affected_action_id,event)
      values(workflow_row.id,new.id,parent_row.id,'parent_auto_closed');
      insert into public.atlas_activity_log(action_id,event,new_value,actor,created_at)
      values(parent_row.id,'parent_auto_closed',new.id,'system',server_timestamp);
    end if;
  end if;

  if workflow_row.sub_action_auto_close then
    for child_id in
      update public.atlas_actions child
         set status = 'done', resolution = 'completed', revision = child.revision + 1,
             evidence_json = jsonb_build_object(
               'version', 2, 'kind', 'hierarchy_automation',
               'summary', 'Completed automatically with the parent action.',
               'source_action_id', new.id,
               'verification', jsonb_build_object('status', 'system_recorded')
             ),
             updated_at = server_timestamp
       where child.parent_action_id = new.id
         and child.status not in ('done','completed','closed','archived','cancelled','canceled')
         and coalesce(child.work_mode, 'autonomous') <> 'user_only'
         and coalesce(child.approval_state, 'not_required') not in ('needs_review','deferred')
       returning child.id
    loop
      insert into public.atlas_hierarchy_automation_events(workflow_id,source_action_id,affected_action_id,event)
      values(workflow_row.id,new.id,child_id,'sub_action_auto_closed');
      insert into public.atlas_activity_log(action_id,event,new_value,actor,created_at)
      values(child_id,'sub_action_auto_closed',new.id,'system',server_timestamp);
    end loop;
  end if;
  return new;
end
$function$;

drop trigger if exists atlas_actions_apply_hierarchy_completion_policy on public.atlas_actions;
create trigger atlas_actions_apply_hierarchy_completion_policy
after update of status on public.atlas_actions
for each row execute function public.atlas_apply_hierarchy_completion_policy();

create table if not exists public.atlas_action_project_conversions (
  id text primary key,
  source_action_id text not null references public.atlas_actions(id) on delete restrict,
  project_id text not null references public.atlas_projects(id) on delete restrict,
  source_action_snapshot jsonb not null,
  child_action_ids jsonb not null default '[]'::jsonb check (jsonb_typeof(child_action_ids)='array'),
  actor text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique(source_action_id)
);

create or replace function public.convert_atlas_action_to_project(
  p_action_id text,
  p_project_id text,
  p_project_name text,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  action_row public.atlas_actions%rowtype;
  project_row public.atlas_projects%rowtype;
  conversion_row public.atlas_action_project_conversions%rowtype;
  child_ids jsonb;
  source_snapshot jsonb;
  resolved_name text;
  server_timestamp timestamptz := timezone('utc', now());
begin
  if p_actor <> 'ransomed' then raise exception using errcode='42501',message='ATLAS_OWNER_REQUIRED'; end if;
  select * into action_row from public.atlas_actions where id=p_action_id for update;
  if not found then raise exception using errcode='P0002',message='ATLAS_ACTION_NOT_FOUND'; end if;
  if action_row.status='archived' then raise exception using errcode='55000',message='ATLAS_ACTION_ARCHIVED'; end if;
  if p_expected_revision is not null and action_row.revision<>p_expected_revision then raise exception using errcode='40001',message='ATLAS_REVISION_CONFLICT'; end if;
  source_snapshot := to_jsonb(action_row);
  if not exists(select 1 from public.atlas_actions where parent_action_id=p_action_id) then
    raise exception using errcode='55000',message='ATLAS_PARENT_ACTION_REQUIRED';
  end if;
  if exists(select 1 from public.atlas_action_project_conversions where source_action_id=p_action_id) then
    select * into conversion_row from public.atlas_action_project_conversions where source_action_id=p_action_id;
    select * into project_row from public.atlas_projects where id=conversion_row.project_id;
    return jsonb_build_object('project',to_jsonb(project_row),'conversion',to_jsonb(conversion_row),'idempotent',true);
  end if;

  perform 1 from public.atlas_actions where parent_action_id=p_action_id order by id for update;
  select coalesce(jsonb_agg(id order by id),'[]'::jsonb) into child_ids
    from public.atlas_actions where parent_action_id=p_action_id;
  resolved_name := coalesce(nullif(btrim(p_project_name),''),action_row.title);

  insert into public.atlas_projects(
    id,name,summary,description,business,status,health,priority,lead_id,members,
    start_date,target_date,update_frequency,created_by,updated_by,created_at,updated_at
  ) values(
    p_project_id,resolved_name,left(coalesce(action_row.description,''),500),coalesce(action_row.description,''),
    action_row.business,'planned','no_update',action_row.priority,
    case when coalesce(action_row.owners,'[]'::jsonb) ? 'ransomed' then 'ransomed' else null end,
    coalesce(action_row.owners,'[]'::jsonb),current_date,
    case when action_row.due_date ~ '^\d{4}-\d{2}-\d{2}$' then action_row.due_date::date else null end,
    'weekly',p_actor,p_actor,server_timestamp,server_timestamp
  ) returning * into project_row;

  update public.atlas_actions
     set project_id=p_project_id,project_milestone_id=null,parent_action_id=null,
         updated_at=server_timestamp
   where parent_action_id=p_action_id;

  update public.atlas_actions
     set title=left(action_row.title || ' (project issue)',500),project_id=p_project_id,
         project_milestone_id=null,parent_action_id=null,revision=revision+1,updated_at=server_timestamp
   where id=p_action_id returning * into action_row;

  insert into public.atlas_action_project_conversions(
    id,source_action_id,project_id,source_action_snapshot,child_action_ids,actor,created_at
  ) values(gen_random_uuid()::text,p_action_id,p_project_id,source_snapshot,child_ids,p_actor,server_timestamp)
  returning * into conversion_row;

  insert into public.atlas_project_activity_log(project_id,event,new_value,actor,created_at)
  values(p_project_id,'created_from_parent_action',jsonb_build_object('source_action_id',p_action_id,'child_action_ids',child_ids),p_actor,server_timestamp);
  insert into public.atlas_activity_log(action_id,event,new_value,actor,created_at)
  values(p_action_id,'converted_to_project',p_project_id,p_actor,server_timestamp);
  return jsonb_build_object('project',to_jsonb(project_row),'action',to_jsonb(action_row),'conversion',to_jsonb(conversion_row),'idempotent',false);
end
$function$;

create table if not exists public.atlas_text_references (
  id text primary key,
  source_type text not null check(source_type in ('action','project','document','comment')),
  source_id text not null,
  source_field text not null,
  target_action_id text not null references public.atlas_actions(id) on delete restrict,
  matched_identifier text not null,
  status text not null default 'active' check(status in ('active','stale')),
  revision bigint not null default 0 check(revision>=0),
  first_seen_at timestamptz not null default timezone('utc',now()),
  last_seen_at timestamptz not null default timezone('utc',now()),
  unique(source_type,source_id,source_field,target_action_id)
);

create index if not exists atlas_text_references_target_idx
  on public.atlas_text_references(target_action_id,status,last_seen_at desc);
create index if not exists atlas_text_references_source_idx
  on public.atlas_text_references(source_type,source_id,status,last_seen_at desc);

create table if not exists public.atlas_text_reference_events (
  id bigint generated by default as identity primary key,
  reference_id text not null references public.atlas_text_references(id) on delete restrict,
  event text not null check(event in ('detected','reactivated','stale')),
  snapshot jsonb not null,
  created_at timestamptz not null default timezone('utc',now())
);

create or replace function public.atlas_audit_text_reference()
returns trigger
language plpgsql
set search_path=''
as $function$
begin
  if tg_op='INSERT' then
    insert into public.atlas_text_reference_events(reference_id,event,snapshot) values(new.id,'detected',to_jsonb(new));
  elsif new.status is distinct from old.status then
    insert into public.atlas_text_reference_events(reference_id,event,snapshot)
    values(new.id,case when new.status='active' then 'reactivated' else 'stale' end,to_jsonb(new));
  end if;
  return new;
end
$function$;

drop trigger if exists atlas_text_references_audit on public.atlas_text_references;
create trigger atlas_text_references_audit
after insert or update on public.atlas_text_references
for each row execute function public.atlas_audit_text_reference();

create or replace function public.atlas_sync_text_references()
returns trigger
language plpgsql
set search_path=''
as $function$
declare
  source_type_value text := tg_argv[0];
  source_id_value text;
  field_name text;
  field_value text;
  combined_value text := '';
  captured_number bigint;
  target_row public.atlas_actions%rowtype;
  relation_row public.atlas_action_relations%rowtype;
  canonical_source text;
  canonical_target text;
  source_active boolean := true;
  server_timestamp timestamptz := timezone('utc',now());
begin
  source_id_value := to_jsonb(new)->>'id';
  if to_jsonb(new) ? 'status' then source_active := coalesce(to_jsonb(new)->>'status','active') <> 'archived'; end if;
  foreach field_name in array tg_argv[1:array_length(tg_argv,1)] loop
    field_value := coalesce(to_jsonb(new)->>field_name,'');
    combined_value := combined_value || E'\n' || field_value;
  end loop;

  update public.atlas_text_references
     set status='stale',revision=revision+1,last_seen_at=server_timestamp
   where source_type=source_type_value and source_id=source_id_value and status='active';

  if source_active then
    for captured_number in
      select distinct captures[1]::bigint
        from regexp_matches(combined_value,'(?i)(?:@)?ATLAS-([0-9]+)','g') captures
    loop
      select * into target_row from public.atlas_actions where display_number=captured_number;
      if target_row.id is null or (source_type_value='action' and target_row.id=source_id_value) then continue; end if;
      field_name := case
        when position(lower(target_row.identifier) in lower(coalesce(to_jsonb(new)->>'title',''))) > 0 then 'title'
        when position(lower(target_row.identifier) in lower(coalesce(to_jsonb(new)->>'description',''))) > 0 then 'description'
        when position(lower(target_row.identifier) in lower(coalesce(to_jsonb(new)->>'notes',''))) > 0 then 'notes'
        when position(lower(target_row.identifier) in lower(coalesce(to_jsonb(new)->>'summary',''))) > 0 then 'summary'
        when position(lower(target_row.identifier) in lower(coalesce(to_jsonb(new)->>'content',''))) > 0 then 'content'
        else tg_argv[1]
      end;
      insert into public.atlas_text_references(id,source_type,source_id,source_field,target_action_id,matched_identifier,status)
      values(gen_random_uuid()::text,source_type_value,source_id_value,field_name,target_row.id,target_row.identifier,'active')
      on conflict(source_type,source_id,source_field,target_action_id) do update
        set status='active',revision=public.atlas_text_references.revision+1,last_seen_at=server_timestamp,
            matched_identifier=excluded.matched_identifier;

      if source_type_value='action' then
        canonical_source := least(source_id_value,target_row.id);
        canonical_target := greatest(source_id_value,target_row.id);
        update public.atlas_action_relations
           set status='active',revision=revision+1,updated_by='system',updated_at=server_timestamp
         where source_action_id=canonical_source and target_action_id=canonical_target
           and relation_type='related' and note='auto:text_reference' and status<>'active'
           and not exists(
             select 1 from public.atlas_action_relations active_relation
              where active_relation.source_action_id=canonical_source and active_relation.target_action_id=canonical_target
                and active_relation.relation_type='related' and active_relation.status='active'
           );
        if not found then
          insert into public.atlas_action_relations(id,source_action_id,target_action_id,relation_type,status,note,created_by,updated_by)
          values(gen_random_uuid()::text,canonical_source,canonical_target,'related','active','auto:text_reference','system','system')
          on conflict do nothing;
        end if;
      end if;
    end loop;
  end if;

  if source_type_value='action' then
    for relation_row in
      select * from public.atlas_action_relations
       where note='auto:text_reference' and relation_type='related' and status='active'
         and source_id_value in (source_action_id,target_action_id)
    loop
      if not exists(
        select 1 from public.atlas_text_references reference
         where reference.source_type='action' and reference.status='active'
           and ((reference.source_id=relation_row.source_action_id and reference.target_action_id=relation_row.target_action_id)
             or (reference.source_id=relation_row.target_action_id and reference.target_action_id=relation_row.source_action_id))
      ) then
        update public.atlas_action_relations set status='archived',revision=revision+1,updated_by='system',updated_at=server_timestamp
         where id=relation_row.id;
      end if;
    end loop;
  end if;
  return new;
end
$function$;

drop trigger if exists atlas_actions_sync_text_references on public.atlas_actions;
create trigger atlas_actions_sync_text_references after insert or update of title,description,notes on public.atlas_actions
for each row execute function public.atlas_sync_text_references('action','title','description','notes');
drop trigger if exists atlas_projects_sync_text_references on public.atlas_projects;
create trigger atlas_projects_sync_text_references after insert or update of name,summary,description,status on public.atlas_projects
for each row execute function public.atlas_sync_text_references('project','name','summary','description');
drop trigger if exists atlas_documents_sync_text_references on public.atlas_documents;
create trigger atlas_documents_sync_text_references after insert or update of title,content,status on public.atlas_documents
for each row execute function public.atlas_sync_text_references('document','title','content');
drop trigger if exists atlas_comments_sync_text_references on public.atlas_comments;
create trigger atlas_comments_sync_text_references after insert or update of body,status on public.atlas_comments
for each row execute function public.atlas_sync_text_references('comment','body');

create or replace function public.start_atlas_cycle_today(
  p_cycle_id text,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  cycle_row public.atlas_cycles%rowtype;
  active_row public.atlas_cycles%rowtype;
  schedule_row public.atlas_cycle_schedules%rowtype;
  result jsonb;
  server_timestamp timestamptz := timezone('utc',now());
begin
  if p_actor<>'ransomed' then raise exception using errcode='42501',message='ATLAS_OWNER_REQUIRED'; end if;
  select * into cycle_row from public.atlas_cycles where id=p_cycle_id for update;
  if not found then raise exception using errcode='P0002',message='ATLAS_CYCLE_NOT_FOUND'; end if;
  if cycle_row.status<>'planned' then raise exception using errcode='55000',message='ATLAS_CYCLE_NOT_PLANNED'; end if;
  if p_expected_revision is not null and cycle_row.revision<>p_expected_revision then raise exception using errcode='40001',message='ATLAS_CYCLE_REVISION_CONFLICT'; end if;
  select * into schedule_row from public.atlas_cycle_schedules where id=cycle_row.schedule_id for update;
  if exists(select 1 from public.atlas_cycles earlier where earlier.schedule_id=cycle_row.schedule_id and earlier.status='planned' and earlier.start_date<cycle_row.start_date) then
    raise exception using errcode='55000',message='ATLAS_NEXT_PLANNED_CYCLE_REQUIRED';
  end if;
  select * into active_row from public.atlas_cycles where schedule_id=cycle_row.schedule_id and status='active' limit 1 for update;
  if active_row.id is not null then
    return public.complete_atlas_cycle(active_row.id,p_actor,active_row.revision,true);
  end if;
  update public.atlas_cycles
     set start_date=current_date,end_date=current_date+(schedule_row.duration_weeks*7-1),status='active',
         revision=revision+1,updated_by=p_actor,updated_at=server_timestamp
   where id=p_cycle_id returning * into cycle_row;
  with future as(
    select id,row_number() over(order by cycle_number)::integer as position
      from public.atlas_cycles where schedule_id=cycle_row.schedule_id and status='planned'
  )
  update public.atlas_cycles future_cycle
     set start_date=cycle_row.end_date+schedule_row.cooldown_days+1+((future.position-1)*(schedule_row.duration_weeks*7+schedule_row.cooldown_days)),
         end_date=cycle_row.end_date+schedule_row.cooldown_days+((future.position-1)*(schedule_row.duration_weeks*7+schedule_row.cooldown_days))+schedule_row.duration_weeks*7,
         revision=future_cycle.revision+1,updated_by=p_actor,updated_at=server_timestamp
    from future where future_cycle.id=future.id;
  insert into public.atlas_cycle_activity_log(cycle_id,schedule_id,event,new_value,actor,created_at)
  values(cycle_row.id,cycle_row.schedule_id,'cycle_started_today',to_jsonb(cycle_row),p_actor,server_timestamp);
  return jsonb_build_object('cycle',to_jsonb(cycle_row),'started_today',true);
end
$function$;

create or replace function public.atlas_reject_core_convenience_history_mutation()
returns trigger language plpgsql set search_path='' as $function$
begin raise exception using errcode='55000',message='ATLAS_CORE_CONVENIENCE_HISTORY_IMMUTABLE'; end
$function$;

do $migration$
declare table_name text; role_name text;
begin
  foreach table_name in array array[
    'atlas_hierarchy_automation_events','atlas_action_project_conversions',
    'atlas_text_references','atlas_text_reference_events'
  ] loop
    execute format('alter table public.%I enable row level security',table_name);
    execute format('revoke all on table public.%I from public',table_name);
    foreach role_name in array array['anon','authenticated'] loop
      if exists(select 1 from pg_roles where rolname=role_name) then execute format('revoke all on table public.%I from %I',table_name,role_name); end if;
    end loop;
  end loop;
  if exists(select 1 from pg_roles where rolname='service_role') then
    grant select,insert on table public.atlas_hierarchy_automation_events,public.atlas_action_project_conversions,public.atlas_text_reference_events to service_role;
    grant select,insert,update on table public.atlas_text_references to service_role;
    grant usage,select on sequence public.atlas_action_display_number_seq,public.atlas_hierarchy_automation_events_id_seq,public.atlas_text_reference_events_id_seq to service_role;
  end if;
end
$migration$;

drop trigger if exists atlas_hierarchy_automation_events_immutable on public.atlas_hierarchy_automation_events;
create trigger atlas_hierarchy_automation_events_immutable before update or delete on public.atlas_hierarchy_automation_events for each row execute function public.atlas_reject_core_convenience_history_mutation();
drop trigger if exists atlas_action_project_conversions_immutable on public.atlas_action_project_conversions;
create trigger atlas_action_project_conversions_immutable before update or delete on public.atlas_action_project_conversions for each row execute function public.atlas_reject_core_convenience_history_mutation();
drop trigger if exists atlas_text_reference_events_immutable on public.atlas_text_reference_events;
create trigger atlas_text_reference_events_immutable before update or delete on public.atlas_text_reference_events for each row execute function public.atlas_reject_core_convenience_history_mutation();
drop trigger if exists atlas_text_references_no_delete on public.atlas_text_references;
create trigger atlas_text_references_no_delete before delete on public.atlas_text_references for each row execute function public.atlas_reject_core_convenience_history_mutation();

revoke all on function public.convert_atlas_action_to_project(text,text,text,text,bigint) from public;
revoke all on function public.start_atlas_cycle_today(text,text,bigint) from public;
do $migration$
declare role_name text;
begin
  foreach role_name in array array['anon','authenticated'] loop
    if exists(select 1 from pg_roles where rolname=role_name) then
      execute format('revoke execute on function public.convert_atlas_action_to_project(text,text,text,text,bigint) from %I',role_name);
      execute format('revoke execute on function public.start_atlas_cycle_today(text,text,bigint) from %I',role_name);
    end if;
  end loop;
  if exists(select 1 from pg_roles where rolname='service_role') then
    grant execute on function public.convert_atlas_action_to_project(text,text,text,text,bigint) to service_role;
    grant execute on function public.start_atlas_cycle_today(text,text,bigint) to service_role;
  end if;
end
$migration$;

comment on column public.atlas_actions.identifier is 'Immutable human-readable action reference such as ATLAS-42.';
comment on table public.atlas_text_references is 'Durable automatic references and backlinks discovered in Atlas text fields.';
comment on function public.convert_atlas_action_to_project(text,text,text,text,bigint) is 'Owner-only transactional conversion of a parent action and its direct children into a project.';
