-- Linear parity slice 5: strategic initiatives, multi-parent hierarchy,
-- project rollups, structured updates, resources, graph inputs, and views.

create table if not exists public.atlas_initiatives (
  id text primary key,
  name text not null,
  summary text not null default '',
  description text not null default '',
  business text,
  status text not null default 'planned'
    check (status in ('proposed', 'planned', 'active', 'completed', 'canceled', 'archived')),
  health text not null default 'no_update'
    check (health in ('on_track', 'at_risk', 'off_track', 'no_update')),
  priority text check (priority is null or priority in ('p0', 'p1', 'p2', 'p3')),
  owner_id text references public.atlas_members(id),
  labels jsonb not null default '[]'::jsonb check (jsonb_typeof(labels) = 'array'),
  start_date date,
  target_date date,
  color text,
  icon text,
  update_frequency text not null default 'weekly'
    check (update_frequency in ('daily', 'weekly', 'biweekly', 'monthly', 'never')),
  sort_order numeric(30,10) not null default 0,
  completed_at timestamptz,
  archived_from_status text,
  revision bigint not null default 0 check (revision >= 0),
  created_by text not null default 'system',
  updated_by text not null default 'system',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (start_date is null or target_date is null or start_date <= target_date)
);

create table if not exists public.atlas_initiative_projects (
  id text primary key,
  initiative_id text not null references public.atlas_initiatives(id) on delete restrict,
  project_id text not null references public.atlas_projects(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists atlas_initiative_projects_active_pair_idx
  on public.atlas_initiative_projects (initiative_id, project_id) where status = 'active';
create index if not exists atlas_initiative_projects_project_idx
  on public.atlas_initiative_projects (project_id, initiative_id) where status = 'active';

create table if not exists public.atlas_initiative_relations (
  id text primary key,
  parent_initiative_id text not null references public.atlas_initiatives(id) on delete restrict,
  child_initiative_id text not null references public.atlas_initiatives(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (parent_initiative_id <> child_initiative_id)
);

create unique index if not exists atlas_initiative_relations_active_pair_idx
  on public.atlas_initiative_relations (parent_initiative_id, child_initiative_id) where status = 'active';
create index if not exists atlas_initiative_relations_child_idx
  on public.atlas_initiative_relations (child_initiative_id, parent_initiative_id) where status = 'active';

create table if not exists public.atlas_initiative_updates (
  id text primary key,
  initiative_id text not null references public.atlas_initiatives(id) on delete restrict,
  health text not null check (health in ('on_track', 'at_risk', 'off_track')),
  body text not null,
  context_snapshot jsonb not null default '{}'::jsonb,
  created_by text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.atlas_initiative_resources (
  id text primary key,
  initiative_id text not null references public.atlas_initiatives(id) on delete restrict,
  resource_type text not null default 'link' check (resource_type in ('link', 'document')),
  title text not null,
  url text,
  document_ref text,
  status text not null default 'active' check (status in ('active', 'archived')),
  revision bigint not null default 0 check (revision >= 0),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (
    (resource_type = 'link' and nullif(btrim(url), '') is not null)
    or (resource_type = 'document' and nullif(btrim(document_ref), '') is not null)
  )
);

create table if not exists public.atlas_initiative_activity_log (
  id bigint generated by default as identity primary key,
  initiative_id text not null references public.atlas_initiatives(id) on delete restrict,
  event text not null,
  old_value jsonb,
  new_value jsonb,
  actor text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists atlas_initiatives_status_target_idx
  on public.atlas_initiatives (status, target_date, sort_order);
create index if not exists atlas_initiatives_owner_status_idx
  on public.atlas_initiatives (owner_id, status);
create index if not exists atlas_initiative_updates_created_idx
  on public.atlas_initiative_updates (initiative_id, created_at desc);
create index if not exists atlas_initiative_resources_active_idx
  on public.atlas_initiative_resources (initiative_id, title) where status = 'active';
create index if not exists atlas_initiative_activity_created_idx
  on public.atlas_initiative_activity_log (initiative_id, created_at desc);

create or replace function public.atlas_manage_initiative_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  if new.owner_id is not null and new.owner_id not in ('ransomed', 'codex', 'claude') then
    raise exception using errcode = '23514', message = 'ATLAS_INITIATIVE_OWNER_NOT_ALLOWED';
  end if;
  if new.labels is null or jsonb_typeof(new.labels) <> 'array' then
    raise exception using errcode = '23514', message = 'ATLAS_INITIATIVE_LABELS_ARRAY_REQUIRED';
  end if;
  if tg_op = 'UPDATE' then
    if new.status = 'completed' and old.status <> 'completed' then
      new.completed_at := coalesce(new.completed_at, timezone('utc', now()));
    elsif old.status = 'completed' and new.status <> 'completed' then
      new.completed_at := null;
    end if;
  elsif new.status = 'completed' then
    new.completed_at := coalesce(new.completed_at, timezone('utc', now()));
  end if;
  return new;
end
$function$;

create or replace function public.atlas_audit_initiative_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  insert into public.atlas_initiative_activity_log (initiative_id, event, old_value, new_value, actor)
  values (
    new.id,
    case
      when tg_op = 'INSERT' then 'initiative_created'
      when new.status = 'archived' and old.status <> 'archived' then 'initiative_archived'
      when old.status = 'archived' and new.status <> 'archived' then 'initiative_restored'
      when new.health is distinct from old.health then 'initiative_health_changed'
      when new.status is distinct from old.status then 'initiative_status_changed'
      else 'initiative_updated'
    end,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new),
    case when tg_op = 'INSERT' then new.created_by else new.updated_by end
  );
  return new;
end
$function$;

create or replace function public.atlas_audit_initiative_child_row()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  target_initiative text;
  event_name text;
  event_actor text;
begin
  if tg_table_name = 'atlas_initiative_projects' then
    target_initiative := new.initiative_id;
    event_name := case when tg_op = 'INSERT' then 'project_attached' when new.status = 'archived' then 'project_detached' else 'project_membership_restored' end;
    event_actor := case when tg_op = 'INSERT' then new.created_by else new.updated_by end;
  elsif tg_table_name = 'atlas_initiative_relations' then
    target_initiative := new.parent_initiative_id;
    event_name := case when tg_op = 'INSERT' then 'sub_initiative_attached' when new.status = 'archived' then 'sub_initiative_detached' else 'sub_initiative_restored' end;
    event_actor := case when tg_op = 'INSERT' then new.created_by else new.updated_by end;
  else
    target_initiative := new.initiative_id;
    event_name := case when tg_op = 'INSERT' then 'resource_created' when new.status = 'archived' then 'resource_archived' else 'resource_updated' end;
    event_actor := case when tg_op = 'INSERT' then new.created_by else new.updated_by end;
  end if;
  insert into public.atlas_initiative_activity_log (initiative_id, event, old_value, new_value, actor)
  values (target_initiative, event_name, case when tg_op = 'INSERT' then null else to_jsonb(old) end, to_jsonb(new), event_actor);
  return new;
end
$function$;

revoke all on function public.atlas_manage_initiative_row() from public;
revoke all on function public.atlas_audit_initiative_row() from public;
revoke all on function public.atlas_audit_initiative_child_row() from public;

create trigger atlas_initiatives_manage_row before insert or update of status, owner_id, labels
  on public.atlas_initiatives for each row execute function public.atlas_manage_initiative_row();
create trigger atlas_initiatives_audit_row after insert or update
  on public.atlas_initiatives for each row execute function public.atlas_audit_initiative_row();
create trigger atlas_initiative_projects_audit_row after insert or update
  on public.atlas_initiative_projects for each row execute function public.atlas_audit_initiative_child_row();
create trigger atlas_initiative_relations_audit_row after insert or update
  on public.atlas_initiative_relations for each row execute function public.atlas_audit_initiative_child_row();
create trigger atlas_initiative_resources_audit_row after insert or update
  on public.atlas_initiative_resources for each row execute function public.atlas_audit_initiative_child_row();

create or replace function public.set_atlas_initiative_project(
  p_initiative_id text,
  p_project_id text,
  p_active boolean,
  p_actor text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  initiative_row public.atlas_initiatives%rowtype;
  membership_row public.atlas_initiative_projects%rowtype;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into initiative_row from public.atlas_initiatives where id = p_initiative_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_NOT_FOUND'; end if;
  if initiative_row.status = 'archived' then raise exception using errcode = '55000', message = 'ATLAS_INITIATIVE_ARCHIVED'; end if;
  if not exists (select 1 from public.atlas_projects where id = p_project_id and status <> 'archived') then
    raise exception using errcode = 'P0002', message = 'ATLAS_PROJECT_NOT_FOUND';
  end if;
  select * into membership_row from public.atlas_initiative_projects
   where initiative_id = p_initiative_id and project_id = p_project_id
   order by created_at desc limit 1 for update;
  if found then
    update public.atlas_initiative_projects set status = case when p_active then 'active' else 'archived' end,
      updated_by = p_actor, updated_at = timezone('utc', now()) where id = membership_row.id returning * into membership_row;
  elsif p_active then
    insert into public.atlas_initiative_projects (id, initiative_id, project_id, status, created_by, updated_by)
    values (gen_random_uuid()::text, p_initiative_id, p_project_id, 'active', p_actor, p_actor)
    returning * into membership_row;
  else
    raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_PROJECT_NOT_FOUND';
  end if;
  return to_jsonb(membership_row);
end
$function$;

create or replace function public.set_atlas_initiative_parent(
  p_child_initiative_id text,
  p_parent_initiative_id text,
  p_active boolean,
  p_actor text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  child_row public.atlas_initiatives%rowtype;
  parent_row public.atlas_initiatives%rowtype;
  relation_row public.atlas_initiative_relations%rowtype;
  ancestor_depth integer := 1;
  descendant_depth integer := 1;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  if p_child_initiative_id = p_parent_initiative_id then raise exception using errcode = '23514', message = 'ATLAS_INITIATIVE_SELF_PARENT'; end if;
  select * into child_row from public.atlas_initiatives where id = p_child_initiative_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_NOT_FOUND'; end if;
  select * into parent_row from public.atlas_initiatives where id = p_parent_initiative_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_PARENT_NOT_FOUND'; end if;
  if child_row.status = 'archived' or parent_row.status = 'archived' then raise exception using errcode = '55000', message = 'ATLAS_INITIATIVE_ARCHIVED'; end if;

  if p_active then
    if exists (
      with recursive descendants(id) as (
        select p_child_initiative_id
        union
        select relation.child_initiative_id from public.atlas_initiative_relations relation
        join descendants on relation.parent_initiative_id = descendants.id where relation.status = 'active'
      ) select 1 from descendants where id = p_parent_initiative_id
    ) then raise exception using errcode = '23514', message = 'ATLAS_INITIATIVE_CYCLE'; end if;

    with recursive ancestors(id, depth, path) as (
      select p_parent_initiative_id, 1, array[p_parent_initiative_id]
      union all
      select relation.parent_initiative_id, ancestors.depth + 1, ancestors.path || relation.parent_initiative_id
      from public.atlas_initiative_relations relation join ancestors on relation.child_initiative_id = ancestors.id
      where relation.status = 'active' and not relation.parent_initiative_id = any(ancestors.path)
    ) select coalesce(max(depth), 1) into ancestor_depth from ancestors;
    with recursive descendants(id, depth, path) as (
      select p_child_initiative_id, 1, array[p_child_initiative_id]
      union all
      select relation.child_initiative_id, descendants.depth + 1, descendants.path || relation.child_initiative_id
      from public.atlas_initiative_relations relation join descendants on relation.parent_initiative_id = descendants.id
      where relation.status = 'active' and not relation.child_initiative_id = any(descendants.path)
    ) select coalesce(max(depth), 1) into descendant_depth from descendants;
    if ancestor_depth + descendant_depth > 5 then raise exception using errcode = '23514', message = 'ATLAS_INITIATIVE_MAX_DEPTH'; end if;
  end if;

  select * into relation_row from public.atlas_initiative_relations
   where parent_initiative_id = p_parent_initiative_id and child_initiative_id = p_child_initiative_id
   order by created_at desc limit 1 for update;
  if found then
    update public.atlas_initiative_relations set status = case when p_active then 'active' else 'archived' end,
      updated_by = p_actor, updated_at = timezone('utc', now()) where id = relation_row.id returning * into relation_row;
  elsif p_active then
    insert into public.atlas_initiative_relations (id, parent_initiative_id, child_initiative_id, status, created_by, updated_by)
    values (gen_random_uuid()::text, p_parent_initiative_id, p_child_initiative_id, 'active', p_actor, p_actor)
    returning * into relation_row;
  else
    raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_RELATION_NOT_FOUND';
  end if;
  return to_jsonb(relation_row);
end
$function$;

create or replace function public.post_atlas_initiative_update(
  p_initiative_id text,
  p_update_id text,
  p_health text,
  p_body text,
  p_actor text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  initiative_row public.atlas_initiatives%rowtype;
  update_row public.atlas_initiative_updates%rowtype;
  snapshot jsonb;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  if p_health not in ('on_track', 'at_risk', 'off_track') then raise exception using errcode = '22023', message = 'ATLAS_INITIATIVE_UPDATE_HEALTH_INVALID'; end if;
  if nullif(btrim(p_body), '') is null then raise exception using errcode = '22023', message = 'ATLAS_INITIATIVE_UPDATE_BODY_REQUIRED'; end if;
  select * into initiative_row from public.atlas_initiatives where id = p_initiative_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_NOT_FOUND'; end if;
  if initiative_row.status = 'archived' then raise exception using errcode = '55000', message = 'ATLAS_INITIATIVE_ARCHIVED'; end if;
  with recursive tree(id) as (
    select p_initiative_id
    union
    select relation.child_initiative_id from public.atlas_initiative_relations relation
    join tree on relation.parent_initiative_id = tree.id where relation.status = 'active'
  ), projects as (
    select distinct membership.project_id from public.atlas_initiative_projects membership
    join tree on tree.id = membership.initiative_id where membership.status = 'active'
  )
  select jsonb_build_object(
    'status', initiative_row.status, 'owner_id', initiative_row.owner_id,
    'target_date', initiative_row.target_date, 'revision', initiative_row.revision,
    'projects', count(project.id),
    'project_health', jsonb_build_object(
      'on_track', count(*) filter (where project.health = 'on_track'),
      'at_risk', count(*) filter (where project.health = 'at_risk'),
      'off_track', count(*) filter (where project.health = 'off_track'),
      'no_update', count(*) filter (where project.health = 'no_update')
    )
  ) into snapshot from projects join public.atlas_projects project on project.id = projects.project_id;
  insert into public.atlas_initiative_updates (id, initiative_id, health, body, context_snapshot, created_by)
  values (p_update_id, p_initiative_id, p_health, btrim(p_body), coalesce(snapshot, '{}'::jsonb), p_actor)
  returning * into update_row;
  update public.atlas_initiatives set health = p_health, revision = revision + 1,
    updated_by = p_actor, updated_at = timezone('utc', now()) where id = p_initiative_id;
  insert into public.atlas_initiative_activity_log (initiative_id, event, new_value, actor)
  values (p_initiative_id, 'initiative_update_posted', to_jsonb(update_row), p_actor);
  return to_jsonb(update_row);
end
$function$;

create or replace function public.move_atlas_initiative_order(
  p_initiative_id text,
  p_before_initiative_id text,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  initiative_row public.atlas_initiatives%rowtype;
  target_order numeric;
  previous_order numeric;
  new_order numeric;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into initiative_row from public.atlas_initiatives where id = p_initiative_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_NOT_FOUND'; end if;
  if p_expected_revision is not null and initiative_row.revision <> p_expected_revision then raise exception using errcode = '40001', message = 'ATLAS_INITIATIVE_REVISION_CONFLICT'; end if;
  if p_before_initiative_id is null then
    select coalesce(max(sort_order), 0) + 1000 into new_order from public.atlas_initiatives where id <> p_initiative_id;
  else
    select sort_order into target_order from public.atlas_initiatives where id = p_before_initiative_id for update;
    if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_REFERENCE_NOT_FOUND'; end if;
    select max(sort_order) into previous_order from public.atlas_initiatives
      where id not in (p_initiative_id, p_before_initiative_id) and sort_order < target_order;
    new_order := case when previous_order is null then target_order - 1000 else (previous_order + target_order) / 2 end;
  end if;
  update public.atlas_initiatives set sort_order = new_order, revision = revision + 1,
    updated_by = p_actor, updated_at = timezone('utc', now()) where id = p_initiative_id returning * into initiative_row;
  return to_jsonb(initiative_row);
end
$function$;

create or replace function public.transition_atlas_initiative(
  p_initiative_id text,
  p_restore boolean,
  p_actor text,
  p_expected_revision bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  initiative_row public.atlas_initiatives%rowtype;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into initiative_row from public.atlas_initiatives where id = p_initiative_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_NOT_FOUND'; end if;
  if initiative_row.revision <> p_expected_revision then raise exception using errcode = '40001', message = 'ATLAS_INITIATIVE_REVISION_CONFLICT'; end if;
  if p_restore then
    if initiative_row.status <> 'archived' then return to_jsonb(initiative_row); end if;
    update public.atlas_initiatives set status = coalesce(archived_from_status, 'planned'), archived_from_status = null,
      revision = revision + 1, updated_by = p_actor, updated_at = timezone('utc', now())
      where id = p_initiative_id returning * into initiative_row;
  else
    if initiative_row.status = 'archived' then return to_jsonb(initiative_row); end if;
    update public.atlas_initiatives set archived_from_status = status, status = 'archived',
      revision = revision + 1, updated_by = p_actor, updated_at = timezone('utc', now())
      where id = p_initiative_id returning * into initiative_row;
  end if;
  return to_jsonb(initiative_row);
end
$function$;

create or replace function public.upsert_atlas_initiative_resource(
  p_resource_id text,
  p_initiative_id text,
  p_resource_type text,
  p_title text,
  p_url text,
  p_document_ref text,
  p_status text,
  p_actor text,
  p_expected_revision bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  initiative_row public.atlas_initiatives%rowtype;
  resource_row public.atlas_initiative_resources%rowtype;
begin
  if p_actor not in ('ransomed', 'codex', 'claude') then raise exception using errcode = '22023', message = 'ATLAS_ACTOR_NOT_ALLOWED'; end if;
  if p_resource_type not in ('link', 'document') or p_status not in ('active', 'archived') then raise exception using errcode = '22023', message = 'ATLAS_INITIATIVE_RESOURCE_INVALID'; end if;
  if nullif(btrim(p_title), '') is null then raise exception using errcode = '22023', message = 'ATLAS_INITIATIVE_RESOURCE_TITLE_REQUIRED'; end if;
  select * into initiative_row from public.atlas_initiatives where id = p_initiative_id;
  if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_NOT_FOUND'; end if;
  if initiative_row.status = 'archived' then raise exception using errcode = '55000', message = 'ATLAS_INITIATIVE_ARCHIVED'; end if;
  if p_resource_id is null then
    insert into public.atlas_initiative_resources (id, initiative_id, resource_type, title, url, document_ref, status, created_by, updated_by)
    values (gen_random_uuid()::text, p_initiative_id, p_resource_type, btrim(p_title), p_url, p_document_ref, p_status, p_actor, p_actor)
    returning * into resource_row;
  else
    select * into resource_row from public.atlas_initiative_resources where id = p_resource_id and initiative_id = p_initiative_id for update;
    if not found then raise exception using errcode = 'P0002', message = 'ATLAS_INITIATIVE_RESOURCE_NOT_FOUND'; end if;
    if p_expected_revision is null or resource_row.revision <> p_expected_revision then raise exception using errcode = '40001', message = 'ATLAS_INITIATIVE_RESOURCE_REVISION_CONFLICT'; end if;
    update public.atlas_initiative_resources set resource_type = p_resource_type, title = btrim(p_title),
      url = p_url, document_ref = p_document_ref, status = p_status, revision = revision + 1,
      updated_by = p_actor, updated_at = timezone('utc', now()) where id = p_resource_id returning * into resource_row;
  end if;
  return to_jsonb(resource_row);
end
$function$;

do $migration$
begin
  alter table public.atlas_saved_views drop constraint if exists atlas_saved_views_entity_type_check;
  alter table public.atlas_saved_views add constraint atlas_saved_views_entity_type_check
    check (entity_type in ('action', 'project', 'initiative'));
  alter table public.atlas_saved_views drop constraint if exists atlas_saved_views_timeline_entity_check;
  alter table public.atlas_saved_views add constraint atlas_saved_views_timeline_entity_check
    check (layout <> 'timeline' or entity_type in ('project', 'initiative'));
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_initiative_layout_check') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_initiative_layout_check
      check (entity_type <> 'initiative' or layout in ('list', 'timeline'));
  end if;
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'atlas_saved_views' and column_name = 'context_initiative_id') then
    alter table public.atlas_saved_views add column context_initiative_id text;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_context_initiative_id_fkey') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_context_initiative_id_fkey
      foreign key (context_initiative_id) references public.atlas_initiatives(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atlas_saved_views_one_context_check') then
    alter table public.atlas_saved_views add constraint atlas_saved_views_one_context_check
      check (context_project_id is null or context_initiative_id is null);
  end if;
end
$migration$;

drop index if exists public.atlas_saved_views_one_default_idx;
create unique index atlas_saved_views_one_default_idx
  on public.atlas_saved_views (
    entity_type,
    coalesce(context_project_id, '__workspace_project__'),
    coalesce(context_initiative_id, '__workspace_initiative__')
  ) where is_default and archived_at is null;
create index if not exists atlas_saved_views_context_initiative_idx
  on public.atlas_saved_views (context_initiative_id) where context_initiative_id is not null;

drop trigger if exists atlas_initiatives_reject_delete on public.atlas_initiatives;
create trigger atlas_initiatives_reject_delete before delete on public.atlas_initiatives
  for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_initiative_projects_reject_delete on public.atlas_initiative_projects;
create trigger atlas_initiative_projects_reject_delete before delete on public.atlas_initiative_projects
  for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_initiative_relations_reject_delete on public.atlas_initiative_relations;
create trigger atlas_initiative_relations_reject_delete before delete on public.atlas_initiative_relations
  for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_initiative_resources_reject_delete on public.atlas_initiative_resources;
create trigger atlas_initiative_resources_reject_delete before delete on public.atlas_initiative_resources
  for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_initiative_updates_reject_mutation on public.atlas_initiative_updates;
create trigger atlas_initiative_updates_reject_mutation before update or delete on public.atlas_initiative_updates
  for each row execute function public.atlas_reject_project_history_mutation();
drop trigger if exists atlas_initiative_activity_reject_mutation on public.atlas_initiative_activity_log;
create trigger atlas_initiative_activity_reject_mutation before update or delete on public.atlas_initiative_activity_log
  for each row execute function public.atlas_reject_project_history_mutation();

alter table public.atlas_initiatives enable row level security;
alter table public.atlas_initiative_projects enable row level security;
alter table public.atlas_initiative_relations enable row level security;
alter table public.atlas_initiative_updates enable row level security;
alter table public.atlas_initiative_resources enable row level security;
alter table public.atlas_initiative_activity_log enable row level security;

revoke all on table public.atlas_initiatives, public.atlas_initiative_projects,
  public.atlas_initiative_relations, public.atlas_initiative_updates,
  public.atlas_initiative_resources, public.atlas_initiative_activity_log from public;
revoke all on function public.set_atlas_initiative_project(text,text,boolean,text) from public;
revoke all on function public.set_atlas_initiative_parent(text,text,boolean,text) from public;
revoke all on function public.post_atlas_initiative_update(text,text,text,text,text) from public;
revoke all on function public.move_atlas_initiative_order(text,text,text,bigint) from public;
revoke all on function public.transition_atlas_initiative(text,boolean,text,bigint) from public;
revoke all on function public.upsert_atlas_initiative_resource(text,text,text,text,text,text,text,text,bigint) from public;

do $migration$
declare
  role_name text;
begin
  foreach role_name in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = role_name) then
      execute format('revoke all on table public.atlas_initiatives, public.atlas_initiative_projects, public.atlas_initiative_relations, public.atlas_initiative_updates, public.atlas_initiative_resources, public.atlas_initiative_activity_log from %I', role_name);
      execute format('revoke execute on function public.set_atlas_initiative_project(text,text,boolean,text) from %I', role_name);
      execute format('revoke execute on function public.set_atlas_initiative_parent(text,text,boolean,text) from %I', role_name);
      execute format('revoke execute on function public.post_atlas_initiative_update(text,text,text,text,text) from %I', role_name);
      execute format('revoke execute on function public.move_atlas_initiative_order(text,text,text,bigint) from %I', role_name);
      execute format('revoke execute on function public.transition_atlas_initiative(text,boolean,text,bigint) from %I', role_name);
      execute format('revoke execute on function public.upsert_atlas_initiative_resource(text,text,text,text,text,text,text,text,bigint) from %I', role_name);
    end if;
  end loop;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant select, insert, update on public.atlas_initiatives, public.atlas_initiative_projects,
      public.atlas_initiative_relations, public.atlas_initiative_resources to service_role;
    grant select, insert on public.atlas_initiative_updates, public.atlas_initiative_activity_log to service_role;
    grant usage, select on sequence public.atlas_initiative_activity_log_id_seq to service_role;
    revoke delete, truncate on public.atlas_initiatives, public.atlas_initiative_projects,
      public.atlas_initiative_relations, public.atlas_initiative_updates,
      public.atlas_initiative_resources, public.atlas_initiative_activity_log from service_role;
    revoke update on public.atlas_initiative_updates, public.atlas_initiative_activity_log from service_role;
    grant execute on function public.set_atlas_initiative_project(text,text,boolean,text) to service_role;
    grant execute on function public.set_atlas_initiative_parent(text,text,boolean,text) to service_role;
    grant execute on function public.post_atlas_initiative_update(text,text,text,text,text) to service_role;
    grant execute on function public.move_atlas_initiative_order(text,text,text,bigint) to service_role;
    grant execute on function public.transition_atlas_initiative(text,boolean,text,bigint) to service_role;
    grant execute on function public.upsert_atlas_initiative_resource(text,text,text,text,text,text,text,text,bigint) to service_role;
  end if;
end
$migration$;

comment on table public.atlas_initiatives is 'Strategic objectives above projects with Linear-style status, health, hierarchy, and rollups.';
comment on table public.atlas_initiative_relations is 'Acyclic multi-parent initiative graph, limited to five levels by mutation RPC.';
