-- Linear parity slice 7: comments, one-level threads, selected resolutions,
-- reactions, link attachments, inline anchors, mentions, and subscriptions.

create table if not exists public.atlas_comments (
  id text primary key,
  target_type text not null check (target_type in ('action','project','initiative','document','project_update','initiative_update')),
  target_id text not null,
  parent_comment_id text references public.atlas_comments(id) on delete restrict,
  thread_root_id text references public.atlas_comments(id) on delete restrict,
  body text not null,
  mentions jsonb not null default '[]'::jsonb check (jsonb_typeof(mentions)='array'),
  attachments jsonb not null default '[]'::jsonb check (jsonb_typeof(attachments)='array'),
  anchor jsonb check (anchor is null or jsonb_typeof(anchor)='object'),
  status text not null default 'active' check (status in ('active','archived')),
  resolved_at timestamptz,
  resolved_by text,
  resolution_comment_id text references public.atlas_comments(id) on delete restrict,
  revision bigint not null default 0 check (revision>=0),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  check ((parent_comment_id is null and thread_root_id is null) or (parent_comment_id is not null and thread_root_id is not null and parent_comment_id=thread_root_id))
);

create index if not exists atlas_comments_target_created_idx on public.atlas_comments(target_type,target_id,created_at);
create index if not exists atlas_comments_thread_idx on public.atlas_comments(thread_root_id,created_at) where thread_root_id is not null;
create index if not exists atlas_comments_parent_idx on public.atlas_comments(parent_comment_id) where parent_comment_id is not null;
create index if not exists atlas_comments_resolution_idx on public.atlas_comments(resolution_comment_id) where resolution_comment_id is not null;
create index if not exists atlas_comments_mentions_idx on public.atlas_comments using gin(mentions);

create table if not exists public.atlas_reactions (
  id text primary key,
  target_type text not null check (target_type in ('action','project','initiative','document','project_update','initiative_update','comment')),
  target_id text not null,
  emoji text not null,
  actor text not null,
  status text not null default 'active' check (status in ('active','removed')),
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  check (char_length(emoji) between 1 and 32)
);

create unique index if not exists atlas_reactions_active_actor_idx
  on public.atlas_reactions(target_type,target_id,emoji,actor) where status='active';
create index if not exists atlas_reactions_target_idx
  on public.atlas_reactions(target_type,target_id,status,emoji);

create table if not exists public.atlas_discussion_subscriptions (
  id text primary key,
  target_type text not null check (target_type in ('action','project','initiative','document','project_update','initiative_update')),
  target_id text not null,
  principal_id text not null,
  status text not null default 'active' check (status in ('active','muted')),
  created_at timestamptz not null default timezone('utc',now()),
  updated_at timestamptz not null default timezone('utc',now()),
  unique(target_type,target_id,principal_id)
);

create index if not exists atlas_discussion_subscriptions_principal_idx
  on public.atlas_discussion_subscriptions(principal_id,status,updated_at desc);

create table if not exists public.atlas_collaboration_activity_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  event text not null,
  old_value jsonb,
  new_value jsonb,
  actor text not null,
  created_at timestamptz not null default timezone('utc',now())
);

create index if not exists atlas_collaboration_activity_entity_idx
  on public.atlas_collaboration_activity_log(entity_type,entity_id,created_at desc);

create or replace function public.atlas_discussion_target_exists(p_target_type text,p_target_id text)
returns boolean language plpgsql stable set search_path='' as $function$
begin
  return case p_target_type
    when 'action' then exists(select 1 from public.atlas_actions where id=p_target_id)
    when 'project' then exists(select 1 from public.atlas_projects where id=p_target_id)
    when 'initiative' then exists(select 1 from public.atlas_initiatives where id=p_target_id)
    when 'document' then exists(select 1 from public.atlas_documents where id=p_target_id)
    when 'project_update' then exists(select 1 from public.atlas_project_updates where id=p_target_id)
    when 'initiative_update' then exists(select 1 from public.atlas_initiative_updates where id=p_target_id)
    when 'comment' then exists(select 1 from public.atlas_comments where id=p_target_id)
    else false end;
end $function$;

create or replace function public.atlas_validate_comment_row()
returns trigger language plpgsql set search_path='' as $function$
declare item jsonb; principal_count integer; unique_count integer; root_row public.atlas_comments%rowtype; resolution_row public.atlas_comments%rowtype;
begin
  if not public.atlas_discussion_target_exists(new.target_type,new.target_id) then raise exception using errcode='23503',message='ATLAS_COMMENT_TARGET_NOT_FOUND'; end if;
  if nullif(btrim(new.body),'') is null then raise exception using errcode='23514',message='ATLAS_COMMENT_BODY_REQUIRED'; end if;
  select count(*),count(distinct value) into principal_count,unique_count from jsonb_array_elements_text(new.mentions);
  if principal_count<>unique_count or exists(select 1 from jsonb_array_elements_text(new.mentions) mention where mention.value not in ('ransomed','codex','claude')) then raise exception using errcode='23514',message='ATLAS_COMMENT_MENTION_INVALID'; end if;
  for item in select value from jsonb_array_elements(new.attachments) loop
    if jsonb_typeof(item)<>'object' or nullif(btrim(item->>'title'),'') is null or coalesce(item->>'url','') !~ '^https://[^[:space:]]+$' or (item ? 'size_bytes' and ((item->>'size_bytes')::bigint<0)) then raise exception using errcode='23514',message='ATLAS_COMMENT_ATTACHMENT_INVALID'; end if;
  end loop;
  if new.anchor is not null then
    if nullif(btrim(new.anchor->>'field'),'') is null or nullif(new.anchor->>'quote','') is null then raise exception using errcode='23514',message='ATLAS_COMMENT_ANCHOR_INVALID'; end if;
    if new.anchor ? 'start' and (new.anchor->>'start')::integer<0 then raise exception using errcode='23514',message='ATLAS_COMMENT_ANCHOR_INVALID'; end if;
    if new.anchor ? 'end' and (new.anchor->>'end')::integer<coalesce((new.anchor->>'start')::integer,0) then raise exception using errcode='23514',message='ATLAS_COMMENT_ANCHOR_INVALID'; end if;
  end if;
  if new.parent_comment_id is not null then
    select * into root_row from public.atlas_comments where id=new.thread_root_id;
    if not found or root_row.parent_comment_id is not null or root_row.target_type<>new.target_type or root_row.target_id<>new.target_id then raise exception using errcode='23514',message='ATLAS_COMMENT_THREAD_INVALID'; end if;
  end if;
  if new.resolution_comment_id is not null then
    if new.parent_comment_id is not null then raise exception using errcode='23514',message='ATLAS_COMMENT_REPLY_CANNOT_RESOLVE'; end if;
    select * into resolution_row from public.atlas_comments where id=new.resolution_comment_id;
    if not found or resolution_row.status<>'active' or not (resolution_row.id=new.id or resolution_row.thread_root_id=new.id) then raise exception using errcode='23514',message='ATLAS_COMMENT_RESOLUTION_INVALID'; end if;
  end if;
  return new;
end $function$;

create or replace function public.atlas_validate_reaction_row()
returns trigger language plpgsql set search_path='' as $function$
begin
  if new.actor not in ('ransomed','codex','claude') then raise exception using errcode='23514',message='ATLAS_REACTION_ACTOR_INVALID'; end if;
  if not public.atlas_discussion_target_exists(new.target_type,new.target_id) then raise exception using errcode='23503',message='ATLAS_REACTION_TARGET_NOT_FOUND'; end if;
  if new.emoji ~ '[[:space:]]' then raise exception using errcode='23514',message='ATLAS_REACTION_EMOJI_INVALID'; end if;
  return new;
end $function$;

create or replace function public.atlas_validate_subscription_row()
returns trigger language plpgsql set search_path='' as $function$
begin
  if new.principal_id not in ('ransomed','codex','claude') then raise exception using errcode='23514',message='ATLAS_SUBSCRIPTION_PRINCIPAL_INVALID'; end if;
  if not public.atlas_discussion_target_exists(new.target_type,new.target_id) then raise exception using errcode='23503',message='ATLAS_SUBSCRIPTION_TARGET_NOT_FOUND'; end if;
  return new;
end $function$;

create or replace function public.atlas_audit_collaboration_row()
returns trigger language plpgsql set search_path='' as $function$
declare kind text; row_id text; actor_value text; event_name text; new_json jsonb:=to_jsonb(new); old_json jsonb:=case when tg_op='INSERT' then null else to_jsonb(old) end;
begin
  kind:=case tg_table_name when 'atlas_comments' then 'comment' when 'atlas_reactions' then 'reaction' else 'subscription' end;
  row_id:=new_json->>'id';
  actor_value:=case when tg_table_name='atlas_comments' then case when tg_op='INSERT' then new_json->>'created_by' else new_json->>'updated_by' end when tg_table_name='atlas_reactions' then new_json->>'actor' else new_json->>'principal_id' end;
  event_name:=case when tg_op='INSERT' then kind||'_created' when tg_table_name='atlas_comments' and (new_json->>'resolved_at') is distinct from (old_json->>'resolved_at') then case when new_json->>'resolved_at' is null then 'thread_reopened' else 'thread_resolved' end when (new_json->>'status') is distinct from (old_json->>'status') then kind||'_'||(new_json->>'status') else kind||'_updated' end;
  insert into public.atlas_collaboration_activity_log(entity_type,entity_id,event,old_value,new_value,actor)
  values(kind,row_id,event_name,old_json,new_json,actor_value);
  return new;
end $function$;

revoke all on function public.atlas_discussion_target_exists(text,text) from public;
revoke all on function public.atlas_validate_comment_row() from public;
revoke all on function public.atlas_validate_reaction_row() from public;
revoke all on function public.atlas_validate_subscription_row() from public;
revoke all on function public.atlas_audit_collaboration_row() from public;

create trigger atlas_comments_validate_row before insert or update on public.atlas_comments for each row execute function public.atlas_validate_comment_row();
create trigger atlas_reactions_validate_row before insert or update on public.atlas_reactions for each row execute function public.atlas_validate_reaction_row();
create trigger atlas_subscriptions_validate_row before insert or update on public.atlas_discussion_subscriptions for each row execute function public.atlas_validate_subscription_row();
create trigger atlas_comments_audit_row after insert or update on public.atlas_comments for each row execute function public.atlas_audit_collaboration_row();
create trigger atlas_reactions_audit_row after insert or update on public.atlas_reactions for each row execute function public.atlas_audit_collaboration_row();
create trigger atlas_subscriptions_audit_row after insert or update on public.atlas_discussion_subscriptions for each row execute function public.atlas_audit_collaboration_row();

create or replace function public.create_atlas_comment(p_target_type text,p_target_id text,p_parent_comment_id text,p_body text,p_mentions jsonb,p_attachments jsonb,p_anchor jsonb,p_actor text)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare parent_row public.atlas_comments%rowtype; root_id text; comment_row public.atlas_comments%rowtype; mention text;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  if p_parent_comment_id is not null then
    select * into parent_row from public.atlas_comments where id=p_parent_comment_id and status='active';
    if not found then raise exception using errcode='P0002',message='ATLAS_COMMENT_PARENT_NOT_FOUND'; end if;
    if parent_row.target_type<>p_target_type or parent_row.target_id<>p_target_id then raise exception using errcode='23514',message='ATLAS_COMMENT_PARENT_TARGET_MISMATCH'; end if;
    root_id:=coalesce(parent_row.thread_root_id,parent_row.id);
  end if;
  insert into public.atlas_comments(id,target_type,target_id,parent_comment_id,thread_root_id,body,mentions,attachments,anchor,status,created_by,updated_by)
  values(gen_random_uuid()::text,p_target_type,p_target_id,root_id,root_id,btrim(p_body),coalesce(p_mentions,'[]'::jsonb),coalesce(p_attachments,'[]'::jsonb),p_anchor,'active',p_actor,p_actor) returning * into comment_row;
  insert into public.atlas_discussion_subscriptions(id,target_type,target_id,principal_id,status)
  values(gen_random_uuid()::text,p_target_type,p_target_id,p_actor,'active') on conflict(target_type,target_id,principal_id) do update set status='active',updated_at=timezone('utc',now());
  for mention in select value from jsonb_array_elements_text(coalesce(p_mentions,'[]'::jsonb)) loop
    insert into public.atlas_discussion_subscriptions(id,target_type,target_id,principal_id,status)
    values(gen_random_uuid()::text,p_target_type,p_target_id,mention,'active') on conflict(target_type,target_id,principal_id) do update set status='active',updated_at=timezone('utc',now());
  end loop;
  return to_jsonb(comment_row);
end $function$;

create or replace function public.update_atlas_comment(p_comment_id text,p_body text,p_mentions jsonb,p_attachments jsonb,p_actor text,p_expected_revision bigint)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare row_value public.atlas_comments%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into row_value from public.atlas_comments where id=p_comment_id for update;
  if not found then raise exception using errcode='P0002',message='ATLAS_COMMENT_NOT_FOUND'; end if;
  if row_value.created_by<>p_actor and p_actor<>'ransomed' then raise exception using errcode='42501',message='ATLAS_COMMENT_AUTHOR_REQUIRED'; end if;
  if row_value.status='archived' then raise exception using errcode='55000',message='ATLAS_COMMENT_ARCHIVED'; end if;
  if row_value.revision<>p_expected_revision then raise exception using errcode='40001',message='ATLAS_COMMENT_REVISION_CONFLICT'; end if;
  update public.atlas_comments set body=btrim(p_body),mentions=coalesce(p_mentions,'[]'::jsonb),attachments=coalesce(p_attachments,'[]'::jsonb),revision=revision+1,updated_by=p_actor,updated_at=timezone('utc',now()) where id=p_comment_id returning * into row_value;
  return to_jsonb(row_value);
end $function$;

create or replace function public.transition_atlas_comment(p_comment_id text,p_restore boolean,p_actor text,p_expected_revision bigint)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare row_value public.atlas_comments%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into row_value from public.atlas_comments where id=p_comment_id for update;
  if not found then raise exception using errcode='P0002',message='ATLAS_COMMENT_NOT_FOUND'; end if;
  if row_value.created_by<>p_actor and p_actor<>'ransomed' then raise exception using errcode='42501',message='ATLAS_COMMENT_AUTHOR_REQUIRED'; end if;
  if row_value.revision<>p_expected_revision then raise exception using errcode='40001',message='ATLAS_COMMENT_REVISION_CONFLICT'; end if;
  if not p_restore and exists(select 1 from public.atlas_comments root where root.resolution_comment_id=row_value.id and root.resolved_at is not null) then raise exception using errcode='55000',message='ATLAS_COMMENT_IS_THREAD_RESOLUTION'; end if;
  update public.atlas_comments set status=case when p_restore then 'active' else 'archived' end,revision=revision+1,updated_by=p_actor,updated_at=timezone('utc',now()) where id=p_comment_id returning * into row_value;
  return to_jsonb(row_value);
end $function$;

create or replace function public.resolve_atlas_comment_thread(p_root_comment_id text,p_resolution_comment_id text,p_resolved boolean,p_actor text,p_expected_revision bigint)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare root_row public.atlas_comments%rowtype; resolution_row public.atlas_comments%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into root_row from public.atlas_comments where id=p_root_comment_id for update;
  if not found or root_row.parent_comment_id is not null then raise exception using errcode='P0002',message='ATLAS_COMMENT_ROOT_NOT_FOUND'; end if;
  if root_row.status='archived' then raise exception using errcode='55000',message='ATLAS_COMMENT_ARCHIVED'; end if;
  if root_row.revision<>p_expected_revision then raise exception using errcode='40001',message='ATLAS_COMMENT_REVISION_CONFLICT'; end if;
  if p_resolved then
    select * into resolution_row from public.atlas_comments where id=coalesce(p_resolution_comment_id,p_root_comment_id) and status='active';
    if not found or not (resolution_row.id=root_row.id or resolution_row.thread_root_id=root_row.id) then raise exception using errcode='23514',message='ATLAS_COMMENT_RESOLUTION_INVALID'; end if;
  end if;
  update public.atlas_comments set resolved_at=case when p_resolved then timezone('utc',now()) else null end,resolved_by=case when p_resolved then p_actor else null end,resolution_comment_id=case when p_resolved then resolution_row.id else null end,revision=revision+1,updated_by=p_actor,updated_at=timezone('utc',now()) where id=root_row.id returning * into root_row;
  return to_jsonb(root_row);
end $function$;

create or replace function public.toggle_atlas_reaction(p_target_type text,p_target_id text,p_emoji text,p_actor text)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare reaction_row public.atlas_reactions%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  select * into reaction_row from public.atlas_reactions where target_type=p_target_type and target_id=p_target_id and emoji=p_emoji and actor=p_actor order by updated_at desc limit 1 for update;
  if found then
    update public.atlas_reactions set status=case when status='active' then 'removed' else 'active' end,updated_at=timezone('utc',now()) where id=reaction_row.id returning * into reaction_row;
  else
    insert into public.atlas_reactions(id,target_type,target_id,emoji,actor,status) values(gen_random_uuid()::text,p_target_type,p_target_id,p_emoji,p_actor,'active') returning * into reaction_row;
  end if;
  return to_jsonb(reaction_row);
end $function$;

create or replace function public.set_atlas_discussion_subscription(p_target_type text,p_target_id text,p_status text,p_actor text)
returns jsonb language plpgsql security definer set search_path='' as $function$
declare row_value public.atlas_discussion_subscriptions%rowtype;
begin
  if p_actor not in ('ransomed','codex','claude') then raise exception using errcode='22023',message='ATLAS_ACTOR_NOT_ALLOWED'; end if;
  if p_status not in ('active','muted') then raise exception using errcode='22023',message='ATLAS_SUBSCRIPTION_STATUS_INVALID'; end if;
  insert into public.atlas_discussion_subscriptions(id,target_type,target_id,principal_id,status)
  values(gen_random_uuid()::text,p_target_type,p_target_id,p_actor,p_status)
  on conflict(target_type,target_id,principal_id) do update set status=excluded.status,updated_at=timezone('utc',now()) returning * into row_value;
  return to_jsonb(row_value);
end $function$;

revoke all on function public.create_atlas_comment(text,text,text,text,jsonb,jsonb,jsonb,text) from public;
revoke all on function public.update_atlas_comment(text,text,jsonb,jsonb,text,bigint) from public;
revoke all on function public.transition_atlas_comment(text,boolean,text,bigint) from public;
revoke all on function public.resolve_atlas_comment_thread(text,text,boolean,text,bigint) from public;
revoke all on function public.toggle_atlas_reaction(text,text,text,text) from public;
revoke all on function public.set_atlas_discussion_subscription(text,text,text,text) from public;

drop trigger if exists atlas_comments_reject_delete on public.atlas_comments;
create trigger atlas_comments_reject_delete before delete on public.atlas_comments for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_reactions_reject_delete on public.atlas_reactions;
create trigger atlas_reactions_reject_delete before delete on public.atlas_reactions for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_subscriptions_reject_delete on public.atlas_discussion_subscriptions;
create trigger atlas_subscriptions_reject_delete before delete on public.atlas_discussion_subscriptions for each row execute function public.atlas_reject_immutable_delete();
drop trigger if exists atlas_collaboration_activity_reject_mutation on public.atlas_collaboration_activity_log;
create trigger atlas_collaboration_activity_reject_mutation before update or delete on public.atlas_collaboration_activity_log for each row execute function public.atlas_reject_project_history_mutation();

alter table public.atlas_comments enable row level security;
alter table public.atlas_reactions enable row level security;
alter table public.atlas_discussion_subscriptions enable row level security;
alter table public.atlas_collaboration_activity_log enable row level security;
revoke all on table public.atlas_comments,public.atlas_reactions,public.atlas_discussion_subscriptions,public.atlas_collaboration_activity_log from public;

do $migration$
declare role_name text;
begin
  foreach role_name in array array['anon','authenticated'] loop
    if exists(select 1 from pg_roles where rolname=role_name) then
      execute format('revoke all on table public.atlas_comments,public.atlas_reactions,public.atlas_discussion_subscriptions,public.atlas_collaboration_activity_log from %I',role_name);
      execute format('revoke execute on function public.create_atlas_comment(text,text,text,text,jsonb,jsonb,jsonb,text) from %I',role_name);
      execute format('revoke execute on function public.update_atlas_comment(text,text,jsonb,jsonb,text,bigint) from %I',role_name);
      execute format('revoke execute on function public.transition_atlas_comment(text,boolean,text,bigint) from %I',role_name);
      execute format('revoke execute on function public.resolve_atlas_comment_thread(text,text,boolean,text,bigint) from %I',role_name);
      execute format('revoke execute on function public.toggle_atlas_reaction(text,text,text,text) from %I',role_name);
      execute format('revoke execute on function public.set_atlas_discussion_subscription(text,text,text,text) from %I',role_name);
    end if;
  end loop;
  if exists(select 1 from pg_roles where rolname='service_role') then
    grant select,insert,update on public.atlas_comments,public.atlas_reactions,public.atlas_discussion_subscriptions to service_role;
    grant select,insert on public.atlas_collaboration_activity_log to service_role;
    grant usage,select on sequence public.atlas_collaboration_activity_log_id_seq to service_role;
    revoke delete,truncate on public.atlas_comments,public.atlas_reactions,public.atlas_discussion_subscriptions,public.atlas_collaboration_activity_log from service_role;
    revoke update on public.atlas_collaboration_activity_log from service_role;
    grant execute on function public.create_atlas_comment(text,text,text,text,jsonb,jsonb,jsonb,text) to service_role;
    grant execute on function public.update_atlas_comment(text,text,jsonb,jsonb,text,bigint) to service_role;
    grant execute on function public.transition_atlas_comment(text,boolean,text,bigint) to service_role;
    grant execute on function public.resolve_atlas_comment_thread(text,text,boolean,text,bigint) to service_role;
    grant execute on function public.toggle_atlas_reaction(text,text,text,text) to service_role;
    grant execute on function public.set_atlas_discussion_subscription(text,text,text,text) to service_role;
  end if;
end $migration$;

comment on table public.atlas_comments is 'Canonical Atlas root/reply discussions across work, updates, and documents.';
comment on table public.atlas_reactions is 'Unicode reactions with actor-level active/removed history.';
