// @vitest-environment jsdom

import React from'react';import{render,screen,waitFor}from'@testing-library/react';import axe from'axe-core';import{beforeEach,describe,expect,it,vi}from'vitest';import InsightsPage,{InsightVisualization}from'./InsightsPage.jsx';import*as hooks from'../hooks/useInsights.js';
vi.mock('../hooks/useInsights.js',()=>({useInsights:vi.fn(),useInsight:vi.fn(),useDashboards:vi.fn(),useDashboard:vi.fn(),useCreateInsight:vi.fn(),useUpdateInsight:vi.fn(),useRunInsight:vi.fn(),useArchiveInsight:vi.fn(),useCreateDashboard:vi.fn(),useAddDashboardCard:vi.fn()}));vi.mock('../hooks/useBusinesses.js',()=>({useBusinessContext:()=>({BUSINESS_LIST:[{id:'personal',label:'Personal'}]})}));
function mutation(result={}){return{mutate:vi.fn(),mutateAsync:vi.fn().mockResolvedValue(result),isPending:false}}
const result={measure:'effort',summary:{sum:5,average:2.5,filtered_count:2,missing_measure_count:0,p25:1.5,p50:2.5,p75:3.5,p95:3.9},chart_data:[{slice:'personal',segment:'p1',value:5,action_ids:['a1','a2']}],scatter_data:[{action_id:'a1',title:'First',value:2,slice:'p1',segment:'All'}],burn_up:[{bucket:'2026-08',created:2,completed:1}],table:[{id:'a1',title:'First',status:'done',priority:'p1',business:'personal',estimate_points:2,created_at:'2026-08-01T00:00:00Z'}]};
const insight={id:'i1',name:'Effort by project',description:'Resource allocation',measure:'effort',slice_by:'project',segment_by:'priority',chart_type:'bar',time_grouping:'monthly',filters:{},revision:2,snapshots:[{id:'s1',insight_revision:2,result,created_at:'2026-08-20T20:00:00Z'}]};const dashboard={id:'d1',name:'Delivery dashboard',description:'Core metrics',cards:[{id:'c1',insight_id:'i1',display_type:'chart',insight,result}]};
describe('InsightVisualization',()=>{it('renders metric, bar, scatter, burn-up, and table presentations',()=>{const{rerender}=render(<InsightVisualization result={result} chartType="metric" onOpenAction={vi.fn()}/>);expect(screen.getByText('5')).toBeTruthy();rerender(<InsightVisualization result={result} chartType="bar" onOpenAction={vi.fn()}/>);expect(screen.getByText(/personal/)).toBeTruthy();rerender(<InsightVisualization result={result} chartType="scatter" onOpenAction={vi.fn()}/>);expect(screen.getByRole('img',{name:'Insight scatterplot'})).toBeTruthy();rerender(<InsightVisualization result={result} chartType="burn_up" onOpenAction={vi.fn()}/>);expect(screen.getByRole('img',{name:'Burn-up chart'})).toBeTruthy();rerender(<InsightVisualization result={result} chartType="table" onOpenAction={vi.fn()}/>);expect(screen.getByRole('button',{name:'First'})).toBeTruthy()})});
describe('InsightsPage',()=>{beforeEach(()=>{vi.clearAllMocks();hooks.useInsights.mockReturnValue({data:[insight],isLoading:false});hooks.useInsight.mockReturnValue({data:insight,isLoading:false});hooks.useDashboards.mockReturnValue({data:[dashboard],isLoading:false});hooks.useDashboard.mockReturnValue({data:dashboard,isLoading:false});hooks.useRunInsight.mockReturnValue(mutation(result));for(const name of['useCreateInsight','useUpdateInsight','useArchiveInsight','useCreateDashboard','useAddDashboardCard'])hooks[name].mockReturnValue(mutation())});it('renders saved Insights, dashboards, and export controls',()=>{render(<InsightsPage insightId={null} dashboardId={null} selectedBusiness={null} onOpenInsight={vi.fn()} onOpenDashboard={vi.fn()} onOpenAction={vi.fn()} onBack={vi.fn()}/>);expect(screen.getByRole('heading',{name:'Insights'})).toBeTruthy();expect(screen.getByRole('button',{name:'Open insight: Effort by project'})).toBeTruthy();expect(screen.getByRole('button',{name:'Open dashboard: Delivery dashboard'})).toBeTruthy();expect(screen.getByRole('link',{name:/Actions CSV/})).toBeTruthy()});it('evaluates an Insight with snapshots and drill-down',async()=>{render(<InsightsPage insightId="i1" dashboardId={null} selectedBusiness={null} onOpenInsight={vi.fn()} onOpenDashboard={vi.fn()} onOpenAction={vi.fn()} onBack={vi.fn()}/>);expect(screen.getByRole('heading',{name:'Effort by project'})).toBeTruthy();await waitFor(()=>expect(screen.getByText(/personal/)).toBeTruthy());expect(screen.getByRole('link',{name:'CSV'})).toBeTruthy();expect(screen.getByText(/revision 2/)).toBeTruthy()});it('renders evaluated dashboard cards',()=>{render(<InsightsPage insightId={null} dashboardId="d1" selectedBusiness={null} onOpenInsight={vi.fn()} onOpenDashboard={vi.fn()} onOpenAction={vi.fn()} onBack={vi.fn()}/>);expect(screen.getByRole('heading',{name:'Delivery dashboard'})).toBeTruthy();expect(screen.getByText('Effort by project')).toBeTruthy()});it('has no automated semantic accessibility violations',async()=>{const{container}=render(<InsightsPage insightId={null} dashboardId="d1" selectedBusiness={null} onOpenInsight={vi.fn()} onOpenDashboard={vi.fn()} onOpenAction={vi.fn()} onBack={vi.fn()}/>);const findings=await axe.run(container,{rules:{'color-contrast':{enabled:false}}});expect(findings.violations).toEqual([])})});
