import { describe,expect,it } from 'vitest';import{consumeRoomRateLimit,parseDocumentRoomMessage,validDocumentSelection,type RoomAttachment}from'./documentRoomProtocol';
const attachment:RoomAttachment={documentId:'d1',actor:'ransomed',clientId:'browser:1',canEdit:true,selection:null,connectedAt:'2026-08-20T00:00:00Z',windowStartedAt:1000,messageCount:0,abuseCount:0,lastRevision:1};
describe('document room protocol',()=>{
  it('accepts ping, presence, and bounded edit envelopes',()=>{expect(parseDocumentRoomMessage(JSON.stringify({type:'ping',request_id:'r1'})).message).toMatchObject({type:'ping'});expect(parseDocumentRoomMessage(JSON.stringify({type:'presence',selection:{start:1,end:2},revision:1})).message).toMatchObject({type:'presence'});expect(parseDocumentRoomMessage(JSON.stringify({type:'edit',operation_id:'op1',base_revision:1,base_content_sha256:'a'.repeat(64),title:'Doc',content:'Body',selection:{start:0,end:4}})).message).toMatchObject({type:'edit',operation_id:'op1'})});
  it('rejects malformed, unknown, oversized, and invalid-selection messages',()=>{expect(parseDocumentRoomMessage('{').error).toBe('MESSAGE_JSON_INVALID');expect(parseDocumentRoomMessage(JSON.stringify({type:'unknown'})).error).toBe('MESSAGE_TYPE_UNSUPPORTED');expect(parseDocumentRoomMessage('x'.repeat(262145)).error).toBe('MESSAGE_TOO_LARGE');expect(parseDocumentRoomMessage(JSON.stringify({type:'presence',selection:{start:5,end:2}})).error).toBe('PRESENCE_SELECTION_INVALID')});
  it('validates selections against content bounds',()=>{expect(validDocumentSelection(null)).toBe(true);expect(validDocumentSelection({start:0,end:10},10)).toBe(true);expect(validDocumentSelection({start:0,end:11},10)).toBe(false)});
  it('allows twenty messages per second and closes after repeated abuse',()=>{let next=attachment;for(let i=0;i<20;i+=1){const result=consumeRoomRateLimit(next,1000);expect(result.allowed).toBe(true);next=result.attachment}for(let i=0;i<3;i+=1){const result=consumeRoomRateLimit(next,1000);expect(result.allowed).toBe(false);next=result.attachment;if(i===2)expect(result.close).toBe(true)}});
  it('resets the rate window after one second',()=>{const busy={...attachment,messageCount:20};const result=consumeRoomRateLimit(busy,2000);expect(result.allowed).toBe(true);expect(result.attachment.messageCount).toBe(1)});
});
