type Row = Record<string, any>;
const DAY = 86400000;
const TERMINAL = new Set(['done','completed','closed','canceled','cancelled','archived']);

export function statusType(status: unknown) {
  const value=String(status||'unknown');
  if(['done','completed','closed'].includes(value))return'completed';
  if(['canceled','cancelled'].includes(value))return'canceled';
  if(value==='archived')return'archived';
  if(['not_started','todo','open'].includes(value))return'backlog';
  return'active';
}

export function percentile(values:number[],percent:number){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);const index=(sorted.length-1)*percent;const lower=Math.floor(index);const upper=Math.ceil(index);if(lower===upper)return sorted[lower];return sorted[lower]+(sorted[upper]-sorted[lower])*(index-lower)}

export function dateBucket(value:unknown,grouping='monthly'){if(!value)return'Unknown';const date=new Date(String(value));if(Number.isNaN(date.valueOf()))return'Unknown';const year=date.getUTCFullYear();const month=date.getUTCMonth();if(grouping==='yearly')return String(year);if(grouping==='quarterly')return `${year}-Q${Math.floor(month/3)+1}`;if(grouping==='monthly')return `${year}-${String(month+1).padStart(2,'0')}`;if(grouping==='weekly'){const copy=new Date(Date.UTC(year,month,date.getUTCDate()));copy.setUTCDate(copy.getUTCDate()-copy.getUTCDay());return copy.toISOString().slice(0,10)}return date.toISOString().slice(0,10)}

function values(value:unknown){if(Array.isArray(value))return value.length?value.map(String):['None'];if(value===null||value===undefined||value==='')return['None'];return[String(value)]}

export function dimensionValues(action:Row,dimension:string,grouping='monthly'):string[]{
  switch(dimension){
    case'none':return['All'];case'status':return values(action.status);case'status_type':return[statusType(action.status)];case'owner':return values(action.owners);case'business':return values(action.business);case'priority':return values(action.priority);case'tag':return values(action.tags);case'estimate':return[action.estimate_points===null||action.estimate_points===undefined?'Unestimated':String(action.estimate_points)];case'template':return values(action.template_name||action.template_id);case'project':return values(action.project_name||action.project_id);case'initiative':return values((action.initiatives||[]).map((item:Row)=>item.name||item.id));case'cycle':return values(action.cycle_name||action.cycle_id);case'release':return values((action.releases||[]).map((item:Row)=>item.release?.name||item.release_id));case'pipeline':return values((action.releases||[]).map((item:Row)=>item.pipeline?.name||item.release?.pipeline_id));case'created_date':return[dateBucket(action.created_at,grouping)];case'completed_date':return[dateBucket(action.completed_at,grouping)];case'started_date':return[dateBucket(action.started_at,grouping)];case'due_date':return[dateBucket(action.due_date,grouping)];default:return['All'];
  }
}

function includesDimension(action:Row,key:string,expected:unknown){const wanted=Array.isArray(expected)?expected.map(String):[String(expected)];return dimensionValues(action,key).some(value=>wanted.includes(value))}
export function applyInsightFilters(actions:Row[],filters:Row={},includeArchived=false,excludeNoPriority=false){return actions.filter(action=>{if(!includeArchived&&action.status==='archived')return false;if(excludeNoPriority&&!action.priority)return false;for(const[key,expected]of Object.entries(filters||{})){if(expected===undefined||expected===null||expected===''||(Array.isArray(expected)&&!expected.length))continue;if(key==='created_after'&&String(action.created_at||'')<String(expected))return false;if(key==='created_before'&&String(action.created_at||'')>String(expected))return false;if(key==='completed_after'&&String(action.completed_at||'')<String(expected))return false;if(key==='completed_before'&&String(action.completed_at||'')>String(expected))return false;if(['status','owner','business','priority','tag','project','initiative','cycle','template','release','pipeline'].includes(key)&&!includesDimension(action,key,expected))return false;}return true})}

function measureValue(action:Row,measure:string,unestimatedValue:number,now:Date){if(measure==='issue_count')return 1;if(measure==='effort')return Number.isInteger(action.estimate_points)?Number(action.estimate_points):unestimatedValue;const end=measure==='issue_age'?now:(action.completed_at?new Date(action.completed_at):null);const start=measure==='cycle_time'?(action.started_at?new Date(action.started_at):null):measure==='triage_time'?(action.triaged_at?new Date(action.triaged_at):null):(action.created_at?new Date(action.created_at):null);const durationEnd=measure==='triage_time'?(action.started_at?new Date(action.started_at):null):end;if(!start||!durationEnd||Number.isNaN(start.valueOf())||Number.isNaN(durationEnd.valueOf())||durationEnd<start)return null;return (durationEnd.valueOf()-start.valueOf())/DAY}
function summary(valuesList:number[]){const sum=valuesList.reduce((total,value)=>total+value,0);return{count:valuesList.length,sum,average:valuesList.length?sum/valuesList.length:null,p25:percentile(valuesList,.25),p50:percentile(valuesList,.5),p75:percentile(valuesList,.75),p95:percentile(valuesList,.95)}}

function burnUp(actions:Row[],grouping:string){const events=new Map<string,{created:number;completed:number}>();for(const action of actions){const created=dateBucket(action.created_at,grouping);if(created!=='Unknown'){if(!events.has(created))events.set(created,{created:0,completed:0});events.get(created)!.created+=1}const completed=dateBucket(action.completed_at,grouping);if(completed!=='Unknown'){if(!events.has(completed))events.set(completed,{created:0,completed:0});events.get(completed)!.completed+=1}}let createdTotal=0,completedTotal=0;return Array.from(events.entries()).sort(([a],[b])=>a.localeCompare(b)).map(([bucket,event])=>{createdTotal+=event.created;completedTotal+=event.completed;return{bucket,created:createdTotal,completed:completedTotal}})}

export function computeInsight(actions:Row[],definition:Row,options:{unestimatedValue?:number;now?:Date}={}){
  const now=options.now||new Date();const unestimatedValue=options.unestimatedValue??1;const filtered=applyInsightFilters(actions,definition.filters||{},definition.include_archived===true,definition.exclude_no_priority===true);const measured=filtered.map(action=>({action,value:measureValue(action,definition.measure,unestimatedValue,now)}));const valid=measured.filter(item=>item.value!==null)as Array<{action:Row;value:number}>;const missing_measure_count=measured.length-valid.length;const grouping=definition.time_grouping||'monthly';const slice=definition.slice_by||'status';const segment=definition.segment_by||null;const cells=new Map<string,{slice:string;segment:string;values:number[];action_ids:string[]}>();for(const item of valid){for(const sliceValue of dimensionValues(item.action,slice,grouping))for(const segmentValue of segment?dimensionValues(item.action,segment,grouping):['All']){const key=`${sliceValue}\u0000${segmentValue}`;if(!cells.has(key))cells.set(key,{slice:sliceValue,segment:segmentValue,values:[],action_ids:[]});cells.get(key)!.values.push(item.value);cells.get(key)!.action_ids.push(String(item.action.id))}}
  const chart_data=Array.from(cells.values()).map(cell=>({...cell,...summary(cell.values),value:['issue_count','effort'].includes(definition.measure)?cell.values.reduce((a,b)=>a+b,0):summary(cell.values).average})).sort((a,b)=>a.slice.localeCompare(b.slice)||a.segment.localeCompare(b.segment));
  const scatter=valid.map(item=>({action_id:item.action.id,title:item.action.title,value:item.value,slice:dimensionValues(item.action,slice,grouping)[0],segment:segment?dimensionValues(item.action,segment,grouping)[0]:'All'}));
  const table=filtered.slice(0,2000).map(action=>({id:action.id,title:action.title,status:action.status,business:action.business,priority:action.priority,owners:action.owners,estimate_points:action.estimate_points,project:action.project_name||action.project_id||'',cycle:action.cycle_name||action.cycle_id||'',created_at:action.created_at,started_at:action.started_at,completed_at:action.completed_at,due_date:action.due_date}));
  const updated=filtered.map(action=>action.updated_at).filter(Boolean).sort().at(-1)||null;
  return{as_of:now.toISOString(),source_watermark:updated,definition_revision:definition.revision??0,measure:definition.measure,slice_by:slice,segment_by:segment,filters:definition.filters||{},summary:{...summary(valid.map(item=>item.value)),filtered_count:filtered.length,missing_measure_count},chart_data,scatter_data:scatter,burn_up:burnUp(filtered,grouping),table,action_ids:filtered.map(action=>String(action.id))}
}

export function mergeInsightFilters(...filters:Row[]){return Object.assign({},...filters.filter(Boolean))}

export function csvCell(value:unknown){let text=Array.isArray(value)?value.join('|'):value===null||value===undefined?'':typeof value==='object'?JSON.stringify(value):String(value);if(/^[=+\-@]/.test(text))text=`'${text}`;return`"${text.replace(/"/g,'""')}"`}
export function rowsToCsv(rows:Row[],headers?:string[]){const columns=headers||Array.from(new Set(rows.flatMap(row=>Object.keys(row))));return[columns.map(csvCell).join(','),...rows.map(row=>columns.map(column=>csvCell(row[column])).join(','))].join('\r\n')}
